// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Oleksii PELYKH

import type { CodegenConfig } from "@graphql-codegen/cli";

/**
 * GraphQL Codegen configuration.
 *
 * The schema and operation documents live in the private `ttctl/research` repo
 * (sibling to this repo in the local workspace) under:
 *
 *   - `../research/graphql/schema.graphql` — synthesized SDL covering the
 *     mobile gateway, web profile editor, and portal surfaces (unified).
 *   - `../research/graphql/operations/*.graphql` — extracted operation
 *     documents (mobile gateway APQ catalog).
 *
 * The generated TypeScript file at `packages/core/src/__generated__/graphql.ts`
 * is committed to this repo so contributors without research-repo access can
 * still build and use typed operations. Re-running `pnpm codegen` requires the
 * sibling `../research/` working copy and will overwrite the generated file.
 *
 * Run: `pnpm codegen`
 */
const config: CodegenConfig = {
  overwrite: true,
  schema: "../research/graphql/schema.graphql",
  // Wave-0 MVP wires up only the operations actually invoked from
  // `@ttctl/core` source. Expand this glob as additional operations come into
  // scope and the schema gaps they depend on are filled.
  documents: ["../research/graphql/operations/Viewer.graphql", "../research/graphql/operations/ProfileShow.graphql"],
  generates: {
    "packages/core/src/__generated__/graphql.ts": {
      plugins: [
        {
          add: {
            content: [
              "// SPDX-License-Identifier: AGPL-3.0-only",
              "// Copyright (C) 2026 Oleksii PELYKH",
              "//",
              "// AUTO-GENERATED by `pnpm codegen` from `../research/graphql/schema.graphql`",
              "// and selected operations under `../research/graphql/operations/`. Do not edit",
              "// by hand; re-run codegen instead.",
              "",
            ].join("\n"),
          },
        },
        "typescript",
        "typescript-operations",
      ],
      config: {
        useTypeImports: true,
        avoidOptionals: true,
        skipTypename: false,
        enumsAsTypes: true,
      },
    },
  },
};

export default config;
