// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Oleksii PELYKH
//
// AUTO-GENERATED by `pnpm codegen` from `../research/graphql/schema.graphql`
// and selected operations under `../research/graphql/operations/`. Do not edit
// by hand; re-run codegen instead.

/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  BigDecimal: { input: unknown; output: unknown; }
  Date: { input: unknown; output: unknown; }
  DateTime: { input: unknown; output: unknown; }
  PageSize: { input: unknown; output: unknown; }
  Time: { input: unknown; output: unknown; }
  TimeOfDay: { input: unknown; output: unknown; }
  Unknown: { input: unknown; output: unknown; }
  Upload: { input: unknown; output: unknown; }
};

export type AcceptFreelanceTalentAgreementPayload = MutationResult & {
  __typename?: 'AcceptFreelanceTalentAgreementPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type AcceptGigReachOutPayload = MutationResult & {
  __typename?: 'AcceptGigReachOutPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type AccessibleRole = {
  _placeholder: Maybe<Scalars['String']['output']>;
};

export type AcknowledgeAllTalentBadgesPayload = MutationResult & {
  __typename?: 'AcknowledgeAllTalentBadgesPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type AcknowledgeBadgeNotificationPayload = MutationResult & {
  __typename?: 'AcknowledgeBadgeNotificationPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type ActionStatusEnum =
  | 'NEGATIVE'
  | 'NEUTRAL'
  | 'PENDING'
  | 'POSITIVE';

export type AddProfileIndustryConnectionsPayload = MutationResult & {
  __typename?: 'AddProfileIndustryConnectionsPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type AddProfileSkillSetPayload = MutationResult & {
  __typename?: 'AddProfileSkillSetPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type AllocatedHoursChangeRequest = Node & {
  __typename?: 'AllocatedHoursChangeRequest';
  allocatedHours: Scalars['Int']['output'];
  comment: Scalars['String']['output'];
  futureAvailableHours: Maybe<Scalars['Unknown']['output']>;
  id: Scalars['ID']['output'];
  rejectReason: Maybe<Scalars['Unknown']['output']>;
  returnInDate: Maybe<Scalars['Unknown']['output']>;
  reviewedManually: Scalars['Boolean']['output'];
  statusV2: AllocatedHoursChangeRequestStatus;
  useReturnAvailability: Scalars['Boolean']['output'];
};

export type AllocatedHoursChangeRequestStatus = {
  __typename?: 'AllocatedHoursChangeRequestStatus';
  value: Scalars['String']['output'];
};

export type AllocatedHoursChangeRequestStatusEnum =
  | 'ACCEPTED'
  | 'CANCELLED'
  | 'PENDING'
  | 'REJECTED';

export type ApnTokenRegisterPayload = MutationResult & {
  __typename?: 'ApnTokenRegisterPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type ApnTokenRemovePayload = MutationResult & {
  __typename?: 'ApnTokenRemovePayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type ApnTokensOps = {
  __typename?: 'ApnTokensOps';
  register: Maybe<ApnTokenRegisterPayload>;
};


export type ApnTokensOpsRegisterArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};

export type Application = AvailabilityRequest | JobApplication;

export type AttachTalentVideoPitchPayload = MutationResult & {
  __typename?: 'AttachTalentVideoPitchPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type AuthOps = {
  __typename?: 'AuthOps';
  sendPasswordResetEmail: Maybe<SendResetPasswordEmailPayload>;
  signIn: Maybe<SignInPayload>;
};


export type AuthOpsSendPasswordResetEmailArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type AuthOpsSignInArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};

export type AvailabilityRequest = Node & {
  __typename?: 'AvailabilityRequest';
  answeredAt: Maybe<Scalars['DateTime']['output']>;
  comment: Maybe<Scalars['String']['output']>;
  createdAt: Scalars['DateTime']['output'];
  id: Scalars['ID']['output'];
  jirStatus: AvailabilityRequestStatus;
  job: TalentJob;
  jobExpertiseAnswers: Array<Maybe<Scalars['Unknown']['output']>>;
  jobPositionAnswers: Array<Maybe<JobPositionAnswer>>;
  metadata: AvailabilityRequestFixedMetadata;
  rejectReason: Maybe<Scalars['Unknown']['output']>;
  requestedHourlyRate: Money;
  statusV2: AvailabilityRequestStatus;
  talentComment: Scalars['String']['output'];
  updatedAt: Scalars['DateTime']['output'];
};

export type AvailabilityRequestAnsweredAfterThresholdContext = {
  __typename?: 'AvailabilityRequestAnsweredAfterThresholdContext';
  availabilityRequest: Maybe<AvailabilityRequest>;
  timeUntilAnsweredInSeconds: Maybe<Scalars['Int']['output']>;
};

export type AvailabilityRequestConfirmPayload = MutationResult & {
  __typename?: 'AvailabilityRequestConfirmPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type AvailabilityRequestFixedMetadata = {
  __typename?: 'AvailabilityRequestFixedMetadata';
  estimatedRevenue: Maybe<Scalars['String']['output']>;
  estimatedRevenueExplanation: Maybe<Scalars['String']['output']>;
  longTermDisclaimer: Maybe<Scalars['String']['output']>;
  offeredHourlyRate: Money;
};

export type AvailabilityRequestKindEnum =
  | '_UNKNOWN';

export type AvailabilityRequestMetrics = {
  __typename?: 'AvailabilityRequestMetrics';
  answeredCount: Scalars['Int']['output'];
  averageResponseTime: Scalars['Float']['output'];
  isRelevant: Scalars['Boolean']['output'];
};

export type AvailabilityRequestOps = {
  __typename?: 'AvailabilityRequestOps';
  confirm: Maybe<AvailabilityRequestConfirmPayload>;
  reject: Maybe<AvailabilityRequestRejectPayload>;
};


export type AvailabilityRequestOpsConfirmArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type AvailabilityRequestOpsRejectArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};

export type AvailabilityRequestRejectPayload = MutationResult & {
  __typename?: 'AvailabilityRequestRejectPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type AvailabilityRequestRejectReason = {
  __typename?: 'AvailabilityRequestRejectReason';
  customPlaceholder: Maybe<Scalars['String']['output']>;
  isMandatory: Scalars['Boolean']['output'];
  key: Scalars['String']['output'];
  value: Scalars['String']['output'];
};

export type AvailabilityRequestRejectReasonsTypeV3 = {
  __typename?: 'AvailabilityRequestRejectReasonsTypeV3';
  fixed: Array<Maybe<AvailabilityRequestRejectReason>>;
  flexible: Array<Maybe<AvailabilityRequestRejectReason>>;
};

export type AvailabilityRequestStatus = {
  __typename?: 'AvailabilityRequestStatus';
  value: Scalars['String']['output'];
};

export type AvailabilityRequestStatusEnum =
  | 'CANCELLED'
  | 'CONFIRMED'
  | 'EXPIRED'
  | 'PENDING'
  | 'REJECTED'
  | 'WITHDRAWN';

export type Badge = Node & {
  __typename?: 'Badge';
  achievedAt: Maybe<Scalars['DateTime']['output']>;
  animation: Scalars['String']['output'];
  backgroundGradientBottom: Scalars['String']['output'];
  backgroundGradientTop: Scalars['String']['output'];
  celebrationText: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  image: Scalars['String']['output'];
  level: Scalars['Int']['output'];
  longDescription: Scalars['String']['output'];
  name: Scalars['String']['output'];
  progress: Maybe<Scalars['Int']['output']>;
};

export type BadgeConnection = {
  __typename?: 'BadgeConnection';
  nodes: Array<Maybe<Badge>>;
};

export type BadgeContext = {
  __typename?: 'BadgeContext';
  badge: Maybe<Badge>;
};

export type BadgeGroup = Node & {
  __typename?: 'BadgeGroup';
  badges: BadgeConnection;
  id: Scalars['ID']['output'];
  order: Maybe<Scalars['Int']['output']>;
};

export type BadgeGroupConnection = {
  __typename?: 'BadgeGroupConnection';
  nodes: Array<Maybe<BadgeGroup>>;
};

export type BadgedLogic =
  | 'AND'
  | 'OR';

export type BillingCycle = Node & {
  __typename?: 'BillingCycle';
  endDate: Scalars['Date']['output'];
  engagement: TalentEngagement;
  hours: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  minimumCommitment: Maybe<Scalars['Unknown']['output']>;
  startDate: Scalars['Date']['output'];
  timesheetOverdue: Scalars['Boolean']['output'];
  timesheetSubmissionDeadlineDatetime: Scalars['DateTime']['output'];
  timesheetSubmissionOpenDatetime: Scalars['DateTime']['output'];
  timesheetSubmitted: Scalars['Boolean']['output'];
};

export type BillingCycleConnection = {
  __typename?: 'BillingCycleConnection';
  ids: Array<Maybe<Scalars['ID']['output']>>;
  nodes: Array<Maybe<BillingCycle>>;
};

export type BooleanFilter = {
  eq: InputMaybe<Scalars['Boolean']['input']>;
};

export type BudgetFitFilterEnum =
  | 'FIT'
  | 'FIT_OR_10_PERCENT_LESS'
  | 'FIT_OR_20_PERCENT_LESS'
  | 'FIT_OR_30_PERCENT_LESS';

export type Center = {
  __typename?: 'Center';
  notifications: NotificationConnection;
};

export type Certification = Node & {
  __typename?: 'Certification';
  certificate: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  institution: Scalars['String']['output'];
  skills: SkillConnection;
  validFromMonth: Scalars['Int']['output'];
  validFromYear: Scalars['Int']['output'];
  validToMonth: Maybe<Scalars['Unknown']['output']>;
  validToYear: Maybe<Scalars['Unknown']['output']>;
};

export type CertificationConnection = {
  __typename?: 'CertificationConnection';
  nodes: Array<Maybe<Certification>>;
};

export type Client = Node & {
  __typename?: 'Client';
  city: Maybe<Scalars['String']['output']>;
  countryName: Maybe<Scalars['String']['output']>;
  crunchbase: Maybe<Scalars['Unknown']['output']>;
  facebook: Maybe<Scalars['Unknown']['output']>;
  foundingYear: Maybe<Scalars['String']['output']>;
  fullName: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  industry: Maybe<Scalars['String']['output']>;
  isEnterprise: Scalars['Boolean']['output'];
  linkedin: Maybe<Scalars['Unknown']['output']>;
  teamSize: TeamSize;
  twitter: Maybe<Scalars['Unknown']['output']>;
  website: Maybe<Scalars['Unknown']['output']>;
};

export type CodeOfConductAcceptPayload = MutationResult & {
  __typename?: 'CodeOfConductAcceptPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type CommitmentEnum =
  | 'FULL_TIME'
  | 'HOURLY'
  | 'PART_TIME';

export type CommitmentHoursDictionary = {
  __typename?: 'CommitmentHoursDictionary';
  full_time: Scalars['Int']['output'];
  hourly: Scalars['Int']['output'];
  part_time: Scalars['Int']['output'];
};

export type CommitmentType = {
  __typename?: 'CommitmentType';
  slug: Scalars['String']['output'];
};

export type CommunityEventContactLeaderPayload = MutationResult & {
  __typename?: 'CommunityEventContactLeaderPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type CommunityEventOps = {
  __typename?: 'CommunityEventOps';
  rsvp: Maybe<RsvpPayload>;
};


export type CommunityEventOpsRsvpArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};

export type CompanyRepresentative = Node & {
  __typename?: 'CompanyRepresentative';
  email: Scalars['String']['output'];
  fullName: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  phoneNumber: Scalars['String']['output'];
  position: Scalars['String']['output'];
  timeZone: TimeZone;
};

export type CompleteConsultationsTrainingPayload = MutationResult & {
  __typename?: 'CompleteConsultationsTrainingPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type CompleteTalentConsultingOnboardingPayload = MutationResult & {
  __typename?: 'CompleteTalentConsultingOnboardingPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type CompleteTalentConsultingTrainingPayload = MutationResult & {
  __typename?: 'CompleteTalentConsultingTrainingPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type ConfigurePushNotificationsPayload = MutationResult & {
  __typename?: 'ConfigurePushNotificationsPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type ContactFields = {
  __typename?: 'ContactFields';
  communitySlackId: Scalars['String']['output'];
  email: Scalars['String']['output'];
  phoneNumber: Maybe<Scalars['String']['output']>;
  skype: Maybe<Scalars['String']['output']>;
};

export type CreateApplicantPayload = MutationResult & {
  __typename?: 'CreateApplicantPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type CreateBecomeClientPayload = MutationResult & {
  __typename?: 'CreateBecomeClientPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type CreateCoachingEngagementPayload = MutationResult & {
  __typename?: 'CreateCoachingEngagementPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type CreateCommunityLeaderApplicationPayload = MutationResult & {
  __typename?: 'CreateCommunityLeaderApplicationPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type CreateDirectReferralPayload = MutationResult & {
  __typename?: 'CreateDirectReferralPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type CreateEngagementTestimonialPayload = MutationResult & {
  __typename?: 'CreateEngagementTestimonialPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type CreateForTestingPayload = MutationResult & {
  __typename?: 'CreateForTestingPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type CreateMarketplaceHelpRequestPayload = MutationResult & {
  __typename?: 'CreateMarketplaceHelpRequestPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type CreatePaymentOptionPayload = MutationResult & {
  __typename?: 'CreatePaymentOptionPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type CreateRateChangeRequestPayload = MutationResult & {
  __typename?: 'CreateRateChangeRequestPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type CreateTalentSignalPayload = MutationResult & {
  __typename?: 'CreateTalentSignalPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type CreateTopChatConversationPayload = MutationResult & {
  __typename?: 'CreateTopChatConversationPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type CreateTopChatUploadPayload = MutationResult & {
  __typename?: 'CreateTopChatUploadPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type DesiredOverlappingHoursFilter = {
  from: InputMaybe<Scalars['Time']['input']>;
  to: InputMaybe<Scalars['Time']['input']>;
};

export type DevelopmentCreateAvailabilityRequestPayload = MutationResult & {
  __typename?: 'DevelopmentCreateAvailabilityRequestPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type DevelopmentCreateEngagementPayload = MutationResult & {
  __typename?: 'DevelopmentCreateEngagementPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type DevelopmentCreateInterviewPayload = MutationResult & {
  __typename?: 'DevelopmentCreateInterviewPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type DevelopmentCreateMobileAnnouncementPayload = MutationResult & {
  __typename?: 'DevelopmentCreateMobileAnnouncementPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type DevelopmentSendSurveyInterviewEndedPayload = MutationResult & {
  __typename?: 'DevelopmentSendSurveyInterviewEndedPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type DevelopmentSendSurveyMidEngagementPayload = MutationResult & {
  __typename?: 'DevelopmentSendSurveyMidEngagementPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type Education = Node & {
  __typename?: 'Education';
  degree: Scalars['String']['output'];
  fieldOfStudy: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  institution: Scalars['String']['output'];
  location: Scalars['String']['output'];
  skills: SkillConnection;
  yearFrom: Scalars['Int']['output'];
  yearTo: Scalars['Int']['output'];
};

export type EducationConnection = {
  __typename?: 'EducationConnection';
  nodes: Array<Maybe<Education>>;
};

export type Employment = Node & {
  __typename?: 'Employment';
  company: Scalars['String']['output'];
  companyWebsite: Maybe<Scalars['String']['output']>;
  endDate: Scalars['Int']['output'];
  experienceItems: Array<Maybe<Scalars['String']['output']>>;
  highlight: Scalars['Boolean']['output'];
  id: Scalars['ID']['output'];
  industries: IndustryConnection;
  isEnterpriseExperience: Maybe<Scalars['Boolean']['output']>;
  managementExperience: ManagementExperience;
  position: Scalars['String']['output'];
  primaryGeography: Maybe<Scalars['Unknown']['output']>;
  reportingTo: Array<Maybe<Scalars['Unknown']['output']>>;
  showViaToptal: Scalars['Boolean']['output'];
  skills: SkillConnection;
  startDate: Scalars['Int']['output'];
};

export type EmploymentConnection = {
  __typename?: 'EmploymentConnection';
  nodes: Array<Maybe<Employment>>;
};

export type EngagementAdditionalInfo = {
  __typename?: 'EngagementAdditionalInfo';
  status: Maybe<Scalars['String']['output']>;
};

export type EngagementAgreement = {
  __typename?: 'EngagementAgreement';
  applicationRate: Scalars['String']['output'];
  commitment: CommitmentType;
  marketplaceMargin: Maybe<Scalars['Unknown']['output']>;
  talentHourlyRate: Scalars['String']['output'];
  talentRate: Scalars['String']['output'];
  timePeriod: Scalars['String']['output'];
};

export type EngagementBillCycle = {
  __typename?: 'EngagementBillCycle';
  verbose: Scalars['String']['output'];
};

export type EngagementBreakCancelPayload = MutationResult & {
  __typename?: 'EngagementBreakCancelPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type EngagementBreakOps = {
  __typename?: 'EngagementBreakOps';
  cancel: Maybe<EngagementBreakCancelPayload>;
  reschedule: Maybe<EngagementBreakReschedulePayload>;
};


export type EngagementBreakOpsCancelArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type EngagementBreakOpsRescheduleArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};

export type EngagementBreakReschedulePayload = MutationResult & {
  __typename?: 'EngagementBreakReschedulePayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type EngagementCreateBreakPayload = MutationResult & {
  __typename?: 'EngagementCreateBreakPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type EngagementDeliveryModelIdentifier =
  | 'CORE'
  | 'EXPERT_CROWD'
  | 'MARKETPLACE'
  | 'TOPTAL_RECRUIT';

export type EngagementOperations = {
  __typename?: 'EngagementOperations';
  scheduleEngagementBreak: EngagementOperationsScheduleEngagementBreak;
};

export type EngagementOperationsScheduleEngagementBreak = {
  __typename?: 'EngagementOperationsScheduleEngagementBreak';
  callable: Scalars['String']['output'];
};

export type EngagementOps = {
  __typename?: 'EngagementOps';
  createBreak: Maybe<EngagementCreateBreakPayload>;
  proposeEndDate: Maybe<MutationResult>;
};


export type EngagementOpsCreateBreakArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type EngagementOpsProposeEndDateArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};

export type EngagementRatePeriodEnum =
  | 'HOUR'
  | 'WEEK';

export type EngagementStatusEnum =
  | 'ACTIVE'
  | 'COMPLETED';

export type EngagementTrialStatusEnum =
  | 'CANCELED'
  | 'EXPIRED'
  | 'PENDING'
  | 'REJECTED'
  | 'SUCCESSFUL';

export type EnrollInLearningProgramPayload = MutationResult & {
  __typename?: 'EnrollInLearningProgramPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type EstimatedLengthFilterEnum =
  | 'FROM_1_TO_2_WEEKS'
  | 'FROM_2_TO_3_MONTHS'
  | 'FROM_2_TO_4_WEEKS'
  | 'FROM_3_TO_6_MONTHS'
  | 'FROM_4_TO_8_WEEKS'
  | 'FROM_6_TO_12_MONTHS'
  | 'OVER_12_MONTHS'
  | 'UNKNOWN';

export type FeedbackReason = {
  __typename?: 'FeedbackReason';
  identifier: Scalars['String']['output'];
  nameForRole: Scalars['String']['output'];
};

export type HideCommunitySlackChannelRecommendationPayload = MutationResult & {
  __typename?: 'HideCommunitySlackChannelRecommendationPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type HourlyRate = {
  __typename?: 'HourlyRate';
  budgetFit: Scalars['String']['output'];
};

export type HourlyRateFilter = {
  budgetFit: InputMaybe<Scalars['Unknown']['input']>;
};

export type Industry = Node & {
  __typename?: 'Industry';
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
};

export type IndustryConnection = {
  __typename?: 'IndustryConnection';
  nodes: Array<Maybe<Industry>>;
  totalCount: Scalars['Int']['output'];
};

export type IndustryConnections = {
  __typename?: 'IndustryConnections';
  nodes: Array<Maybe<Employment>>;
};

export type IndustryConnectionsCreateInput = {
  industryId: Scalars['String']['input'];
  profileItems: Array<InputMaybe<Scalars['Unknown']['input']>>;
};

export type InterviewAcceptPayload = MutationResult & {
  __typename?: 'InterviewAcceptPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type InterviewContext = {
  __typename?: 'InterviewContext';
  subject: Maybe<Scalars['Unknown']['output']>;
};

export type InterviewGuideSectionIdentifierEnum =
  | 'ASK_YOUR_CLIENT'
  | 'GAPS'
  | 'JOB_HIGHLIGHTS'
  | 'POTENTIAL_QUESTIONS'
  | 'PRO_TIPS'
  | 'STRENGTHS';

export type InterviewGuideTipIdentifierEnum =
  | 'BE_PRESENTABLE'
  | 'CAMERA_ON'
  | 'DONT_DISCUSS_RATE'
  | 'GAP_ANALYSIS'
  | 'HIRING_FACTORS'
  | 'JOB_SUMMARY'
  | 'PROFILE_REFERENCES'
  | 'QUESTIONS_TO_ASK'
  | 'QUESTIONS_TO_PREPARE_FOR'
  | 'SMALL_TALK'
  | 'STANDARD_QUESTIONS'
  | 'STRENGTHS_OVERLAP';

export type InterviewKindEnum =
  | 'EXTERNAL'
  | 'INTERNAL';

export type InterviewOps = {
  __typename?: 'InterviewOps';
  accept: Maybe<InterviewAcceptPayload>;
  reject: Maybe<InterviewRejectPayload>;
};


export type InterviewOpsAcceptArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type InterviewOpsRejectArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};

export type InterviewRejectPayload = MutationResult & {
  __typename?: 'InterviewRejectPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type InterviewRejectReason = {
  __typename?: 'InterviewRejectReason';
  commentRequired: Scalars['Boolean']['output'];
  identifier: Scalars['String']['output'];
  label: Scalars['String']['output'];
};

export type InterviewStatusEnum =
  | 'ACCEPTED'
  | 'MISSED'
  | 'PENDING'
  | 'REJECTED'
  | 'SCHEDULED'
  | 'TIME_ACCEPTED'
  | 'TIME_REJECTED';

export type InterviewTalentNotesPayload = MutationResult & {
  __typename?: 'InterviewTalentNotesPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type JobActivityItemStatus = {
  __typename?: 'JobActivityItemStatus';
  value: Scalars['String']['output'];
  verbose: Scalars['String']['output'];
};

export type JobActivityItemStatusEnum =
  | 'ACTIVE'
  | 'APPLICATION_REJECTED'
  | 'APPLIED'
  | 'AVAILABILITY_REQUEST_CONFIRMED'
  | 'AVAILABILITY_REQUEST_EXPIRED'
  | 'AVAILABILITY_REQUEST_PENDING'
  | 'AVAILABILITY_REQUEST_REJECTED'
  | 'AVAILABILITY_REQUEST_WITHDRAWN'
  | 'CANCELED'
  | 'CLIENT_PENDING_LEGAL'
  | 'COMPLETED'
  | 'INTERNAL_INTERVIEW_AWAITING_CONFIRMATION'
  | 'INTERNAL_INTERVIEW_CANCELED'
  | 'INTERNAL_INTERVIEW_REQUEST_MISSED'
  | 'INTERNAL_INTERVIEW_SCHEDULED'
  | 'INTERNAL_INTERVIEW_TIME_REJECTED'
  | 'INTERVIEW_AWAITING_CONFIRMATION'
  | 'INTERVIEW_CANCELED'
  | 'INTERVIEW_REQUEST_MISSED'
  | 'INTERVIEW_SCHEDULED'
  | 'INTERVIEW_TIME_REJECTED'
  | 'JOB_CANCELED'
  | 'ON_BREAK'
  | 'ON_HOLD'
  | 'ON_TRIAL'
  | 'PENDING_START'
  | 'POSITION_FULFILLED'
  | 'PROFILE_SENT_TO_CLIENT'
  | 'REJECTED_AFTER_TRIAL'
  | 'REJECTED_BY_CLIENT'
  | 'REJECTED_BY_MATCHER'
  | 'WAITING_AFTER_INTERNAL_INTERVIEW'
  | 'WAITING_AFTER_INTERVIEW';

export type JobActivityItemStatusGroup = {
  __typename?: 'JobActivityItemStatusGroup';
  value: Scalars['String']['output'];
  verbose: Scalars['String']['output'];
};

export type JobActivityItemStatusGroupEnum =
  | 'ACTIVE_ENGAGEMENT'
  | 'ARCHIVED'
  | 'CLOSED_ENGAGEMENT'
  | 'ON_CLIENT_REVIEW'
  | 'ON_RECRUITER_REVIEW';

export type JobActivityList = {
  __typename?: 'JobActivityList';
  entities: Array<Maybe<TalentJobActivityItem>>;
  ids: Array<Maybe<Scalars['ID']['output']>>;
  totalCount: Scalars['Int']['output'];
};

export type JobAlertsSubscriptionEnum =
  | 'ALL'
  | 'MATCHED'
  | 'NONE';

export type JobApplication = Node & {
  __typename?: 'JobApplication';
  id: Scalars['ID']['output'];
  requestedHourlyRate: Money;
};

export type JobApplyPayload = MutationResult & {
  __typename?: 'JobApplyPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type JobClearInterestStatusPayload = MutationResult & {
  __typename?: 'JobClearInterestStatusPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type JobCommitmentFilterEnum =
  | 'FROM_10_TO_20_HOURS'
  | 'FROM_20_TO_30_HOURS'
  | 'FROM_30_TO_40_HOURS'
  | 'FULL_TIME'
  | 'HOURLY'
  | 'PART_TIME'
  | 'SUITABLE'
  | 'UP_TO_10_HOURS';

export type JobEstimatedLength = {
  __typename?: 'JobEstimatedLength';
  enumValue: Scalars['String']['output'];
};

export type JobEstimatedLengthEnum =
  | 'FROM_1_TO_2_WEEKS'
  | 'FROM_2_TO_3_MONTHS'
  | 'FROM_2_TO_4_WEEKS'
  | 'FROM_3_TO_6_MONTHS'
  | 'FROM_4_TO_8_WEEKS'
  | 'FROM_6_TO_12_MONTHS'
  | 'OVER_12_MONTHS'
  | 'UNKNOWN';

export type JobExpertiseAnswerInput = {
  other: InputMaybe<Scalars['Unknown']['input']>;
  questionId: Scalars['String']['input'];
  subjectId: InputMaybe<Scalars['Unknown']['input']>;
};

export type JobHiringStatus = {
  __typename?: 'JobHiringStatus';
  hiredCount: Scalars['Int']['output'];
  hiringStatus: Scalars['String']['output'];
  hiringStatusColor: Scalars['String']['output'];
  verbose: Maybe<Scalars['String']['output']>;
};

export type JobHiringStatusEnum =
  | 'ACCEPTING_APPLICATIONS'
  | 'ALREADY_INTERVIEWING'
  | 'BE_FIRST_TO_APPLY'
  | 'CANDIDATES_INTRODUCED_TO_CLIENT'
  | 'FULFILLED'
  | 'INELIGIBLE'
  | 'REVIEWING_APPLICATIONS';

export type JobIndustriesConnection = {
  __typename?: 'JobIndustriesConnection';
  edges: Array<Maybe<JobIndustryEdge>>;
};

export type JobIndustryEdge = {
  __typename?: 'JobIndustryEdge';
  node: Industry;
};

export type JobList = {
  __typename?: 'JobList';
  entities: Array<Maybe<TalentJob>>;
  ids: Array<Maybe<Scalars['ID']['output']>>;
  totalCount: Scalars['Int']['output'];
  unfilteredTotalCount: Scalars['Int']['output'];
};

export type JobMarkNotInterestedPayload = MutationResult & {
  __typename?: 'JobMarkNotInterestedPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type JobMarkSavedPayload = MutationResult & {
  __typename?: 'JobMarkSavedPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type JobMarkViewedPayload = MutationResult & {
  __typename?: 'JobMarkViewedPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type JobOperations = {
  __typename?: 'JobOperations';
  apply: JobOperationsApply;
  markSaved: Operation;
};

export type JobOperationsApply = {
  __typename?: 'JobOperationsApply';
  errors: Array<Maybe<JobOperationsApplyError>>;
};

export type JobOperationsApplyError = {
  __typename?: 'JobOperationsApplyError';
  code: Scalars['String']['output'];
  message: Scalars['String']['output'];
};

export type JobOperationsApplyErrorsEnum =
  | 'ALREADY_APPLIED'
  | 'AVAILABILITY_REQUEST_ADDRESSED_OR_ADDRESSABLE'
  | 'ID_VERIFICATION_REQUIRED'
  | 'LEGACY_CLIENT'
  | 'NOT_ELIGIBLE'
  | 'NOT_ENOUGH_AVAILABLE_HOURS'
  | 'NO_MATCHING_SKILLS'
  | 'SPECIALIZATION_MISMATCH';

export type JobOps = {
  __typename?: 'JobOps';
  apply: Maybe<JobApplyPayload>;
  clearInterestStatus: Maybe<JobClearInterestStatusPayload>;
  markNotInterested: Maybe<JobMarkNotInterestedPayload>;
  markSaved: Maybe<JobMarkSavedPayload>;
  markViewed: Maybe<JobMarkViewedPayload>;
  startIdVerification: Maybe<TalentStartIdVerificationPayload>;
};


export type JobOpsApplyArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type JobOpsClearInterestStatusArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type JobOpsMarkNotInterestedArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type JobOpsMarkSavedArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type JobOpsMarkViewedArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type JobOpsStartIdVerificationArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};

export type JobPositionAnswer = Node & {
  __typename?: 'JobPositionAnswer';
  answer: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  question: JobPositionQuestion;
};

export type JobPositionAnswerInput = {
  answer: Scalars['String']['input'];
  id: Scalars['String']['input'];
};

export type JobPositionAnswerInterfaceEnum =
  | 'DISPLAY_HOURS_OVERLAP';

export type JobPositionQuestion = Node & {
  __typename?: 'JobPositionQuestion';
  id: Scalars['ID']['output'];
  question: Scalars['String']['output'];
};

export type JobSkillSet = Node & {
  __typename?: 'JobSkillSet';
  id: Scalars['ID']['output'];
  isOptional: Scalars['Boolean']['output'];
  rating: Scalars['Int']['output'];
  theSkill: Skill;
};

export type JobSkillSetEdge = {
  __typename?: 'JobSkillSetEdge';
  node: JobSkillSet;
};

export type JobSkillSetsConnection = {
  __typename?: 'JobSkillSetsConnection';
  edges: Array<Maybe<JobSkillSetEdge>>;
};

export type JobSpecialization = {
  __typename?: 'JobSpecialization';
  title: Scalars['String']['output'];
};

export type JobTimeZone = {
  __typename?: 'JobTimeZone';
  hoursOverlap: Maybe<Scalars['Int']['output']>;
  recommendedHoursOverlap: Scalars['Int']['output'];
  timeZone: TimeZone;
  verbose: Scalars['String']['output'];
  workingHoursAreApproximate: Scalars['Boolean']['output'];
  workingTimeFrom: Scalars['String']['output'];
  workingTimeTo: Scalars['String']['output'];
};

export type JobUnmarkNotInterestedPayload = MutationResult & {
  __typename?: 'JobUnmarkNotInterestedPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type JobWorkType = {
  __typename?: 'JobWorkType';
  slug: Scalars['String']['output'];
};

export type JobWorkTypeSlug =
  | 'MIXED'
  | 'ONSITE'
  | 'RECRUITING'
  | 'REMOTE';

export type KeyValueStrings = {
  __typename?: 'KeyValueStrings';
  key: Scalars['String']['output'];
  value: Scalars['String']['output'];
};

export type Language = Node & {
  __typename?: 'Language';
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
};

export type ManagementExperience = {
  __typename?: 'ManagementExperience';
  reportsRange: Maybe<Scalars['String']['output']>;
};

export type MarkAsPreferredPaymentOptionPayload = MutationResult & {
  __typename?: 'MarkAsPreferredPaymentOptionPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type MarkJobsAsViewedPayload = MutationResult & {
  __typename?: 'MarkJobsAsViewedPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type MarkMarketplaceMigrationNotificationSeenPayload = MutationResult & {
  __typename?: 'MarkMarketplaceMigrationNotificationSeenPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type MarkSeenFirstJobNotificationPayload = MutationResult & {
  __typename?: 'MarkSeenFirstJobNotificationPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type MemorandumBalanceEnum =
  | 'CREDIT'
  | 'DEBIT';

export type MemorandumsConnection = {
  __typename?: 'MemorandumsConnection';
  nodes: Array<Maybe<Scalars['Unknown']['output']>>;
};

export type MinimumCommitmentInapplicableReason =
  | 'HAS_BREAK'
  | 'IS_TRIAL'
  | 'NOT_FULL_LENGTH';

export type MobileAnnouncement = Node & {
  __typename?: 'MobileAnnouncement';
  destination: MobileAnnouncementDestination;
  id: Scalars['ID']['output'];
  style: Scalars['String']['output'];
  summary: Scalars['String']['output'];
};

export type MobileAnnouncementDestination = MobileExternalLink | MobileTopTip;

export type MobileAnnouncementStyleEnum =
  | 'IMPORTANT'
  | 'REGULAR'
  | 'YEAR_IN_REVIEW';

export type MobileAppSetting = {
  __typename?: 'MobileAppSetting';
  hasSeenJobOfferDiclaimer: Scalars['Boolean']['output'];
};

export type MobileAppSubmitFeedbackPayload = MutationResult & {
  __typename?: 'MobileAppSubmitFeedbackPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type MobileAppViewJobOfferDisclaimerPayload = MutationResult & {
  __typename?: 'MobileAppViewJobOfferDisclaimerPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type MobileExternalLink = {
  __typename?: 'MobileExternalLink';
  externalUrl: Maybe<Scalars['String']['output']>;
};

export type MobileFeedbackFeatureEnum =
  | '_UNKNOWN';

export type MobileFeedbackQuestion = MobileFeedbackQuestionEmojiRating;

export type MobileFeedbackQuestionEmojiRating = {
  __typename?: 'MobileFeedbackQuestionEmojiRating';
  label: Maybe<Scalars['String']['output']>;
  options: Maybe<Array<MobileFeedbackQuestionEmojiRatingOption>>;
};

export type MobileFeedbackQuestionEmojiRatingOption = {
  __typename?: 'MobileFeedbackQuestionEmojiRatingOption';
  label: Maybe<Scalars['String']['output']>;
  value: Maybe<Scalars['String']['output']>;
};

export type MobileStoryPageContent = MobileStoryPageContentBadge | MobileStoryPageContentChart | MobileStoryPageContentMetric | MobileStoryPageContentYearsAtToptal;

export type MobileStoryPageContentBadge = {
  __typename?: 'MobileStoryPageContentBadge';
  badges: Maybe<Array<Badge>>;
  subtitle: Maybe<Scalars['String']['output']>;
};

export type MobileStoryPageContentChart = {
  __typename?: 'MobileStoryPageContentChart';
  color: Maybe<Scalars['String']['output']>;
  data: Maybe<Array<MobileStoryPageContentChartDataPoint>>;
  kind: Maybe<Scalars['String']['output']>;
  secondaryColor: Maybe<Scalars['String']['output']>;
  summary: Maybe<Scalars['String']['output']>;
  title: Maybe<Scalars['String']['output']>;
};

export type MobileStoryPageContentChartDataPoint = {
  __typename?: 'MobileStoryPageContentChartDataPoint';
  date: Maybe<Scalars['String']['output']>;
  value: Maybe<Scalars['BigDecimal']['output']>;
};

export type MobileStoryPageContentChartKind =
  | 'BAR'
  | 'LINE';

export type MobileStoryPageContentMetric = {
  __typename?: 'MobileStoryPageContentMetric';
  metric: Maybe<Scalars['String']['output']>;
  metricUnit: Maybe<Scalars['String']['output']>;
  subtitle: Maybe<Scalars['String']['output']>;
};

export type MobileStoryPageContentYearsAtToptal = {
  __typename?: 'MobileStoryPageContentYearsAtToptal';
  yearsAtToptal: Maybe<Scalars['Int']['output']>;
};

export type MobileTopTip = Node & {
  __typename?: 'MobileTopTip';
  id: Scalars['ID']['output'];
  imageUrls: Array<Maybe<Scalars['String']['output']>>;
  textMd: Scalars['String']['output'];
  title: Scalars['String']['output'];
};

export type Money = {
  __typename?: 'Money';
  decimal: Scalars['String']['output'];
};

export type Mutation = {
  __typename?: 'Mutation';
  auth: Maybe<AuthOps>;
  availabilityRequest: Maybe<AvailabilityRequestOps>;
  communityEvent: Maybe<CommunityEventOps>;
  createTopChatUpload: Maybe<MutationResult>;
  engagement: Maybe<EngagementOps>;
  engagementBreak: Maybe<EngagementBreakOps>;
  interview: Maybe<InterviewOps>;
  job: Maybe<JobOps>;
  mobileAppSubmitFeedback: Maybe<MutationResult>;
  mobileAppViewJobOfferDisclaimer: Maybe<MutationResult>;
  notificationSetting: Maybe<NotificationSettingOps>;
  preliminarySearchSetting: Maybe<PreliminarySearchSettingOps>;
  recordDeviceData: Maybe<RecordDeviceDataPayload>;
  recordLocation: Maybe<MutationResult>;
  removeProfileSkillSet: Maybe<RemoveProfileSkillSetPayload>;
  saveProfileSkillSetsAndConnections: Maybe<SaveProfileSkillSetsAndConnectionsPayload>;
  searchFilters: Maybe<SearchFiltersOps>;
  searchSubscription: Maybe<SearchSubscriptionOps>;
  sendReferralEmail: Maybe<SendReferralEmailPayload>;
  submitTimesheet: Maybe<SubmitTimesheetPayload>;
  surveys: Maybe<SurveysOps>;
  switchMobileRole: Maybe<SwitchMobileRolePayload>;
  tokens: Maybe<ApnTokensOps>;
  updateProfileIndustryConnections: Maybe<MutationResult>;
  updateProfileSkillSetPublicities: Maybe<MutationResult>;
  updateTimesheet: Maybe<NotificationSettingUpdateTimesheetReminderPayload>;
  viewerRole: Maybe<ViewerRoleOps>;
};


export type MutationAvailabilityRequestArgs = {
  id: Scalars['ID']['input'];
};


export type MutationCommunityEventArgs = {
  id: Scalars['ID']['input'];
};


export type MutationCreateTopChatUploadArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationEngagementArgs = {
  id: Scalars['ID']['input'];
};


export type MutationEngagementBreakArgs = {
  id: Scalars['ID']['input'];
};


export type MutationInterviewArgs = {
  id: Scalars['ID']['input'];
};


export type MutationJobArgs = {
  id: Scalars['ID']['input'];
};


export type MutationMobileAppSubmitFeedbackArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationMobileAppViewJobOfferDisclaimerArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationRecordDeviceDataArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationRecordLocationArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationRemoveProfileSkillSetArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationSaveProfileSkillSetsAndConnectionsArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationSendReferralEmailArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationSubmitTimesheetArgs = {
  billingCycleId: Scalars['ID']['input'];
};


export type MutationSwitchMobileRoleArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationUpdateProfileIndustryConnectionsArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationUpdateProfileSkillSetPublicitiesArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationUpdateTimesheetArgs = {
  billingCycleId: Scalars['ID']['input'];
  comment: Scalars['String']['input'];
  timesheetRecords: Array<TimesheetRecordsInput>;
};

export type MutationResult = {
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type NotificationCenterNotification = Node & {
  __typename?: 'NotificationCenterNotification';
  action: Maybe<Scalars['Unknown']['output']>;
  entity: NotificationEntity;
  icon: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  kind: Scalars['String']['output'];
  label: Maybe<Scalars['Unknown']['output']>;
  notificationContext: Maybe<TitleSubtitleContext>;
  readAt: Maybe<Scalars['Unknown']['output']>;
  relevantAt: Scalars['DateTime']['output'];
  text: Scalars['String']['output'];
};

export type NotificationCenterNotificationLabelStyleEnum =
  | 'INFORMATIONAL';

export type NotificationConnection = {
  __typename?: 'NotificationConnection';
  ids: Array<Maybe<Scalars['ID']['output']>>;
  nodes: Array<Maybe<NotificationCenterNotification>>;
  totalCount: Scalars['Int']['output'];
};

export type NotificationContext = AvailabilityRequestAnsweredAfterThresholdContext | BadgeContext | InterviewContext | TitleSubtitleContext;

export type NotificationEntity = {
  __typename?: 'NotificationEntity';
  entityId: Scalars['ID']['output'];
  kind: Scalars['String']['output'];
};

export type NotificationEntityKindEnum =
  | 'ALLOCATED_HOURS_CHANGE_REQUEST'
  | 'AVAILABILITY_CHANGE_INTERFACE'
  | 'BADGE'
  | 'BILLING_CYCLE'
  | 'COMMUNITY_EVENT'
  | 'CONSULTATION'
  | 'INTERVIEW_GUIDE'
  | 'LEGACY_SURVEY'
  | 'PENDING_TIMESHEETS_INTERFACE'
  | 'RATE_CHANGE_REQUEST'
  | 'SURVEY'
  | 'TALENT_JOB'
  | 'TALENT_JOB_ACTIVITY_ITEM'
  | 'TALENT_PAYMENT';

export type NotificationIconEnum =
  | 'AWARD'
  | 'CANDIDATE_SENT'
  | 'COMMUNITY'
  | 'INFO'
  | 'INTERVIEW'
  | 'JOB_INFO'
  | 'JOB_REJECTED'
  | 'PAYMENT'
  | 'PAYMENT_DISPUTE'
  | 'REFERRAL'
  | 'SURVEY'
  | 'TALENT_ACCEPTED'
  | 'THUNDER'
  | 'TIMESHEET'
  | 'TRIAL';

export type NotificationSetting = {
  __typename?: 'NotificationSetting';
  jobAlertsMuteWhenUnavailable: Scalars['Boolean']['output'];
  jobAlertsSubscription: Scalars['String']['output'];
  smsForNewAvailabilityRequests: Scalars['Boolean']['output'];
  timesheetReminder: Maybe<Scalars['Unknown']['output']>;
};

export type NotificationSettingOps = {
  __typename?: 'NotificationSettingOps';
  update: Maybe<NotificationSettingUpdatePayload>;
  updateTimesheetReminder: Maybe<NotificationSettingUpdateTimesheetReminderPayload>;
};


export type NotificationSettingOpsUpdateArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type NotificationSettingOpsUpdateTimesheetReminderArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};

export type NotificationSettingUpdatePayload = MutationResult & {
  __typename?: 'NotificationSettingUpdatePayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type NotificationSettingUpdateTimesheetReminderPayload = MutationResult & {
  __typename?: 'NotificationSettingUpdateTimesheetReminderPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type Operation = {
  __typename?: 'Operation';
  callable: Scalars['String']['output'];
};

export type OperationCallableTypes =
  | 'DISABLED'
  | 'ENABLED'
  | 'HIDDEN';

export type PaymentFilter = {
  amount: InputMaybe<Scalars['Unknown']['input']>;
  clientIds: InputMaybe<Scalars['Unknown']['input']>;
  createdAt: InputMaybe<Scalars['Unknown']['input']>;
  createdOn: InputMaybe<Scalars['Unknown']['input']>;
  dueDate: InputMaybe<Scalars['Unknown']['input']>;
  engagementId: InputMaybe<Scalars['Unknown']['input']>;
  kind: InputMaybe<Scalars['Unknown']['input']>;
  status: InputMaybe<Scalars['Unknown']['input']>;
};

export type PaymentKindCategory =
  | 'BONUS_PAYMENT'
  | 'REFERRAL_PAYMENT'
  | 'TALENT_PAYMENT';

export type PaymentStatusFilter = {
  except: InputMaybe<Scalars['Unknown']['input']>;
  only: InputMaybe<Scalars['Unknown']['input']>;
};

export type PaymentsConnection = {
  __typename?: 'PaymentsConnection';
  ids: Array<Maybe<Scalars['ID']['output']>>;
  nodes: Array<Maybe<TalentPayment>>;
  summary: PaymentsSummary;
};

export type PaymentsSummary = {
  __typename?: 'PaymentsSummary';
  totalDisputed: Scalars['String']['output'];
  totalDue: Scalars['String']['output'];
  totalOnHold: Scalars['String']['output'];
  totalOutstanding: Scalars['String']['output'];
  totalOverdue: Scalars['String']['output'];
  totalPaid: Scalars['String']['output'];
};

export type Photo = {
  __typename?: 'Photo';
  large: Scalars['String']['output'];
  small: Scalars['String']['output'];
};

export type PitchInput = {
  certificationPitchItems: InputMaybe<Array<InputMaybe<Scalars['Unknown']['input']>>>;
  educationPitchItems: InputMaybe<Array<InputMaybe<Scalars['Unknown']['input']>>>;
  employmentPitchItems: InputMaybe<Array<InputMaybe<Scalars['Unknown']['input']>>>;
  industryPitchItems: InputMaybe<Array<InputMaybe<Scalars['Unknown']['input']>>>;
  mentorship: InputMaybe<Scalars['Unknown']['input']>;
  portfolioPitchItems: InputMaybe<Array<InputMaybe<Scalars['Unknown']['input']>>>;
  publicationPitchItems: InputMaybe<Array<InputMaybe<Scalars['Unknown']['input']>>>;
  skillPitchItems: InputMaybe<Array<InputMaybe<Scalars['Unknown']['input']>>>;
};

export type PitchItemCertificationInput = {
  certificationId: Scalars['String']['input'];
};

export type PitchItemEducationInput = {
  educationId: Scalars['String']['input'];
};

export type PitchItemEmploymentInput = {
  additionalTextItems: Array<InputMaybe<Scalars['Unknown']['input']>>;
  employmentId: Scalars['String']['input'];
};

export type PitchItemIndustryInput = {
  industryId: Scalars['String']['input'];
};

export type PitchItemInterface = {
  _placeholder: Maybe<Scalars['String']['output']>;
};

export type PitchItemPortfolioInput = {
  portfolioItemId: Scalars['String']['input'];
};

export type PitchItemPublicationInput = {
  publicationId: Scalars['String']['input'];
};

export type PitchItemSkillInput = {
  skillSetId: Scalars['String']['input'];
};

export type PlatformConfiguration = Node & {
  __typename?: 'PlatformConfiguration';
  availabilityRequestRejectReasonsV3: AvailabilityRequestRejectReasonsTypeV3;
  commitmentHoursDictionary: CommitmentHoursDictionary;
  engagementBreakReasons: Array<Maybe<FeedbackReason>>;
  id: Scalars['ID']['output'];
  interviewRejectReasons: Array<Maybe<InterviewRejectReason>>;
  marketplaceHelpRequestReasons: Array<Maybe<KeyValueStrings>>;
  marketplaceMargin: Scalars['String']['output'];
  notInterestedInJobReasons: Array<Maybe<KeyValueStrings>>;
  rateValidationRules: TalentRateValidationRules;
  referralProgramRewards: ReferralProgramRewards;
};

export type PointOfContactKindEnum =
  | 'MATCHER'
  | 'MATCHING_OPERATIONS_COORDINATOR';

export type PointsOfContact = {
  __typename?: 'PointsOfContact';
  current: Recruiter;
  handoff: Maybe<Scalars['Unknown']['output']>;
  kind: Scalars['String']['output'];
};

export type PortfolioItem = Node & {
  __typename?: 'PortfolioItem';
  coverImage: Maybe<Scalars['Unknown']['output']>;
  description: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  industries: IndustryConnection;
  kindEnum: Scalars['String']['output'];
  link: Maybe<Scalars['String']['output']>;
  skills: SkillConnection;
  title: Scalars['String']['output'];
};

export type PortfolioItemConnection = {
  __typename?: 'PortfolioItemConnection';
  nodes: Array<Maybe<PortfolioItem>>;
};

export type PortfolioItemKindEnum =
  | 'ACCOMPLISHMENT'
  | 'BASIC'
  | 'CLASSIC'
  | 'CODE_BASE'
  | 'OTHER_AMAZING_THINGS';

export type PostActivationLifecycleUpdateTopSchedulerPayload = MutationResult & {
  __typename?: 'PostActivationLifecycleUpdateTopSchedulerPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type PreAppliedFiltersKindEnum =
  | 'DEFAULT_VERTICAL_FILTERS'
  | 'SAVED_SEARCH_FILTERS';

export type PreliminarySearchSetting = {
  __typename?: 'PreliminarySearchSetting';
  comment: Maybe<Scalars['Unknown']['output']>;
  disablingReason: Maybe<Scalars['Unknown']['output']>;
  enabled: Scalars['Boolean']['output'];
};

export type PreliminarySearchSettingDisablePayload = MutationResult & {
  __typename?: 'PreliminarySearchSettingDisablePayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type PreliminarySearchSettingEnablePayload = MutationResult & {
  __typename?: 'PreliminarySearchSettingEnablePayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type PreliminarySearchSettingOps = {
  __typename?: 'PreliminarySearchSettingOps';
  enable: Maybe<PreliminarySearchSettingEnablePayload>;
};


export type PreliminarySearchSettingOpsEnableArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};

export type Profile = Node & {
  __typename?: 'Profile';
  certifications: CertificationConnection;
  city: Scalars['String']['output'];
  educations: EducationConnection;
  employments: EmploymentConnection;
  fullName: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  industrySets: ProfileIndustrySetConnection;
  photo: ProfilePhotoType;
  portfolioItems: PortfolioItemConnection;
  skillSets: ProfileSkillSetConnection;
  updatedByTalentAt: Scalars['DateTime']['output'];
};

export type ProfileIndustrySet = {
  __typename?: 'ProfileIndustrySet';
  connections: IndustryConnections;
  id: Scalars['String']['output'];
  industry: Industry;
};

export type ProfileIndustrySetConnection = {
  __typename?: 'ProfileIndustrySetConnection';
  nodes: Array<Maybe<ProfileIndustrySet>>;
};

export type ProfilePhotoType = {
  __typename?: 'ProfilePhotoType';
  large: Scalars['String']['output'];
};

export type ProfileSkillSet = Node & {
  __typename?: 'ProfileSkillSet';
  connections: SkillConnections;
  experience: Maybe<Scalars['Int']['output']>;
  id: Scalars['ID']['output'];
  public: Scalars['Boolean']['output'];
  rating: Scalars['String']['output'];
  skill: Skill;
};

export type ProfileSkillSetConnection = {
  __typename?: 'ProfileSkillSetConnection';
  nodes: Array<Maybe<ProfileSkillSet>>;
};

export type ProfileSkillSetInput = {
  connectionIds: InputMaybe<Scalars['Unknown']['input']>;
  experience: InputMaybe<Scalars['Unknown']['input']>;
  id: InputMaybe<Scalars['Unknown']['input']>;
  name: InputMaybe<Scalars['Unknown']['input']>;
  public: InputMaybe<Scalars['Boolean']['input']>;
  rating: InputMaybe<Scalars['Unknown']['input']>;
};

export type PromoteGigsPayload = MutationResult & {
  __typename?: 'PromoteGigsPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type ProposeEngagementEndDatePayload = MutationResult & {
  __typename?: 'ProposeEngagementEndDatePayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type ProposedEngagementEnd = Node & {
  __typename?: 'ProposedEngagementEnd';
  endDate: Scalars['Date']['output'];
  id: Scalars['ID']['output'];
  status: Scalars['String']['output'];
};

export type ProposedEngagementEndStatusEnum =
  | 'CANCELLED'
  | 'PENDING';

export type PushNotificationsConfiguration = {
  __typename?: 'PushNotificationsConfiguration';
  respectBusinessHours: Scalars['Boolean']['output'];
  windowEnd: Scalars['String']['output'];
  windowStart: Scalars['String']['output'];
};

export type Query = {
  __typename?: 'Query';
  node: Maybe<Node>;
  nodes: Maybe<Array<Maybe<Node>>>;
  platformConfiguration: Maybe<PlatformConfiguration>;
  viewer: Maybe<Viewer>;
};


export type QueryNodeArgs = {
  id: Scalars['ID']['input'];
};


export type QueryNodesArgs = {
  ids: Array<Scalars['ID']['input']>;
};

export type QuestionAdditionalInfo = EngagementAdditionalInfo;

export type QuestionnaireAnswerInput = {
  questionId: InputMaybe<Scalars['Unknown']['input']>;
  value: InputMaybe<Scalars['Unknown']['input']>;
};

export type QuestionnaireInputContentTypeEnum =
  | 'EMAIL'
  | 'NONE'
  | 'PHONE';

export type QuestionnaireInputTypeEnum =
  | 'OPEN_TEXT'
  | 'RADIO_BUTTONS'
  | 'SELECT'
  | 'SELECT_WITH_FILTER'
  | 'SELECT_WITH_OTHER_INPUT'
  | 'SINGLE_LINE_TEXT';

export type QuizCompletePayload = MutationResult & {
  __typename?: 'QuizCompletePayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type RateChangeRequest = Node & {
  __typename?: 'RateChangeRequest';
  createdAt: Scalars['DateTime']['output'];
  desiredRate: Scalars['String']['output'];
  engagement: Maybe<Scalars['Unknown']['output']>;
  id: Scalars['ID']['output'];
  outcomeRate: Scalars['String']['output'];
  requestType: Scalars['String']['output'];
  status: Scalars['String']['output'];
  talentComment: Scalars['String']['output'];
};

export type RateChangeRequestAnswerInput = {
  answer: Scalars['String']['input'];
  comment: InputMaybe<Scalars['Unknown']['input']>;
  questionId: InputMaybe<Scalars['String']['input']>;
};

export type RateChangeRequestQuestionKindEnum =
  | 'RADIO'
  | 'TEXT';

export type RateChangeRequestStatusEnum =
  | 'CLAIMED'
  | 'COMPLETED'
  | 'PENDING';

export type RateChangeRequestTypeEnum =
  | 'CONSULTATION'
  | 'CURRENT_ENGAGEMENT'
  | 'FUTURE_ENGAGEMENTS';

export type Rating =
  | 'COMPETENT'
  | 'EXPERT'
  | 'STRONG';

export type RecordDeviceDataPayload = MutationResult & {
  __typename?: 'RecordDeviceDataPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type RecordDeviceEventPayload = MutationResult & {
  __typename?: 'RecordDeviceEventPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type RecordLocationPayload = MutationResult & {
  __typename?: 'RecordLocationPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type Recruiter = {
  __typename?: 'Recruiter';
  contactFields: ContactFields;
  fullName: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  photo: Maybe<Photo>;
  timeZone: TimeZone;
  vacation: Maybe<Scalars['Unknown']['output']>;
};

export type ReferralBonusRewardFilter =
  | 'ELIGIBLE';

export type ReferralEventStatusEnum =
  | 'ACTIVE'
  | 'APPLIED'
  | 'ENGLISH_SCREENING'
  | 'EVALUATING'
  | 'INACTIVE'
  | 'NOT_ACCEPTED'
  | 'NOT_A_MATCH'
  | 'ON_TRIAL'
  | 'PENDING_TALENT'
  | 'PROFILE_CREATION'
  | 'REWARD_PAID'
  | 'REWARD_PENDING'
  | 'SEEKING_TALENT'
  | 'TECHNICAL_SCREENING_1'
  | 'TECHNICAL_SCREENING_2';

export type ReferralProgramEnum =
  | 'CLIENT'
  | 'TALENT_BONUS'
  | 'TALENT_PARTNER'
  | 'TALENT_STANDARD';

export type ReferralProgramReward = {
  __typename?: 'ReferralProgramReward';
  referral: Maybe<Scalars['Int']['output']>;
  referrer: Scalars['Int']['output'];
};

export type ReferralProgramRewards = {
  __typename?: 'ReferralProgramRewards';
  clientReferral: ReferralProgramReward;
  talentUpsell: ReferralProgramReward;
};

export type ReferralStatRoleTypeEnum =
  | 'CLIENT'
  | 'TALENT'
  | 'TALENT_PARTNER';

export type ReferralStatusEnum =
  | 'ACTIVE'
  | 'APPLIED'
  | 'ENGLISH_SCREENING'
  | 'EVALUATING'
  | 'INACTIVE'
  | 'NOT_ACCEPTED'
  | 'NOT_A_MATCH'
  | 'ON_TRIAL'
  | 'PENDING_TALENT'
  | 'PROFILE_CREATION'
  | 'REWARD_PAID'
  | 'REWARD_PENDING'
  | 'SEEKING_TALENT'
  | 'TECHNICAL_SCREENING_1'
  | 'TECHNICAL_SCREENING_2';

export type ReferralUrl = {
  __typename?: 'ReferralUrl';
  url: Scalars['String']['output'];
};

export type ReferralizeUrlPayload = MutationResult & {
  __typename?: 'ReferralizeUrlPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type RejectGigReachOutPayload = MutationResult & {
  __typename?: 'RejectGigReachOutPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type RemoveCoachingEngagementPayload = MutationResult & {
  __typename?: 'RemoveCoachingEngagementPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type RemoveContentReviewPayload = MutationResult & {
  __typename?: 'RemoveContentReviewPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type RemoveProfileSkillSetPayload = MutationResult & {
  __typename?: 'RemoveProfileSkillSetPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type ReportsRange =
  | 'RANGE_1_5'
  | 'RANGE_6_10'
  | 'RANGE_11_20'
  | 'RANGE_21_50'
  | 'RANGE_50_PLUS';

export type ReviewContentPayload = MutationResult & {
  __typename?: 'ReviewContentPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type RevokeSlackApplicationTokenPayload = MutationResult & {
  __typename?: 'RevokeSlackApplicationTokenPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type RoleStatistics = Node & {
  __typename?: 'RoleStatistics';
  hoursWorked: Scalars['Float']['output'];
  id: Scalars['ID']['output'];
  successfulEngagements: Scalars['Int']['output'];
  totalEarnings: Scalars['Float']['output'];
  yearsInToptal: Scalars['Float']['output'];
};

export type RsvpPayload = MutationResult & {
  __typename?: 'RsvpPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type SaveProfileSkillSetsAndConnectionsPayload = MutationResult & {
  __typename?: 'SaveProfileSkillSetsAndConnectionsPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type SearchFiltersOps = {
  __typename?: 'SearchFiltersOps';
  reset: Maybe<SearchFiltersResetPayload>;
  save: Maybe<SearchFiltersSavePayload>;
};


export type SearchFiltersOpsResetArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type SearchFiltersOpsSaveArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};

export type SearchFiltersResetPayload = MutationResult & {
  __typename?: 'SearchFiltersResetPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type SearchFiltersSavePayload = MutationResult & {
  __typename?: 'SearchFiltersSavePayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type SearchSubscription = {
  __typename?: 'SearchSubscription';
  commitmentsV2: Maybe<Scalars['Unknown']['output']>;
  desiredOverlappingHours: Maybe<Scalars['Unknown']['output']>;
  enterpriseProjects: Scalars['Boolean']['output'];
  estimatedLengths: Maybe<Scalars['Unknown']['output']>;
  excludeKeywords: Maybe<Scalars['Unknown']['output']>;
  excludeNotOverlappingHours: Maybe<Scalars['Unknown']['output']>;
  excludeSkills: Maybe<Scalars['Unknown']['output']>;
  excludeUnspecifiedBudget: Maybe<Scalars['Unknown']['output']>;
  hourlyRate: HourlyRate;
  keywords: Maybe<Scalars['Unknown']['output']>;
  logic: Maybe<Scalars['Unknown']['output']>;
  referralBonusReward: Maybe<Scalars['Unknown']['output']>;
  skills: Maybe<Scalars['Unknown']['output']>;
  specializationSlugs: Maybe<Scalars['Unknown']['output']>;
  toptalProjects: Maybe<Scalars['Unknown']['output']>;
  workTypesV2: Maybe<Scalars['Unknown']['output']>;
};

export type SearchSubscriptionOps = {
  __typename?: 'SearchSubscriptionOps';
  start: Maybe<SearchSubscriptionStartPayload>;
  terminate: Maybe<SearchSubscriptionTerminatePayload>;
};


export type SearchSubscriptionOpsStartArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type SearchSubscriptionOpsTerminateArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};

export type SearchSubscriptionStartPayload = MutationResult & {
  __typename?: 'SearchSubscriptionStartPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type SearchSubscriptionTerminatePayload = MutationResult & {
  __typename?: 'SearchSubscriptionTerminatePayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type SendReferralEmailPayload = MutationResult & {
  __typename?: 'SendReferralEmailPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type SendResetPasswordEmailPayload = MutationResult & {
  __typename?: 'SendResetPasswordEmailPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type SetUnavailablePayload = MutationResult & {
  __typename?: 'SetUnavailablePayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type ShortenUrlPayload = MutationResult & {
  __typename?: 'ShortenUrlPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type SignInPayload = MutationResult & {
  __typename?: 'SignInPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type Skill = Node & {
  __typename?: 'Skill';
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
};

export type SkillConnection = {
  __typename?: 'SkillConnection';
  nodes: Array<Maybe<Skill>>;
  totalCount: Scalars['Int']['output'];
};

export type SkillConnections = {
  __typename?: 'SkillConnections';
  nodes: Array<Maybe<Employment>>;
};

export type SpecializationApplyPayload = MutationResult & {
  __typename?: 'SpecializationApplyPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type StatusColor =
  | 'NEGATIVE'
  | 'NEUTRAL'
  | 'POSITIVE'
  | 'WARNING';

export type StringFilter = {
  except: InputMaybe<Scalars['Unknown']['input']>;
  only: InputMaybe<Scalars['Unknown']['input']>;
};

export type SubmitGigFeedbackPayload = MutationResult & {
  __typename?: 'SubmitGigFeedbackPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type SubmitHireMePagePayload = MutationResult & {
  __typename?: 'SubmitHireMePagePayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type SubmitTimesheetPayload = MutationResult & {
  __typename?: 'SubmitTimesheetPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type Survey = Node & {
  __typename?: 'Survey';
  alreadyAnswered: Scalars['Boolean']['output'];
  createdAt: Scalars['DateTime']['output'];
  id: Scalars['ID']['output'];
  isMandatory: Scalars['Boolean']['output'];
  job: Maybe<Scalars['Unknown']['output']>;
  kind: Scalars['String']['output'];
  questions: Array<Maybe<SurveyQuestion>>;
  title: Scalars['String']['output'];
};

export type SurveyAddFeedbackPayload = MutationResult & {
  __typename?: 'SurveyAddFeedbackPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type SurveyAnswerInput = {
  id: InputMaybe<Scalars['Unknown']['input']>;
  questionId: InputMaybe<Scalars['Unknown']['input']>;
  value: InputMaybe<Scalars['Unknown']['input']>;
};

export type SurveyAnswerOption = Node & {
  __typename?: 'SurveyAnswerOption';
  id: Scalars['ID']['output'];
  label: Maybe<Scalars['String']['output']>;
  note: Maybe<Scalars['Unknown']['output']>;
  value: Scalars['String']['output'];
};

export type SurveyDismissPayload = MutationResult & {
  __typename?: 'SurveyDismissPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type SurveyInputTypeEnum =
  | 'CHECKBOX'
  | 'OPEN_TEXT'
  | 'PROPOSED_ENGAGEMENT_END_DATE'
  | 'RADIO_BUTTONS'
  | 'RATING'
  | 'SLIDER';

export type SurveyKindEnum =
  | 'ENGAGEMENT_ENDED'
  | 'ENGAGEMENT_TESTIMONIAL'
  | 'INTERVIEW_ENDED'
  | 'MID_ENGAGEMENT'
  | 'MOBILE_APP_SATISFACTION'
  | 'NEWCOMER'
  | 'NPS'
  | 'OPPORTUNITY_CHECK';

export type SurveyQuestion = Node & {
  __typename?: 'SurveyQuestion';
  answers: Array<Maybe<SurveyAnswerOption>>;
  id: Scalars['ID']['output'];
  inputType: Scalars['String']['output'];
  isMandatory: Scalars['Boolean']['output'];
  label: Scalars['String']['output'];
  note: Maybe<Scalars['Unknown']['output']>;
};

export type SurveySubmitPayload = MutationResult & {
  __typename?: 'SurveySubmitPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type SurveysOps = {
  __typename?: 'SurveysOps';
  addFeedback: Maybe<SurveyAddFeedbackPayload>;
  dismiss: Maybe<SurveyDismissPayload>;
  submit: Maybe<MobileAppSubmitFeedbackPayload>;
};


export type SurveysOpsAddFeedbackArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type SurveysOpsDismissArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type SurveysOpsSubmitArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};

export type SwitchMobileRolePayload = MutationResult & {
  __typename?: 'SwitchMobileRolePayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type SwitchRolePayload = MutationResult & {
  __typename?: 'SwitchRolePayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type TalentAccessibleRoleRoleSelectorVisibility =
  | 'HIDDEN'
  | 'VISIBLE';

export type TalentEngagement = Node & {
  __typename?: 'TalentEngagement';
  activeBreak: Maybe<Scalars['Unknown']['output']>;
  billCycle: EngagementBillCycle;
  billingCycles: BillingCycleConnection;
  commitment: CommitmentType;
  currentAgreement: EngagementAgreement;
  currentBillingCycle: BillingCycle;
  earning: TalentEngagementEarning;
  eligibleForPayment: Scalars['Boolean']['output'];
  eligibleToViewTimeOffs: Scalars['Boolean']['output'];
  eligibleToViewTimesheets: Scalars['Boolean']['output'];
  endDate: Maybe<Scalars['Unknown']['output']>;
  engagementBreaks: Array<Maybe<Scalars['Unknown']['output']>>;
  expectedHours: Scalars['Int']['output'];
  id: Scalars['ID']['output'];
  job: TalentJob;
  minimumHoursPerBillingCycle: Maybe<Scalars['Unknown']['output']>;
  operations: EngagementOperations;
  payments: PaymentsConnection;
  proposedEnd: ProposedEngagementEnd;
  startDate: Scalars['Date']['output'];
  trial: Maybe<Scalars['Unknown']['output']>;
};

export type TalentEngagementDeliveryModel = Node & {
  __typename?: 'TalentEngagementDeliveryModel';
  id: Scalars['ID']['output'];
  identifier: Scalars['String']['output'];
};

export type TalentEngagementEarning = {
  __typename?: 'TalentEngagementEarning';
  paid: Money;
};

export type TalentInterviewMethodTypeEnum =
  | 'BLUEJEANS'
  | 'CUSTOM_WEB_CONFERENCE'
  | 'GOOGLE_HANGOUTS'
  | 'PHONE'
  | 'SKYPE'
  | 'ZOOM';

export type TalentJob = {
  __typename?: 'TalentJob';
  allowedCountries: Array<Maybe<Scalars['Unknown']['output']>>;
  client: Client;
  commitment: CommitmentType;
  contacts: Array<Maybe<CompanyRepresentative>>;
  descriptionMd: Scalars['String']['output'];
  engagementDeliveryModel: TalentEngagementDeliveryModel;
  estimatedLength: JobEstimatedLength;
  expectedHours: Scalars['Int']['output'];
  freshUntil: Scalars['DateTime']['output'];
  hiringStatus: JobHiringStatus;
  id: Scalars['ID']['output'];
  industriesV2: JobIndustriesConnection;
  isCoaching: Scalars['Boolean']['output'];
  isToptalProject: Scalars['Boolean']['output'];
  jobSkillSetsV2: JobSkillSetsConnection;
  jobTimeZone: JobTimeZone;
  languages: Array<Maybe<Language>>;
  maxRate: Maybe<Scalars['Unknown']['output']>;
  minimumHoursPerBillingCycle: Maybe<Scalars['Int']['output']>;
  notInterested: Scalars['Boolean']['output'];
  oldAfter: Scalars['DateTime']['output'];
  onsiteLocations: Array<Maybe<Scalars['Unknown']['output']>>;
  onsitePreference: Maybe<Scalars['Unknown']['output']>;
  operations: JobOperations;
  pointsOfContact: PointsOfContact;
  positionsCount: Scalars['Int']['output'];
  postedWhen: Scalars['DateTime']['output'];
  saved: Scalars['Boolean']['output'];
  semiMonthlyBilling: Scalars['Boolean']['output'];
  specialization: JobSpecialization;
  startDate: Scalars['Date']['output'];
  title: Scalars['String']['output'];
  url: Scalars['String']['output'];
  viewed: Scalars['Boolean']['output'];
  workType: JobWorkType;
};

export type TalentJobActivityItem = Node & {
  __typename?: 'TalentJobActivityItem';
  availabilityRequest: Maybe<AvailabilityRequest>;
  engagement: Maybe<TalentEngagement>;
  id: Scalars['ID']['output'];
  interview: Maybe<Scalars['Unknown']['output']>;
  job: TalentJob;
  jobApplication: Maybe<JobApplication>;
  lastUpdatedAt: Scalars['DateTime']['output'];
  mostRelevantApplication: Maybe<AvailabilityRequest>;
  statusColor: Scalars['String']['output'];
  statusGroupV2: JobActivityItemStatusGroup;
  statusV2: JobActivityItemStatus;
};

export type TalentJobRateInsight = TalentJobRateInsightCompetitive | TalentJobRateInsightUncompetitive;

export type TalentJobRateInsightCompetitive = {
  __typename?: 'TalentJobRateInsightCompetitive';
  estimatedRevenue: Maybe<Scalars['BigDecimal']['output']>;
  estimatedRevenueExplanation: Maybe<Scalars['String']['output']>;
  longTermDisclaimer: Maybe<Scalars['String']['output']>;
};

export type TalentJobRateInsightUncompetitive = {
  __typename?: 'TalentJobRateInsightUncompetitive';
  estimatedRevenue: Maybe<Scalars['BigDecimal']['output']>;
  estimatedRevenueExplanation: Maybe<Scalars['String']['output']>;
  recentApplicationRate: Maybe<Scalars['BigDecimal']['output']>;
  recommendedRate: Maybe<Scalars['BigDecimal']['output']>;
};

export type TalentNotificationMarkAsReadPayload = MutationResult & {
  __typename?: 'TalentNotificationMarkAsReadPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type TalentPayment = Node & {
  __typename?: 'TalentPayment';
  amount: Scalars['String']['output'];
  billingCycle: BillingCycle;
  correctionAmount: Scalars['String']['output'];
  createdAt: Scalars['DateTime']['output'];
  description: Scalars['String']['output'];
  downloadPdfUrl: Scalars['String']['output'];
  dueDate: Scalars['Date']['output'];
  id: Scalars['ID']['output'];
  job: TalentJob;
  kindCategory: Scalars['String']['output'];
  memorandums: MemorandumsConnection;
  number: Scalars['Int']['output'];
  paidAt: Maybe<Scalars['DateTime']['output']>;
  paymentGroupId: Maybe<Scalars['Int']['output']>;
  status: Scalars['String']['output'];
  updatedAt: Scalars['DateTime']['output'];
};

export type TalentPaymentStatus =
  | 'DISPUTED'
  | 'DUE'
  | 'ON_HOLD'
  | 'OUTSTANDING'
  | 'OVERDUE'
  | 'PAID';

export type TalentPermissions = {
  __typename?: 'TalentPermissions';
  canApplyToJobs: Scalars['Boolean']['output'];
  canHaveReferrals: Scalars['Boolean']['output'];
  canViewCommunity: Scalars['Boolean']['output'];
  canViewEligibleJobs: Scalars['Boolean']['output'];
  canViewFaq: Scalars['Boolean']['output'];
  canViewJobsOnClientReview: Scalars['Boolean']['output'];
  canViewJobsOnMatcherReview: Scalars['Boolean']['output'];
  canViewPayments: Scalars['Boolean']['output'];
  canViewRateInsights: Scalars['Boolean']['output'];
  canViewRecognitionBadges: Scalars['Boolean']['output'];
  canViewRecommendedJobs: Scalars['Boolean']['output'];
  canViewSmsNotificationSettings: Scalars['Boolean']['output'];
};

export type TalentPortalSettingUpdatePayload = MutationResult & {
  __typename?: 'TalentPortalSettingUpdatePayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type TalentRate = {
  __typename?: 'TalentRate';
  hourly: Scalars['String']['output'];
};

export type TalentRateInsight = {
  __typename?: 'TalentRateInsight';
  hourly: TalentRateInsightForCommitment;
};

export type TalentRateInsightForCommitment = {
  __typename?: 'TalentRateInsightForCommitment';
  currentRateCompetitive: Scalars['Boolean']['output'];
  recentApplicationRate: Scalars['String']['output'];
  recommendedRate: Scalars['String']['output'];
};

export type TalentRateValidationRule = {
  __typename?: 'TalentRateValidationRule';
  minRate: Scalars['String']['output'];
  rateStep: Scalars['Int']['output'];
};

export type TalentRateValidationRules = {
  __typename?: 'TalentRateValidationRules';
  hourly: TalentRateValidationRule;
};

export type TalentSpecialization = {
  __typename?: 'TalentSpecialization';
  deliveryModel: TalentEngagementDeliveryModel;
  id: Scalars['ID']['output'];
  slug: Scalars['String']['output'];
  title: Scalars['String']['output'];
};

export type TalentStartIdVerificationPayload = MutationResult & {
  __typename?: 'TalentStartIdVerificationPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type TalentVertical = {
  __typename?: 'TalentVertical';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
};

export type TeamSize = {
  __typename?: 'TeamSize';
  value: Maybe<Scalars['String']['output']>;
};

export type TermsOfServiceAcceptPayload = MutationResult & {
  __typename?: 'TermsOfServiceAcceptPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type TermsOfServiceReviewPayload = MutationResult & {
  __typename?: 'TermsOfServiceReviewPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type TimeFilter = {
  gt: InputMaybe<Scalars['Unknown']['input']>;
  gteq: InputMaybe<Scalars['Unknown']['input']>;
  lt: InputMaybe<Scalars['Unknown']['input']>;
  lteq: InputMaybe<Scalars['Unknown']['input']>;
};

export type TimeZone = {
  __typename?: 'TimeZone';
  location: Scalars['String']['output'];
  value: Scalars['String']['output'];
};

export type TimesheetRecordsInput = {
  date: Scalars['Date']['input'];
  duration: InputMaybe<Scalars['BigDecimal']['input']>;
  note: InputMaybe<Scalars['Unknown']['input']>;
};

export type TitleSubtitleContext = {
  __typename?: 'TitleSubtitleContext';
  subtitle: Scalars['String']['output'];
  title: Scalars['String']['output'];
};

export type TopChatConversationService = TopChatConversationSlackService;

export type TopChatConversationSlackService = {
  __typename?: 'TopChatConversationSlackService';
  channelId: Maybe<Scalars['String']['output']>;
  id: Maybe<Scalars['ID']['output']>;
};

export type TopChatConversationStatus =
  | 'ACTIVE'
  | 'ARCHIVED';

export type TopChatConversationStatusFilter = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateMeetingHoursPayload = MutationResult & {
  __typename?: 'UpdateMeetingHoursPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type UpdatePaymentOptionPayload = MutationResult & {
  __typename?: 'UpdatePaymentOptionPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type UpdateProfileIndustryConnectionsPayload = MutationResult & {
  __typename?: 'UpdateProfileIndustryConnectionsPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type UpdateProfileSkillSetPublicitiesPayload = MutationResult & {
  __typename?: 'UpdateProfileSkillSetPublicitiesPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type UpdateTalentConsultingRatePayload = MutationResult & {
  __typename?: 'UpdateTalentConsultingRatePayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type UpdateTimesheetPayload = MutationResult & {
  __typename?: 'UpdateTimesheetPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type UpdateWorkingHoursPayload = MutationResult & {
  __typename?: 'UpdateWorkingHoursPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type UploadTimesheetPayload = MutationResult & {
  __typename?: 'UploadTimesheetPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type UserError = {
  code: Maybe<Scalars['String']['output']>;
  key: Maybe<Scalars['String']['output']>;
  message: Maybe<Scalars['String']['output']>;
};

export type VerticalGlobalMarketConditionEnum =
  | 'MODERATE'
  | 'POOR';

export type VerticalMarketConditionEnum =
  | 'MODERATE'
  | 'POOR'
  | 'STRONG';

export type Viewer = Node & {
  __typename?: 'Viewer';
  accessibleRoles: Array<Maybe<Scalars['Unknown']['output']>>;
  availabilityRequestMetrics: AvailabilityRequestMetrics;
  badgeGroups: BadgeGroupConnection;
  billingCycles: BillingCycleConnection;
  currentMobileAnnouncement: MobileAnnouncement;
  eligibleJobs: JobList;
  hasReferralBonusRewardJobs: Scalars['Boolean']['output'];
  id: Scalars['ID']['output'];
  interviews: Array<Maybe<Scalars['Unknown']['output']>>;
  jobActivityItem: TalentJobActivityItem;
  jobActivityList: JobActivityList;
  lastRateChangeRequest: RateChangeRequest;
  mobileAppSetting: MobileAppSetting;
  notificationCenter: Center;
  notificationSetting: NotificationSetting;
  payments: PaymentsConnection;
  pendingAvailabilityRequests: Array<Maybe<AvailabilityRequest>>;
  pendingSurveys: Array<Maybe<Survey>>;
  preliminarySearchSetting: PreliminarySearchSetting;
  recommendedJobs: Array<Maybe<Scalars['Unknown']['output']>>;
  referralUrl: ReferralUrl;
  savedJobsCount: JobList;
  searchSubscription: SearchSubscription;
  talentStatistics: RoleStatistics;
  viewerRole: ViewerRole;
};

export type ViewerRole = {
  __typename?: 'ViewerRole';
  allocatedHours: Scalars['Int']['output'];
  availableShiftRangeFrom: Scalars['String']['output'];
  availableShiftRangeTo: Scalars['String']['output'];
  email: Scalars['String']['output'];
  firstName: Scalars['String']['output'];
  fullName: Scalars['String']['output'];
  hiredHours: Scalars['Int']['output'];
  lastAllocatedHoursChangeRequest: AllocatedHoursChangeRequest;
  operations: ViewerRoleOperations;
  permissions: TalentPermissions;
  phoneNumber: Scalars['String']['output'];
  photo: Photo;
  profile: Profile;
  publicResumeUrl: Scalars['String']['output'];
  pushNotificationsConfiguration: PushNotificationsConfiguration;
  rateInsight: TalentRateInsight;
  rates: TalentRate;
  roleId: Scalars['Int']['output'];
  specializations: Array<Maybe<TalentSpecialization>>;
  timeZone: TimeZone;
  vertical: TalentVertical;
};

export type ViewerRoleOperations = {
  __typename?: 'ViewerRoleOperations';
  createTalentSignal: ViewerRoleOperationsCreateTalentSignal;
  startSearchSubscription: Operation;
};

export type ViewerRoleOperationsCreateTalentSignal = {
  __typename?: 'ViewerRoleOperationsCreateTalentSignal';
  callable: Scalars['String']['output'];
};

export type ViewerRoleOps = {
  __typename?: 'ViewerRoleOps';
  createBecomeClient: Maybe<CreateBecomeClientPayload>;
  createDirectReferral: Maybe<CreateDirectReferralPayload>;
  createMarketplaceHelpRequest: Maybe<CreateMarketplaceHelpRequestPayload>;
  createRateChangeRequest: Maybe<CreateRateChangeRequestPayload>;
  createTalentSignal: Maybe<CreateTalentSignalPayload>;
  setUnavailable: Maybe<SetUnavailablePayload>;
  update: Maybe<ViewerRoleUpdatePayload>;
};


export type ViewerRoleOpsCreateBecomeClientArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type ViewerRoleOpsCreateDirectReferralArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type ViewerRoleOpsCreateMarketplaceHelpRequestArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type ViewerRoleOpsCreateRateChangeRequestArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type ViewerRoleOpsCreateTalentSignalArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type ViewerRoleOpsSetUnavailableArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type ViewerRoleOpsUpdateArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};

export type ViewerRoleResetPasswordPayload = MutationResult & {
  __typename?: 'ViewerRoleResetPasswordPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type ViewerRoleUpdateAccountSettingsPayload = MutationResult & {
  __typename?: 'ViewerRoleUpdateAccountSettingsPayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type ViewerRoleUpdatePayload = MutationResult & {
  __typename?: 'ViewerRoleUpdatePayload';
  errors: Maybe<Array<Maybe<UserError>>>;
  success: Scalars['Boolean']['output'];
};

export type ProfileShowQueryVariables = Exact<{ [key: string]: never; }>;


export type ProfileShowQuery = { viewer: { __typename: 'Viewer', id: string, viewerRole: { __typename: 'ViewerRole', email: string, firstName: string, fullName: string, phoneNumber: string, allocatedHours: number, hiredHours: number, photo: { __typename: 'Photo', large: string, small: string }, profile: { __typename: 'Profile', id: string, fullName: string, city: string, photo: { __typename: 'ProfilePhotoType', large: string }, skillSets: { __typename: 'ProfileSkillSetConnection', nodes: Array<{ __typename: 'ProfileSkillSet', id: string, experience: number | null, rating: string, public: boolean, skill: { __typename: 'Skill', id: string, name: string } } | null> } } } } | null };

export type ViewerQueryVariables = Exact<{ [key: string]: never; }>;


export type ViewerQuery = { viewer: { __typename: 'Viewer', id: string, preliminarySearchSetting: { __typename: 'PreliminarySearchSetting', enabled: boolean, disablingReason: unknown, comment: unknown }, viewerRole: { __typename: 'ViewerRole', allocatedHours: number, hiredHours: number, lastAllocatedHoursChangeRequest: { __typename: 'AllocatedHoursChangeRequest', id: string, allocatedHours: number, rejectReason: unknown, comment: string, futureAvailableHours: unknown, returnInDate: unknown, useReturnAvailability: boolean, reviewedManually: boolean, statusV2: { __typename: 'AllocatedHoursChangeRequestStatus', value: string } } } } | null };

export type LastAllocatedHoursChangeRequestDataFragment = { __typename: 'AllocatedHoursChangeRequest', id: string, allocatedHours: number, rejectReason: unknown, comment: string, futureAvailableHours: unknown, returnInDate: unknown, useReturnAvailability: boolean, reviewedManually: boolean, statusV2: { __typename: 'AllocatedHoursChangeRequestStatus', value: string } };

export type AvailabilityDataFragment = { __typename: 'Viewer', id: string, preliminarySearchSetting: { __typename: 'PreliminarySearchSetting', enabled: boolean, disablingReason: unknown, comment: unknown }, viewerRole: { __typename: 'ViewerRole', allocatedHours: number, hiredHours: number, lastAllocatedHoursChangeRequest: { __typename: 'AllocatedHoursChangeRequest', id: string, allocatedHours: number, rejectReason: unknown, comment: string, futureAvailableHours: unknown, returnInDate: unknown, useReturnAvailability: boolean, reviewedManually: boolean, statusV2: { __typename: 'AllocatedHoursChangeRequestStatus', value: string } } } };
