// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Oleksii PELYKH
//
// AUTO-GENERATED by `pnpm codegen` from
// `../research/graphql/talent_profile/schema.graphql` and operations under
// `../research/graphql/talent_profile/operations/`.
// Do not edit by hand; re-run codegen instead.

/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  SettingName: { input: unknown; output: unknown; }
  Unknown: { input: unknown; output: unknown; }
  Upload: { input: unknown; output: unknown; }
};

export type AcceptAgreementPayload = {
  __typename?: 'AcceptAgreementPayload';
  activation: Maybe<Activation>;
  errors: Maybe<Scalars['Unknown']['output']>;
  notice: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type AcceptFreelanceTalentAgreementInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type AcceptFreelanceTalentAgreementPayload = {
  __typename?: 'AcceptFreelanceTalentAgreementPayload';
  contract: Maybe<Contract>;
  errors: Maybe<Scalars['Unknown']['output']>;
  notice: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type AcceptTrainingPayload = {
  __typename?: 'AcceptTrainingPayload';
  activation: Maybe<Activation>;
  errors: Maybe<Scalars['Unknown']['output']>;
  notice: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type Activation = {
  __typename?: 'Activation';
  steps: Maybe<Scalars['Unknown']['output']>;
};

export type AddProfileSkillSetConnectionPayload = {
  __typename?: 'AddProfileSkillSetConnectionPayload';
  profile: Maybe<Scalars['Unknown']['output']>;
  skillSet: Maybe<Scalars['Unknown']['output']>;
};

export type AddProfileSkillSetInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type AddProfileSkillSetPayload = {
  __typename?: 'AddProfileSkillSetPayload';
  profile: Maybe<Profile>;
  skillSet: Maybe<ProfileSkillSet>;
};

export type AdvancedProfileRecommendation = {
  __typename?: 'AdvancedProfileRecommendation';
  isCustomRequirementsCompleted: Maybe<Scalars['Unknown']['output']>;
  isTravelInformationCompleted: Maybe<Scalars['Unknown']['output']>;
};

export type ApproveItemReviewInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type ApproveItemReviewPayload = {
  __typename?: 'ApproveItemReviewPayload';
  sectionReviews: Maybe<SectionReview>;
};

export type ApproveSectionReviewInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type ApproveSectionReviewPayload = {
  __typename?: 'ApproveSectionReviewPayload';
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  sectionReviews: Maybe<SectionReview>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type CancelResumeUploadInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type CancelResumeUploadPayload = {
  __typename?: 'CancelResumeUploadPayload';
  errors: Maybe<UserError>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type Certification = {
  __typename?: 'Certification';
  certificate: Maybe<Scalars['Unknown']['output']>;
  highlight: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  institution: Maybe<Scalars['Unknown']['output']>;
  link: Maybe<Scalars['Unknown']['output']>;
  number: Maybe<Scalars['Unknown']['output']>;
  skills: Maybe<Scalars['Unknown']['output']>;
  status: Maybe<Scalars['Unknown']['output']>;
  validFromMonth: Maybe<Scalars['Unknown']['output']>;
  validFromYear: Maybe<Scalars['Unknown']['output']>;
  validToMonth: Maybe<Scalars['Unknown']['output']>;
  validToYear: Maybe<Scalars['Unknown']['output']>;
};

export type ChangePortfolioItemPositionInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type ChangePortfolioItemPositionPayload = {
  __typename?: 'ChangePortfolioItemPositionPayload';
  profile: Maybe<Profile>;
};

export type Contract = {
  __typename?: 'Contract';
  billingType: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  isActive: Maybe<Scalars['Unknown']['output']>;
  kind: Maybe<Scalars['Unknown']['output']>;
  provider: Maybe<Scalars['Unknown']['output']>;
  sentAt: Maybe<Scalars['Unknown']['output']>;
  signedAt: Maybe<Scalars['Unknown']['output']>;
  status: Maybe<Scalars['Unknown']['output']>;
  title: Maybe<Scalars['Unknown']['output']>;
  verificationDeadline: Maybe<Scalars['Unknown']['output']>;
};

export type CreateCertificationInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type CreateCertificationPayload = {
  __typename?: 'CreateCertificationPayload';
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type CreateEducationInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type CreateEducationPayload = {
  __typename?: 'CreateEducationPayload';
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type CreateEmploymentInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type CreateEmploymentPayload = {
  __typename?: 'CreateEmploymentPayload';
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type CreateEngagementTestimonialInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type CreateEngagementTestimonialPayload = {
  __typename?: 'CreateEngagementTestimonialPayload';
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type CreateIndustryProfileInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type CreateIndustryProfilePayload = {
  __typename?: 'CreateIndustryProfilePayload';
  errors: Maybe<UserError>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type CreatePayoneerPaymentOptionInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type CreatePayoneerPaymentOptionPayload = {
  __typename?: 'CreatePayoneerPaymentOptionPayload';
  errors: Maybe<UserError>;
  success: Maybe<Scalars['Unknown']['output']>;
  talent: Maybe<Talent>;
};

export type CreatePortfolioItemInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type CreatePortfolioItemPayload = {
  __typename?: 'CreatePortfolioItemPayload';
  profile: Maybe<Profile>;
};

export type CreateToptalPaymentAccountInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type CreateToptalPaymentAccountPayload = {
  __typename?: 'CreateToptalPaymentAccountPayload';
  errors: Maybe<UserError>;
  success: Maybe<Scalars['Unknown']['output']>;
  talent: Maybe<Talent>;
};

export type CreateTravelVisaInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type CreateTravelVisaPayload = {
  __typename?: 'CreateTravelVisaPayload';
  errors: Maybe<UserError>;
  profile: Maybe<Scalars['Unknown']['output']>;
};

export type CustomRequirements = {
  __typename?: 'CustomRequirements';
  backgroundCheck: Maybe<Scalars['Unknown']['output']>;
  drugTest: Maybe<Scalars['Unknown']['output']>;
  timeTrackingTools: Maybe<Scalars['Unknown']['output']>;
};

export type DismissTestimonialNotificationInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type DismissTestimonialNotificationPayload = {
  __typename?: 'DismissTestimonialNotificationPayload';
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type Education = {
  __typename?: 'Education';
  degree: Maybe<Scalars['Unknown']['output']>;
  fieldOfStudy: Maybe<Scalars['Unknown']['output']>;
  highlight: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  institution: Maybe<Scalars['Unknown']['output']>;
  location: Maybe<Scalars['Unknown']['output']>;
  skills: Maybe<Scalars['Unknown']['output']>;
  title: Maybe<Scalars['Unknown']['output']>;
  yearFrom: Maybe<Scalars['Unknown']['output']>;
  yearTo: Maybe<Scalars['Unknown']['output']>;
};

export type Employer = {
  __typename?: 'Employer';
  city: Maybe<Scalars['Unknown']['output']>;
  country: Maybe<Scalars['Unknown']['output']>;
  employeeCount: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  industries: Maybe<Scalars['Unknown']['output']>;
  lastSyncedAt: Maybe<Scalars['Unknown']['output']>;
  logoUrl: Maybe<Scalars['Unknown']['output']>;
  name: Maybe<Scalars['Unknown']['output']>;
  otherNames: Maybe<Scalars['Unknown']['output']>;
  otherUrls: Maybe<Scalars['Unknown']['output']>;
  revenue: Maybe<Scalars['Unknown']['output']>;
  website: Maybe<Scalars['Unknown']['output']>;
};

export type Employment = {
  __typename?: 'Employment';
  company: Maybe<Scalars['Unknown']['output']>;
  companyWebsite: Maybe<Scalars['Unknown']['output']>;
  employer: Maybe<Employer>;
  endDate: Maybe<Scalars['Unknown']['output']>;
  engagement: Maybe<Scalars['Unknown']['output']>;
  experienceItems: Maybe<Scalars['Unknown']['output']>;
  highlight: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  industries: Maybe<Scalars['Unknown']['output']>;
  isEnterpriseExperience: Maybe<Scalars['Unknown']['output']>;
  managementExperience: Maybe<Scalars['Unknown']['output']>;
  noWebsite: Maybe<Scalars['Unknown']['output']>;
  position: Maybe<Scalars['Unknown']['output']>;
  primaryGeography: Maybe<Scalars['Unknown']['output']>;
  publicationPermit: Maybe<Scalars['Unknown']['output']>;
  reportingTo: Maybe<Scalars['Unknown']['output']>;
  showViaToptal: Maybe<Scalars['Unknown']['output']>;
  skills: Maybe<Scalars['Unknown']['output']>;
  startDate: Maybe<Scalars['Unknown']['output']>;
  toptalRelated: Maybe<Scalars['Unknown']['output']>;
};

export type EmploymentsCountRecommendation = {
  __typename?: 'EmploymentsCountRecommendation';
  minimumCount: Maybe<Scalars['Unknown']['output']>;
  type: Maybe<Scalars['Unknown']['output']>;
};

export type EmploymentsMissingDataRecommendation = {
  __typename?: 'EmploymentsMissingDataRecommendation';
  employments: Maybe<Scalars['Unknown']['output']>;
};

export type HighlightCertificationPayload = {
  __typename?: 'HighlightCertificationPayload';
  certification: Maybe<Scalars['Unknown']['output']>;
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type HighlightEducationPayload = {
  __typename?: 'HighlightEducationPayload';
  education: Maybe<Scalars['Unknown']['output']>;
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type HighlightEmploymentPayload = {
  __typename?: 'HighlightEmploymentPayload';
  employment: Maybe<Scalars['Unknown']['output']>;
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type HighlightPortfolioItemPayload = {
  __typename?: 'HighlightPortfolioItemPayload';
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  portfolioItem: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type Industry = {
  __typename?: 'Industry';
  id: Maybe<Scalars['Unknown']['output']>;
  name: Maybe<Scalars['Unknown']['output']>;
};

export type IndustryProfile = {
  __typename?: 'IndustryProfile';
  about: Maybe<Scalars['Unknown']['output']>;
  certifications: Maybe<Scalars['Unknown']['output']>;
  domainArea: Maybe<Scalars['Unknown']['output']>;
  educations: Maybe<Scalars['Unknown']['output']>;
  employments: Maybe<Scalars['Unknown']['output']>;
  highlights: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  portfolioItems: Maybe<Scalars['Unknown']['output']>;
  title: Maybe<Scalars['Unknown']['output']>;
};

export type LogOutInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type LogOutPayload = {
  __typename?: 'LogOutPayload';
  errors: Maybe<Scalars['Unknown']['output']>;
  notice: Maybe<Scalars['Unknown']['output']>;
  returnTo: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type Mutation = {
  __typename?: 'Mutation';
  acceptAgreement: Maybe<AcceptAgreementPayload>;
  acceptFreelanceTalentAgreement: Maybe<AcceptFreelanceTalentAgreementPayload>;
  acceptTraining: Maybe<AcceptTrainingPayload>;
  addProfileSkillSet: Maybe<AddProfileSkillSetPayload>;
  addProfileSkillSetConnection: Maybe<AddProfileSkillSetConnectionPayload>;
  approveItemReview: Maybe<ApproveItemReviewPayload>;
  approveSectionReview: Maybe<ApproveSectionReviewPayload>;
  cancelResumeUpload: Maybe<CancelResumeUploadPayload>;
  changePortfolioItemPosition: Maybe<ChangePortfolioItemPositionPayload>;
  createCertification: Maybe<CreateCertificationPayload>;
  createEducation: Maybe<CreateEducationPayload>;
  createEmployment: Maybe<CreateEmploymentPayload>;
  createEngagementTestimonial: Maybe<CreateEngagementTestimonialPayload>;
  createIndustryProfile: Maybe<CreateIndustryProfilePayload>;
  createPayoneerPaymentOption: Maybe<CreatePayoneerPaymentOptionPayload>;
  createPortfolioItem: Maybe<CreatePortfolioItemPayload>;
  createToptalPaymentAccount: Maybe<CreateToptalPaymentAccountPayload>;
  createTravelVisa: Maybe<CreateTravelVisaPayload>;
  dismissTestimonialNotification: Maybe<DismissTestimonialNotificationPayload>;
  highlightCertification: Maybe<HighlightCertificationPayload>;
  highlightEducation: Maybe<HighlightEducationPayload>;
  highlightEmployment: Maybe<HighlightEmploymentPayload>;
  highlightPortfolioItem: Maybe<HighlightPortfolioItemPayload>;
  logOut: Maybe<LogOutPayload>;
  removeCertification: Maybe<RemoveCertificationPayload>;
  removeEducation: Maybe<RemoveEducationPayload>;
  removeEmployment: Maybe<RemoveEmploymentPayload>;
  removePortfolioItem: Maybe<RemovePortfolioItemPayload>;
  removeProfileSkillSet: Maybe<RemoveProfileSkillSetPayload>;
  removeProfileSkillSetConnection: Maybe<RemoveProfileSkillSetConnectionPayload>;
  removeTravelVisa: Maybe<RemoveTravelVisaPayload>;
  requestTaxForm: Maybe<RequestTaxFormPayload>;
  sendContracts: Maybe<SendContractsPayload>;
  submitForReview: Maybe<SubmitForReviewPayload>;
  updateAdvancedProfileWizardStatus: Maybe<UpdateAdvancedProfileWizardStatusPayload>;
  updateBasicInfo: Maybe<UpdateBasicInfoPayload>;
  updateCertification: Maybe<UpdateCertificationPayload>;
  updateCustomRequirements: Maybe<UpdateCustomRequirementsPayload>;
  updateEducation: Maybe<UpdateEducationPayload>;
  updateEmployment: Maybe<UpdateEmploymentPayload>;
  updateExternalProfiles: Maybe<UpdateExternalProfilesPayload>;
  updateIndustryProfile: Maybe<UpdateIndustryProfilePayload>;
  updatePhoto: Maybe<UpdatePhotoPayload>;
  updatePortfolioItem: Maybe<UpdatePortfolioItemPayload>;
  updateProfileSkillSetExperience: Maybe<UpdateProfileSkillSetExperiencePayload>;
  updateProfileSkillSetPublicity: Maybe<UpdateProfileSkillSetPublicityPayload>;
  updateProfileSkillSetRating: Maybe<UpdateProfileSkillSetRatingPayload>;
  updateTravelVisa: Maybe<UpdateTravelVisaPayload>;
  updateWorkingHours: Maybe<UpdateWorkingHoursPayload>;
  uploadPortfolioCoverImage: Maybe<UploadPortfolioCoverImagePayload>;
  uploadPortfolioFile: Maybe<UploadPortfolioFilePayload>;
  uploadResume: Maybe<UploadResumePayload>;
};


export type MutationAcceptAgreementArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationAcceptFreelanceTalentAgreementArgs = {
  input: AcceptFreelanceTalentAgreementInput;
};


export type MutationAcceptTrainingArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationAddProfileSkillSetArgs = {
  input: AddProfileSkillSetInput;
};


export type MutationAddProfileSkillSetConnectionArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationApproveItemReviewArgs = {
  input: ApproveItemReviewInput;
};


export type MutationApproveSectionReviewArgs = {
  input: ApproveSectionReviewInput;
};


export type MutationCancelResumeUploadArgs = {
  input: CancelResumeUploadInput;
};


export type MutationChangePortfolioItemPositionArgs = {
  input: ChangePortfolioItemPositionInput;
};


export type MutationCreateCertificationArgs = {
  input: CreateCertificationInput;
};


export type MutationCreateEducationArgs = {
  input: CreateEducationInput;
};


export type MutationCreateEmploymentArgs = {
  input: CreateEmploymentInput;
};


export type MutationCreateEngagementTestimonialArgs = {
  input: CreateEngagementTestimonialInput;
};


export type MutationCreateIndustryProfileArgs = {
  input: CreateIndustryProfileInput;
};


export type MutationCreatePayoneerPaymentOptionArgs = {
  input: CreatePayoneerPaymentOptionInput;
};


export type MutationCreatePortfolioItemArgs = {
  input: CreatePortfolioItemInput;
};


export type MutationCreateToptalPaymentAccountArgs = {
  input: CreateToptalPaymentAccountInput;
};


export type MutationCreateTravelVisaArgs = {
  input: CreateTravelVisaInput;
};


export type MutationDismissTestimonialNotificationArgs = {
  input: DismissTestimonialNotificationInput;
};


export type MutationHighlightCertificationArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationHighlightEducationArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationHighlightEmploymentArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationHighlightPortfolioItemArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationLogOutArgs = {
  input: LogOutInput;
};


export type MutationRemoveCertificationArgs = {
  input: RemoveCertificationInput;
};


export type MutationRemoveEducationArgs = {
  input: RemoveEducationInput;
};


export type MutationRemoveEmploymentArgs = {
  input: RemoveEmploymentInput;
};


export type MutationRemovePortfolioItemArgs = {
  input: RemovePortfolioItemInput;
};


export type MutationRemoveProfileSkillSetArgs = {
  input: RemoveProfileSkillSetInput;
};


export type MutationRemoveProfileSkillSetConnectionArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationRemoveTravelVisaArgs = {
  input: RemoveTravelVisaInput;
};


export type MutationRequestTaxFormArgs = {
  input: RequestTaxFormInput;
};


export type MutationSendContractsArgs = {
  input: SendContractsInput;
};


export type MutationSubmitForReviewArgs = {
  input: SubmitForReviewInput;
};


export type MutationUpdateAdvancedProfileWizardStatusArgs = {
  input: UpdateAdvancedProfileWizardStatusInput;
};


export type MutationUpdateBasicInfoArgs = {
  input: UpdateBasicInfoInput;
};


export type MutationUpdateCertificationArgs = {
  input: UpdateCertificationInput;
};


export type MutationUpdateCustomRequirementsArgs = {
  input: UpdateCustomRequirementsInput;
};


export type MutationUpdateEducationArgs = {
  input: UpdateEducationInput;
};


export type MutationUpdateEmploymentArgs = {
  input: UpdateEmploymentInput;
};


export type MutationUpdateExternalProfilesArgs = {
  input: UpdateExternalProfilesInput;
};


export type MutationUpdateIndustryProfileArgs = {
  input: UpdateIndustryProfileInput;
};


export type MutationUpdatePhotoArgs = {
  input: UpdatePhotoInput;
};


export type MutationUpdatePortfolioItemArgs = {
  input: UpdatePortfolioItemInput;
};


export type MutationUpdateProfileSkillSetExperienceArgs = {
  input: UpdateProfileSkillSetExperienceInput;
};


export type MutationUpdateProfileSkillSetPublicityArgs = {
  input: UpdateProfileSkillSetPublicityInput;
};


export type MutationUpdateProfileSkillSetRatingArgs = {
  input: UpdateProfileSkillSetRatingInput;
};


export type MutationUpdateTravelVisaArgs = {
  input: UpdateTravelVisaInput;
};


export type MutationUpdateWorkingHoursArgs = {
  input: UpdateWorkingHoursInput;
};


export type MutationUploadPortfolioCoverImageArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationUploadPortfolioFileArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationUploadResumeArgs = {
  input: UploadResumeInput;
};

export type MutationResult = {
  __typename?: 'MutationResult';
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type Node = {
  __typename?: 'Node';
  id: Maybe<Scalars['Unknown']['output']>;
};

export type Payoneer = {
  __typename?: 'Payoneer';
  canLeave: Maybe<Scalars['Unknown']['output']>;
  comment: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  isSelected: Maybe<Scalars['Unknown']['output']>;
  nameOnAccount: Maybe<Scalars['Unknown']['output']>;
  paymentMethod: Maybe<Scalars['Unknown']['output']>;
  payoneerId: Maybe<Scalars['Unknown']['output']>;
  status: Maybe<Scalars['Unknown']['output']>;
};

export type PortfolioCoverImageTransformationInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type PortfolioItem = {
  __typename?: 'PortfolioItem';
  accomplishment: Maybe<Scalars['Unknown']['output']>;
  clientOrCompanyLogoUrl: Maybe<Scalars['Unknown']['output']>;
  clientOrCompanyName: Maybe<Scalars['Unknown']['output']>;
  coverImage: Maybe<Scalars['Unknown']['output']>;
  description: Maybe<Scalars['Unknown']['output']>;
  details: Maybe<PortfolioItemImageBlock>;
  engagement: Maybe<Scalars['Unknown']['output']>;
  files: Maybe<PortfolioItemFileConnection>;
  highlight: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  industries: Maybe<Scalars['Unknown']['output']>;
  kpis: Maybe<Scalars['Unknown']['output']>;
  link: Maybe<Scalars['Unknown']['output']>;
  publicationPermit: Maybe<Scalars['Unknown']['output']>;
  quotes: Maybe<Scalars['Unknown']['output']>;
  showViaToptal: Maybe<Scalars['Unknown']['output']>;
  skills: Maybe<Scalars['Unknown']['output']>;
  title: Maybe<Scalars['Unknown']['output']>;
  toptalRelated: Maybe<Scalars['Unknown']['output']>;
  websiteUrl: Maybe<Scalars['Unknown']['output']>;
};

export type PortfolioItemFile = {
  __typename?: 'PortfolioItemFile';
  contentType: Maybe<Scalars['Unknown']['output']>;
  description: Maybe<Scalars['Unknown']['output']>;
  title: Maybe<Scalars['Unknown']['output']>;
};

export type PortfolioItemFileConnection = {
  __typename?: 'PortfolioItemFileConnection';
  nodes: Maybe<PortfolioItemFilePdf>;
};

export type PortfolioItemFileImage = {
  __typename?: 'PortfolioItemFileImage';
  id: Maybe<Scalars['Unknown']['output']>;
  image: Maybe<PortfolioItemFileImageContent>;
};

export type PortfolioItemFileImageContent = {
  __typename?: 'PortfolioItemFileImageContent';
  optimizedUrl: Maybe<Scalars['Unknown']['output']>;
  thumbUrl: Maybe<Scalars['Unknown']['output']>;
};

export type PortfolioItemFilePdf = {
  __typename?: 'PortfolioItemFilePdf';
  fileUrl: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  primaryContentType: Maybe<Scalars['Unknown']['output']>;
};

export type PortfolioItemGalleryBlock = {
  __typename?: 'PortfolioItemGalleryBlock';
  id: Maybe<Scalars['Unknown']['output']>;
  items: Maybe<Scalars['Unknown']['output']>;
  title: Maybe<Scalars['Unknown']['output']>;
};

export type PortfolioItemImageBlock = {
  __typename?: 'PortfolioItemImageBlock';
  id: Maybe<Scalars['Unknown']['output']>;
  image: Maybe<Scalars['Unknown']['output']>;
  title: Maybe<Scalars['Unknown']['output']>;
};

export type PortfolioItemTextBlock = {
  __typename?: 'PortfolioItemTextBlock';
  contentHast: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  title: Maybe<Scalars['Unknown']['output']>;
};

export type PortfolioItemVideoBlock = {
  __typename?: 'PortfolioItemVideoBlock';
  id: Maybe<Scalars['Unknown']['output']>;
  title: Maybe<Scalars['Unknown']['output']>;
  videoUrl: Maybe<Scalars['Unknown']['output']>;
};

export type PortfolioItemsCountRecommendation = {
  __typename?: 'PortfolioItemsCountRecommendation';
  minimumCount: Maybe<Scalars['Unknown']['output']>;
};

export type PortfolioItemsMissingIndustryRecommendation = {
  __typename?: 'PortfolioItemsMissingIndustryRecommendation';
  portfolioItems: Maybe<Scalars['Unknown']['output']>;
};

export type Profile = {
  __typename?: 'Profile';
  about: Maybe<Scalars['Unknown']['output']>;
  advancedProfileWizardStatus: Maybe<Scalars['Unknown']['output']>;
  availableShiftRangeFrom: Maybe<Scalars['Unknown']['output']>;
  availableShiftRangeTo: Maybe<Scalars['Unknown']['output']>;
  basicInfoIndustries: Maybe<Scalars['Unknown']['output']>;
  behance: Maybe<Scalars['Unknown']['output']>;
  certifications: Maybe<Scalars['Unknown']['output']>;
  citizenship: Maybe<Scalars['Unknown']['output']>;
  city: Maybe<Scalars['Unknown']['output']>;
  country: Maybe<Scalars['Unknown']['output']>;
  customRequirements: Maybe<CustomRequirements>;
  dribbble: Maybe<Scalars['Unknown']['output']>;
  educations: Maybe<Scalars['Unknown']['output']>;
  employments: Maybe<Scalars['Unknown']['output']>;
  engagements: Maybe<Scalars['Unknown']['output']>;
  expectedEmploymentItems: Maybe<Scalars['Unknown']['output']>;
  experiments: Maybe<Scalars['Unknown']['output']>;
  fullName: Maybe<Scalars['Unknown']['output']>;
  github: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  jsonapiId: Maybe<Scalars['Unknown']['output']>;
  languages: Maybe<Scalars['Unknown']['output']>;
  legalName: Maybe<Scalars['Unknown']['output']>;
  linkedin: Maybe<Scalars['Unknown']['output']>;
  links: Maybe<Scalars['Unknown']['output']>;
  phoneNumber: Maybe<Scalars['Unknown']['output']>;
  photo: Maybe<Scalars['Unknown']['output']>;
  placeIdentity: Maybe<Scalars['Unknown']['output']>;
  portfolioItems: Maybe<Scalars['Unknown']['output']>;
  prefillStatusEnum: Maybe<Scalars['Unknown']['output']>;
  profileCompletion: Maybe<ProfileCompletion>;
  profileReadiness: Maybe<Scalars['Unknown']['output']>;
  quote: Maybe<Scalars['Unknown']['output']>;
  recommendations: Maybe<Scalars['Unknown']['output']>;
  reportingToAutocomplete: Maybe<Scalars['Unknown']['output']>;
  roleType: Maybe<Scalars['Unknown']['output']>;
  skillSets: Maybe<Scalars['Unknown']['output']>;
  skillsAutocomplete: Maybe<Scalars['Unknown']['output']>;
  skillsReadiness: Maybe<Scalars['Unknown']['output']>;
  skype: Maybe<Scalars['Unknown']['output']>;
  softwareSkills: Maybe<Scalars['Unknown']['output']>;
  submitAvailable: Maybe<Scalars['Unknown']['output']>;
  talent: Maybe<Scalars['Unknown']['output']>;
  talentEngagementAutocomplete: Maybe<Scalars['Unknown']['output']>;
  timeZone: Maybe<Scalars['Unknown']['output']>;
  toptalYearsOfExperience: Maybe<Scalars['Unknown']['output']>;
  travelVisas: Maybe<Scalars['Unknown']['output']>;
  twitter: Maybe<Scalars['Unknown']['output']>;
  updatedByTalentAt: Maybe<Scalars['Unknown']['output']>;
  versions: Maybe<Scalars['Unknown']['output']>;
  vertical: Maybe<Scalars['Unknown']['output']>;
  website: Maybe<Scalars['Unknown']['output']>;
  workingTimeFrom: Maybe<Scalars['Unknown']['output']>;
  workingTimeTo: Maybe<Scalars['Unknown']['output']>;
};


export type ProfileReportingToAutocompleteArgs = {
  limit: InputMaybe<Scalars['Unknown']['input']>;
  name: InputMaybe<Scalars['Unknown']['input']>;
};


export type ProfileSkillsAutocompleteArgs = {
  limit: InputMaybe<Scalars['Unknown']['input']>;
  search: InputMaybe<Scalars['Unknown']['input']>;
  withoutIds: InputMaybe<Scalars['Unknown']['input']>;
};


export type ProfileTalentEngagementAutocompleteArgs = {
  id: InputMaybe<Scalars['Unknown']['input']>;
};

export type ProfileCompletion = {
  __typename?: 'ProfileCompletion';
  basicInformation: Maybe<Scalars['Unknown']['output']>;
  certificationItemsCount: Maybe<Scalars['Unknown']['output']>;
  educationItemsCount: Maybe<Scalars['Unknown']['output']>;
  employmentItems: Maybe<Scalars['Unknown']['output']>;
  headshot: Maybe<Scalars['Unknown']['output']>;
  overall: Maybe<Scalars['Unknown']['output']>;
  portfolioItems: Maybe<Scalars['Unknown']['output']>;
  skills: Maybe<Scalars['Unknown']['output']>;
  timezone: Maybe<Scalars['Unknown']['output']>;
};

export type ProfileFreshnessRecommendation = {
  __typename?: 'ProfileFreshnessRecommendation';
  certificationsStatus: Maybe<Scalars['Unknown']['output']>;
  educationsStatus: Maybe<Scalars['Unknown']['output']>;
  portfolioItemsStatus: Maybe<Scalars['Unknown']['output']>;
  skillsStatus: Maybe<Scalars['Unknown']['output']>;
  workExperiencesStatus: Maybe<Scalars['Unknown']['output']>;
};

export type ProfileSkillSet = {
  __typename?: 'ProfileSkillSet';
  connections: Maybe<Scalars['Unknown']['output']>;
  experience: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  position: Maybe<Scalars['Unknown']['output']>;
  public: Maybe<Scalars['Unknown']['output']>;
  rating: Maybe<Scalars['Unknown']['output']>;
  skill: Maybe<Scalars['Unknown']['output']>;
};

export type Query = {
  __typename?: 'Query';
  activation: Maybe<Scalars['Unknown']['output']>;
  agreement: Maybe<Scalars['Unknown']['output']>;
  agreementAcceptance: Maybe<Scalars['Unknown']['output']>;
  countries: Maybe<Scalars['Unknown']['output']>;
  employersAutocomplete: Maybe<Employer>;
  freelanceTalentAgreement: Maybe<Scalars['Unknown']['output']>;
  industriesAutocomplete: Maybe<Industry>;
  languages: Maybe<Scalars['Unknown']['output']>;
  links: Maybe<Scalars['Unknown']['output']>;
  node: Maybe<IndustryProfile>;
  profile: Maybe<Profile>;
  sectionReviews: Maybe<SectionReview>;
  stepSupportStaff: Maybe<Scalars['Unknown']['output']>;
  supportStaff: Maybe<Scalars['Unknown']['output']>;
  taxForms: Maybe<TaxForm>;
  timeZones: Maybe<Scalars['Unknown']['output']>;
  viewer: Maybe<Scalars['Unknown']['output']>;
};


export type QueryEmployersAutocompleteArgs = {
  limit: Scalars['Int']['input'];
  search: Scalars['String']['input'];
};


export type QueryIndustriesAutocompleteArgs = {
  limit: Scalars['Int']['input'];
  search: Scalars['String']['input'];
  withoutIds: InputMaybe<Array<Scalars['ID']['input']>>;
};


export type QueryNodeArgs = {
  id: Scalars['ID']['input'];
};


export type QueryProfileArgs = {
  id: Scalars['ID']['input'];
};


export type QuerySectionReviewsArgs = {
  id: Scalars['ID']['input'];
};


export type QueryStepSupportStaffArgs = {
  stepId: Scalars['ID']['input'];
};


export type QuerySupportStaffArgs = {
  settingsName: Scalars['SettingName']['input'];
};

export type RemoveCertificationInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type RemoveCertificationPayload = {
  __typename?: 'RemoveCertificationPayload';
  errors: Maybe<UserError>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type RemoveEducationInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type RemoveEducationPayload = {
  __typename?: 'RemoveEducationPayload';
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type RemoveEmploymentInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type RemoveEmploymentPayload = {
  __typename?: 'RemoveEmploymentPayload';
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type RemovePortfolioItemInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type RemovePortfolioItemPayload = {
  __typename?: 'RemovePortfolioItemPayload';
  profile: Maybe<Profile>;
};

export type RemoveProfileSkillSetConnectionPayload = {
  __typename?: 'RemoveProfileSkillSetConnectionPayload';
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Scalars['Unknown']['output']>;
  skillSet: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type RemoveProfileSkillSetInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type RemoveProfileSkillSetPayload = {
  __typename?: 'RemoveProfileSkillSetPayload';
  errors: Maybe<UserError>;
  profile: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type RemoveTravelVisaInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type RemoveTravelVisaPayload = {
  __typename?: 'RemoveTravelVisaPayload';
  errors: Maybe<UserError>;
  profile: Maybe<Scalars['Unknown']['output']>;
};

export type RequestTaxFormInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type RequestTaxFormPayload = {
  __typename?: 'RequestTaxFormPayload';
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
  talent: Maybe<Scalars['Unknown']['output']>;
};

export type SectionReview = {
  __typename?: 'SectionReview';
  id: Maybe<Scalars['Unknown']['output']>;
  items: Maybe<Scalars['Unknown']['output']>;
  requestedAt: Maybe<Scalars['Unknown']['output']>;
  section: Maybe<Scalars['Unknown']['output']>;
};

export type SendContractsInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type SendContractsPayload = {
  __typename?: 'SendContractsPayload';
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
  talent: Maybe<Scalars['Unknown']['output']>;
};

export type SkillSetsMissingConnectionsRecommendation = {
  __typename?: 'SkillSetsMissingConnectionsRecommendation';
  skillSets: Maybe<Scalars['Unknown']['output']>;
};

export type SubmitForReviewInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type SubmitForReviewPayload = {
  __typename?: 'SubmitForReviewPayload';
  activation: Maybe<Activation>;
  errors: Maybe<Scalars['Unknown']['output']>;
  notice: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type Talent = {
  __typename?: 'Talent';
  id: Maybe<Scalars['Unknown']['output']>;
  paymentOptions: Maybe<Payoneer>;
};

export type TalentEngagement = {
  __typename?: 'TalentEngagement';
  clientName: Maybe<Scalars['Unknown']['output']>;
  endDate: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  jobPlainId: Maybe<Scalars['Unknown']['output']>;
  jobTitle: Maybe<Scalars['Unknown']['output']>;
  startDate: Maybe<Scalars['Unknown']['output']>;
  status: Maybe<Scalars['Unknown']['output']>;
};

export type TalentProfileVersion = {
  __typename?: 'TalentProfileVersion';
  id: Maybe<Scalars['Unknown']['output']>;
  snapshotText: Maybe<Scalars['Unknown']['output']>;
};

export type TaxForm = {
  __typename?: 'TaxForm';
  description: Maybe<Scalars['Unknown']['output']>;
  formType: Maybe<Scalars['Unknown']['output']>;
  title: Maybe<Scalars['Unknown']['output']>;
};

export type TestimonialEngagementRecommendation = {
  __typename?: 'TestimonialEngagementRecommendation';
  engagements: Maybe<Scalars['Unknown']['output']>;
};

export type ToptalPayments = {
  __typename?: 'ToptalPayments';
  firstName: Maybe<Scalars['Unknown']['output']>;
  lastName: Maybe<Scalars['Unknown']['output']>;
  phoneNumber: Maybe<Scalars['Unknown']['output']>;
  postalCode: Maybe<Scalars['Unknown']['output']>;
};

export type TravelVisa = {
  __typename?: 'TravelVisa';
  country: Maybe<Scalars['Unknown']['output']>;
  expiryDate: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  visaType: Maybe<Scalars['Unknown']['output']>;
};

export type UpdateAdvancedProfileWizardStatusInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateAdvancedProfileWizardStatusPayload = {
  __typename?: 'UpdateAdvancedProfileWizardStatusPayload';
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UpdateBasicInfoInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateBasicInfoPayload = {
  __typename?: 'UpdateBasicInfoPayload';
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UpdateCertificationInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateCertificationPayload = {
  __typename?: 'UpdateCertificationPayload';
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UpdateCustomRequirementsInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateCustomRequirementsPayload = {
  __typename?: 'UpdateCustomRequirementsPayload';
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UpdateEducationInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateEducationPayload = {
  __typename?: 'UpdateEducationPayload';
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UpdateEmploymentInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateEmploymentPayload = {
  __typename?: 'UpdateEmploymentPayload';
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UpdateExternalProfilesInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateExternalProfilesPayload = {
  __typename?: 'UpdateExternalProfilesPayload';
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UpdateIndustryProfileInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateIndustryProfilePayload = {
  __typename?: 'UpdateIndustryProfilePayload';
  errors: Maybe<UserError>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UpdatePhotoInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdatePhotoPayload = {
  __typename?: 'UpdatePhotoPayload';
  errors: Maybe<UserError>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UpdatePortfolioItemInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdatePortfolioItemPayload = {
  __typename?: 'UpdatePortfolioItemPayload';
  profile: Maybe<Profile>;
};

export type UpdateProfileSkillSetExperienceInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateProfileSkillSetExperiencePayload = {
  __typename?: 'UpdateProfileSkillSetExperiencePayload';
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  skillSet: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UpdateProfileSkillSetPublicityInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateProfileSkillSetPublicityPayload = {
  __typename?: 'UpdateProfileSkillSetPublicityPayload';
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  skillSet: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UpdateProfileSkillSetRatingInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateProfileSkillSetRatingPayload = {
  __typename?: 'UpdateProfileSkillSetRatingPayload';
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  skillSet: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UpdateTravelVisaInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateTravelVisaPayload = {
  __typename?: 'UpdateTravelVisaPayload';
  errors: Maybe<UserError>;
  profile: Maybe<Profile>;
};

export type UpdateWorkingHoursInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateWorkingHoursPayload = {
  __typename?: 'UpdateWorkingHoursPayload';
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UploadPortfolioCoverImagePayload = {
  __typename?: 'UploadPortfolioCoverImagePayload';
  coverImageCacheName: Maybe<Scalars['Unknown']['output']>;
  coverImageUrl: Maybe<Scalars['Unknown']['output']>;
};

export type UploadPortfolioFilePayload = {
  __typename?: 'UploadPortfolioFilePayload';
  fileCacheName: Maybe<Scalars['Unknown']['output']>;
  fileUrl: Maybe<Scalars['Unknown']['output']>;
};

export type UploadResumeInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UploadResumePayload = {
  __typename?: 'UploadResumePayload';
  errors: Maybe<UserError>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UserError = {
  __typename?: 'UserError';
  code: Maybe<Scalars['Unknown']['output']>;
  key: Maybe<Scalars['Unknown']['output']>;
  message: Maybe<Scalars['Unknown']['output']>;
};

export type Verification = {
  __typename?: 'Verification';
  id: Maybe<Scalars['Unknown']['output']>;
  link: Maybe<Scalars['Unknown']['output']>;
  status: Maybe<Scalars['Unknown']['output']>;
  updatedAt: Maybe<Scalars['Unknown']['output']>;
};

export type CertificationConnectionFragment = { id: unknown, certificate: unknown, institution: unknown, validFromYear: unknown, validToYear: unknown };

export type ContractFragment = { id: unknown, billingType: unknown, provider: unknown, kind: unknown, title: unknown, status: unknown, signedAt: unknown, sentAt: unknown, isActive: unknown, verificationDeadline: unknown };

export type ContractProfileFragment = { id: unknown, billingType: unknown, kind: unknown, title: unknown, status: unknown, signedAt: unknown, sentAt: unknown, isActive: unknown, verificationDeadline: unknown };

export type CustomRequirementsFragment = { backgroundCheck: unknown, drugTest: unknown, timeTrackingTools: unknown };

export type EducationConnectionFragment = { id: unknown, title: unknown, location: unknown, degree: unknown, yearFrom: unknown, yearTo: unknown };

export type EmploymentConnectionFragment = { id: unknown, company: unknown, position: unknown, startDate: unknown, endDate: unknown, experienceItems: unknown };

export type IndustryFragment = { id: unknown, name: unknown };

export type MutationResultFragmentFragment = { success: unknown, notice: unknown, errors: { code: unknown, key: unknown, message: unknown } | null };

export type PortfolioItemConnectionFragment = { id: unknown, title: unknown, link: unknown, description: unknown };

export type PortfolioItemFileFragment = { contentType: unknown, description: unknown, title: unknown };

export type PortfolioItemFileImageContentFragment = { optimizedUrl: unknown, thumbUrl: unknown };

export type PortfolioItemTextBlockFragment = { id: unknown, title: unknown, contentHast: unknown };

export type PortfolioItemVideoBlockFragment = { id: unknown, title: unknown, videoUrl: unknown };

export type PortfolioItemsMissingIndustryFragment = { id: unknown, title: unknown };

export type ProfileCompletionFragment = { basicInformation: unknown, certificationItemsCount: unknown, educationItemsCount: unknown, employmentItems: unknown, headshot: unknown, overall: unknown, portfolioItems: unknown, skills: unknown, timezone: unknown };

export type RecentIdVerificationFragment = { id: unknown, status: unknown, link: unknown, updatedAt: unknown };

export type TalentEngagementFragment = { id: unknown, status: unknown, startDate: unknown, endDate: unknown, jobTitle: unknown, jobPlainId: unknown, clientName: unknown };

export type TaxFormFragment = { description: unknown, formType: unknown, title: unknown };

export type UserErrorFragmentFragment = { code: unknown, key: unknown, message: unknown };

export type Create_Engagement_TestimonialMutationVariables = Exact<{
  input: CreateEngagementTestimonialInput;
}>;


export type Create_Engagement_TestimonialMutation = { createEngagementTestimonial: { notice: unknown, success: unknown, errors: { code: unknown, key: unknown, message: unknown } | null } | null };

export type CreateIndustryProfileMutationVariables = Exact<{
  input: CreateIndustryProfileInput;
}>;


export type CreateIndustryProfileMutation = { createIndustryProfile: { success: unknown, errors: { code: unknown, key: unknown, message: unknown } | null } | null };

export type DismissTestimonialNotificationMutationVariables = Exact<{
  input: DismissTestimonialNotificationInput;
}>;


export type DismissTestimonialNotificationMutation = { dismissTestimonialNotification: { notice: unknown, success: unknown, errors: { code: unknown, key: unknown, message: unknown } | null } | null };

export type Get_Industries_For_AutocompleteQueryVariables = Exact<{
  search: string;
  limit: number;
  withoutIds: Array<string | number> | string | number | null | undefined;
}>;


export type Get_Industries_For_AutocompleteQuery = { industriesAutocomplete: { id: unknown, name: unknown } | null };

export type UpdateIndustryProfileMutationVariables = Exact<{
  input: UpdateIndustryProfileInput;
}>;


export type UpdateIndustryProfileMutation = { updateIndustryProfile: { success: unknown, errors: { code: unknown, key: unknown, message: unknown } | null } | null };

export type CancelResumeUploadMutationVariables = Exact<{
  input: CancelResumeUploadInput;
}>;


export type CancelResumeUploadMutation = { cancelResumeUpload: { success: unknown, errors: { code: unknown, key: unknown, message: unknown } | null } | null };

export type GetCustomRequirementsQueryVariables = Exact<{
  profileId: string | number;
}>;


export type GetCustomRequirementsQuery = { profile: { id: unknown, customRequirements: { backgroundCheck: unknown, drugTest: unknown, timeTrackingTools: unknown } | null } | null };

export type GetLastUpdateAtQueryVariables = Exact<{
  profileId: string | number;
}>;


export type GetLastUpdateAtQuery = { profile: { id: unknown, updatedByTalentAt: unknown } | null };

export type GetProfilePrefillStatusQueryVariables = Exact<{
  profileId: string | number;
}>;


export type GetProfilePrefillStatusQuery = { profile: { id: unknown, prefillStatusEnum: unknown } | null };

export type UploadResumeMutationVariables = Exact<{
  input: UploadResumeInput;
}>;


export type UploadResumeMutation = { uploadResume: { success: unknown, errors: { code: unknown, key: unknown, message: unknown } | null } | null };
