// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Oleksii PELYKH
//
// AUTO-GENERATED by `pnpm codegen` from
// `../research/graphql/talent_profile/schema.graphql` and operations under
// `../research/graphql/talent_profile/operations/`.
// Do not edit by hand; re-run codegen instead.
//
// Companion file to `talent-profile.ts`. See `zod-schemas.ts` header
// for the TS-type / Zod-schema duality applied to this output.

import { z } from 'zod'
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  SettingName: { input: unknown; output: unknown; }
  Unknown: { input: unknown; output: unknown; }
  Upload: { input: unknown; output: unknown; }
};

export type AcceptAgreementPayload = {
  activation: Maybe<Activation>;
  errors: Maybe<Scalars['Unknown']['output']>;
  notice: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type AcceptFreelanceTalentAgreementInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type AcceptFreelanceTalentAgreementPayload = {
  contract: Maybe<Contract>;
  errors: Maybe<Scalars['Unknown']['output']>;
  notice: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type AcceptTrainingPayload = {
  activation: Maybe<Activation>;
  errors: Maybe<Scalars['Unknown']['output']>;
  notice: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type Activation = {
  steps: Maybe<Scalars['Unknown']['output']>;
};

export type AddProfileSkillSetConnectionPayload = {
  profile: Maybe<Scalars['Unknown']['output']>;
  skillSet: Maybe<Scalars['Unknown']['output']>;
};

export type AddProfileSkillSetInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type AddProfileSkillSetPayload = {
  profile: Maybe<Profile>;
  skillSet: Maybe<ProfileSkillSet>;
};

export type AdvancedProfileRecommendation = {
  isCustomRequirementsCompleted: Maybe<Scalars['Unknown']['output']>;
  isTravelInformationCompleted: Maybe<Scalars['Unknown']['output']>;
};

export type ApproveItemReviewInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type ApproveItemReviewPayload = {
  sectionReviews: Maybe<SectionReview>;
};

export type ApproveSectionReviewInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type ApproveSectionReviewPayload = {
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  sectionReviews: Maybe<SectionReview>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type CancelResumeUploadInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type CancelResumeUploadPayload = {
  errors: Maybe<UserError>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type Certification = {
  certificate: Maybe<Scalars['Unknown']['output']>;
  highlight: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  institution: Maybe<Scalars['Unknown']['output']>;
  link: Maybe<Scalars['Unknown']['output']>;
  number: Maybe<Scalars['Unknown']['output']>;
  skills: Maybe<Scalars['Unknown']['output']>;
  status: Maybe<Scalars['Unknown']['output']>;
  validFromMonth: Maybe<Scalars['Unknown']['output']>;
  validFromYear: Maybe<Scalars['Unknown']['output']>;
  validToMonth: Maybe<Scalars['Unknown']['output']>;
  validToYear: Maybe<Scalars['Unknown']['output']>;
};

export type ChangePortfolioItemPositionInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type ChangePortfolioItemPositionPayload = {
  profile: Maybe<Profile>;
};

export type Contract = {
  billingType: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  isActive: Maybe<Scalars['Unknown']['output']>;
  kind: Maybe<Scalars['Unknown']['output']>;
  provider: Maybe<Scalars['Unknown']['output']>;
  sentAt: Maybe<Scalars['Unknown']['output']>;
  signedAt: Maybe<Scalars['Unknown']['output']>;
  status: Maybe<Scalars['Unknown']['output']>;
  title: Maybe<Scalars['Unknown']['output']>;
  verificationDeadline: Maybe<Scalars['Unknown']['output']>;
};

export type CreateCertificationInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type CreateCertificationPayload = {
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type CreateEducationInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type CreateEducationPayload = {
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type CreateEmploymentInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type CreateEmploymentPayload = {
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type CreateEngagementTestimonialInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type CreateEngagementTestimonialPayload = {
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type CreateIndustryProfileInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type CreateIndustryProfilePayload = {
  errors: Maybe<UserError>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type CreatePayoneerPaymentOptionInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type CreatePayoneerPaymentOptionPayload = {
  errors: Maybe<UserError>;
  success: Maybe<Scalars['Unknown']['output']>;
  talent: Maybe<Talent>;
};

export type CreatePortfolioItemInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type CreatePortfolioItemPayload = {
  profile: Maybe<Profile>;
};

export type CreateToptalPaymentAccountInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type CreateToptalPaymentAccountPayload = {
  errors: Maybe<UserError>;
  success: Maybe<Scalars['Unknown']['output']>;
  talent: Maybe<Talent>;
};

export type CreateTravelVisaInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type CreateTravelVisaPayload = {
  errors: Maybe<UserError>;
  profile: Maybe<Scalars['Unknown']['output']>;
};

export type CustomRequirements = {
  backgroundCheck: Maybe<Scalars['Unknown']['output']>;
  drugTest: Maybe<Scalars['Unknown']['output']>;
  timeTrackingTools: Maybe<Scalars['Unknown']['output']>;
};

export type DismissTestimonialNotificationInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type DismissTestimonialNotificationPayload = {
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type Education = {
  degree: Maybe<Scalars['Unknown']['output']>;
  fieldOfStudy: Maybe<Scalars['Unknown']['output']>;
  highlight: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  institution: Maybe<Scalars['Unknown']['output']>;
  location: Maybe<Scalars['Unknown']['output']>;
  skills: Maybe<Scalars['Unknown']['output']>;
  title: Maybe<Scalars['Unknown']['output']>;
  yearFrom: Maybe<Scalars['Unknown']['output']>;
  yearTo: Maybe<Scalars['Unknown']['output']>;
};

export type Employer = {
  city: Maybe<Scalars['Unknown']['output']>;
  country: Maybe<Scalars['Unknown']['output']>;
  employeeCount: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  industries: Maybe<Scalars['Unknown']['output']>;
  lastSyncedAt: Maybe<Scalars['Unknown']['output']>;
  logoUrl: Maybe<Scalars['Unknown']['output']>;
  name: Maybe<Scalars['Unknown']['output']>;
  otherNames: Maybe<Scalars['Unknown']['output']>;
  otherUrls: Maybe<Scalars['Unknown']['output']>;
  revenue: Maybe<Scalars['Unknown']['output']>;
  website: Maybe<Scalars['Unknown']['output']>;
};

export type Employment = {
  company: Maybe<Scalars['Unknown']['output']>;
  companyWebsite: Maybe<Scalars['Unknown']['output']>;
  employer: Maybe<Employer>;
  endDate: Maybe<Scalars['Unknown']['output']>;
  engagement: Maybe<Scalars['Unknown']['output']>;
  experienceItems: Maybe<Scalars['Unknown']['output']>;
  highlight: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  industries: Maybe<Scalars['Unknown']['output']>;
  isEnterpriseExperience: Maybe<Scalars['Unknown']['output']>;
  managementExperience: Maybe<Scalars['Unknown']['output']>;
  noWebsite: Maybe<Scalars['Unknown']['output']>;
  position: Maybe<Scalars['Unknown']['output']>;
  primaryGeography: Maybe<Scalars['Unknown']['output']>;
  publicationPermit: Maybe<Scalars['Unknown']['output']>;
  reportingTo: Maybe<Scalars['Unknown']['output']>;
  showViaToptal: Maybe<Scalars['Unknown']['output']>;
  skills: Maybe<Scalars['Unknown']['output']>;
  startDate: Maybe<Scalars['Unknown']['output']>;
  toptalRelated: Maybe<Scalars['Unknown']['output']>;
};

export type EmploymentsCountRecommendation = {
  minimumCount: Maybe<Scalars['Unknown']['output']>;
  type: Maybe<Scalars['Unknown']['output']>;
};

export type EmploymentsMissingDataRecommendation = {
  employments: Maybe<Scalars['Unknown']['output']>;
};

export type HighlightCertificationPayload = {
  certification: Maybe<Scalars['Unknown']['output']>;
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type HighlightEducationPayload = {
  education: Maybe<Scalars['Unknown']['output']>;
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type HighlightEmploymentPayload = {
  employment: Maybe<Scalars['Unknown']['output']>;
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type HighlightPortfolioItemPayload = {
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  portfolioItem: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type Industry = {
  id: Maybe<Scalars['Unknown']['output']>;
  name: Maybe<Scalars['Unknown']['output']>;
};

export type IndustryProfile = {
  about: Maybe<Scalars['Unknown']['output']>;
  certifications: Maybe<Scalars['Unknown']['output']>;
  domainArea: Maybe<Scalars['Unknown']['output']>;
  educations: Maybe<Scalars['Unknown']['output']>;
  employments: Maybe<Scalars['Unknown']['output']>;
  highlights: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  portfolioItems: Maybe<Scalars['Unknown']['output']>;
  title: Maybe<Scalars['Unknown']['output']>;
};

export type LogOutInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type LogOutPayload = {
  errors: Maybe<Scalars['Unknown']['output']>;
  notice: Maybe<Scalars['Unknown']['output']>;
  returnTo: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type Mutation = {
  acceptAgreement: Maybe<AcceptAgreementPayload>;
  acceptFreelanceTalentAgreement: Maybe<AcceptFreelanceTalentAgreementPayload>;
  acceptTraining: Maybe<AcceptTrainingPayload>;
  addProfileSkillSet: Maybe<AddProfileSkillSetPayload>;
  addProfileSkillSetConnection: Maybe<AddProfileSkillSetConnectionPayload>;
  approveItemReview: Maybe<ApproveItemReviewPayload>;
  approveSectionReview: Maybe<ApproveSectionReviewPayload>;
  cancelResumeUpload: Maybe<CancelResumeUploadPayload>;
  changePortfolioItemPosition: Maybe<ChangePortfolioItemPositionPayload>;
  createCertification: Maybe<CreateCertificationPayload>;
  createEducation: Maybe<CreateEducationPayload>;
  createEmployment: Maybe<CreateEmploymentPayload>;
  createEngagementTestimonial: Maybe<CreateEngagementTestimonialPayload>;
  createIndustryProfile: Maybe<CreateIndustryProfilePayload>;
  createPayoneerPaymentOption: Maybe<CreatePayoneerPaymentOptionPayload>;
  createPortfolioItem: Maybe<CreatePortfolioItemPayload>;
  createToptalPaymentAccount: Maybe<CreateToptalPaymentAccountPayload>;
  createTravelVisa: Maybe<CreateTravelVisaPayload>;
  dismissTestimonialNotification: Maybe<DismissTestimonialNotificationPayload>;
  highlightCertification: Maybe<HighlightCertificationPayload>;
  highlightEducation: Maybe<HighlightEducationPayload>;
  highlightEmployment: Maybe<HighlightEmploymentPayload>;
  highlightPortfolioItem: Maybe<HighlightPortfolioItemPayload>;
  logOut: Maybe<LogOutPayload>;
  removeCertification: Maybe<RemoveCertificationPayload>;
  removeEducation: Maybe<RemoveEducationPayload>;
  removeEmployment: Maybe<RemoveEmploymentPayload>;
  removePortfolioItem: Maybe<RemovePortfolioItemPayload>;
  removeProfileSkillSet: Maybe<RemoveProfileSkillSetPayload>;
  removeProfileSkillSetConnection: Maybe<RemoveProfileSkillSetConnectionPayload>;
  removeTravelVisa: Maybe<RemoveTravelVisaPayload>;
  requestTaxForm: Maybe<RequestTaxFormPayload>;
  sendContracts: Maybe<SendContractsPayload>;
  submitForReview: Maybe<SubmitForReviewPayload>;
  updateAdvancedProfileWizardStatus: Maybe<UpdateAdvancedProfileWizardStatusPayload>;
  updateBasicInfo: Maybe<UpdateBasicInfoPayload>;
  updateCertification: Maybe<UpdateCertificationPayload>;
  updateCustomRequirements: Maybe<UpdateCustomRequirementsPayload>;
  updateEducation: Maybe<UpdateEducationPayload>;
  updateEmployment: Maybe<UpdateEmploymentPayload>;
  updateExternalProfiles: Maybe<UpdateExternalProfilesPayload>;
  updateIndustryProfile: Maybe<UpdateIndustryProfilePayload>;
  updatePhoto: Maybe<UpdatePhotoPayload>;
  updatePortfolioItem: Maybe<UpdatePortfolioItemPayload>;
  updateProfileSkillSetExperience: Maybe<UpdateProfileSkillSetExperiencePayload>;
  updateProfileSkillSetPublicity: Maybe<UpdateProfileSkillSetPublicityPayload>;
  updateProfileSkillSetRating: Maybe<UpdateProfileSkillSetRatingPayload>;
  updateTravelVisa: Maybe<UpdateTravelVisaPayload>;
  updateWorkingHours: Maybe<UpdateWorkingHoursPayload>;
  uploadPortfolioCoverImage: Maybe<UploadPortfolioCoverImagePayload>;
  uploadPortfolioFile: Maybe<UploadPortfolioFilePayload>;
  uploadResume: Maybe<UploadResumePayload>;
};


export type MutationAcceptAgreementArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationAcceptFreelanceTalentAgreementArgs = {
  input: AcceptFreelanceTalentAgreementInput;
};


export type MutationAcceptTrainingArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationAddProfileSkillSetArgs = {
  input: AddProfileSkillSetInput;
};


export type MutationAddProfileSkillSetConnectionArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationApproveItemReviewArgs = {
  input: ApproveItemReviewInput;
};


export type MutationApproveSectionReviewArgs = {
  input: ApproveSectionReviewInput;
};


export type MutationCancelResumeUploadArgs = {
  input: CancelResumeUploadInput;
};


export type MutationChangePortfolioItemPositionArgs = {
  input: ChangePortfolioItemPositionInput;
};


export type MutationCreateCertificationArgs = {
  input: CreateCertificationInput;
};


export type MutationCreateEducationArgs = {
  input: CreateEducationInput;
};


export type MutationCreateEmploymentArgs = {
  input: CreateEmploymentInput;
};


export type MutationCreateEngagementTestimonialArgs = {
  input: CreateEngagementTestimonialInput;
};


export type MutationCreateIndustryProfileArgs = {
  input: CreateIndustryProfileInput;
};


export type MutationCreatePayoneerPaymentOptionArgs = {
  input: CreatePayoneerPaymentOptionInput;
};


export type MutationCreatePortfolioItemArgs = {
  input: CreatePortfolioItemInput;
};


export type MutationCreateToptalPaymentAccountArgs = {
  input: CreateToptalPaymentAccountInput;
};


export type MutationCreateTravelVisaArgs = {
  input: CreateTravelVisaInput;
};


export type MutationDismissTestimonialNotificationArgs = {
  input: DismissTestimonialNotificationInput;
};


export type MutationHighlightCertificationArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationHighlightEducationArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationHighlightEmploymentArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationHighlightPortfolioItemArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationLogOutArgs = {
  input: LogOutInput;
};


export type MutationRemoveCertificationArgs = {
  input: RemoveCertificationInput;
};


export type MutationRemoveEducationArgs = {
  input: RemoveEducationInput;
};


export type MutationRemoveEmploymentArgs = {
  input: RemoveEmploymentInput;
};


export type MutationRemovePortfolioItemArgs = {
  input: RemovePortfolioItemInput;
};


export type MutationRemoveProfileSkillSetArgs = {
  input: RemoveProfileSkillSetInput;
};


export type MutationRemoveProfileSkillSetConnectionArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationRemoveTravelVisaArgs = {
  input: RemoveTravelVisaInput;
};


export type MutationRequestTaxFormArgs = {
  input: RequestTaxFormInput;
};


export type MutationSendContractsArgs = {
  input: SendContractsInput;
};


export type MutationSubmitForReviewArgs = {
  input: SubmitForReviewInput;
};


export type MutationUpdateAdvancedProfileWizardStatusArgs = {
  input: UpdateAdvancedProfileWizardStatusInput;
};


export type MutationUpdateBasicInfoArgs = {
  input: UpdateBasicInfoInput;
};


export type MutationUpdateCertificationArgs = {
  input: UpdateCertificationInput;
};


export type MutationUpdateCustomRequirementsArgs = {
  input: UpdateCustomRequirementsInput;
};


export type MutationUpdateEducationArgs = {
  input: UpdateEducationInput;
};


export type MutationUpdateEmploymentArgs = {
  input: UpdateEmploymentInput;
};


export type MutationUpdateExternalProfilesArgs = {
  input: UpdateExternalProfilesInput;
};


export type MutationUpdateIndustryProfileArgs = {
  input: UpdateIndustryProfileInput;
};


export type MutationUpdatePhotoArgs = {
  input: UpdatePhotoInput;
};


export type MutationUpdatePortfolioItemArgs = {
  input: UpdatePortfolioItemInput;
};


export type MutationUpdateProfileSkillSetExperienceArgs = {
  input: UpdateProfileSkillSetExperienceInput;
};


export type MutationUpdateProfileSkillSetPublicityArgs = {
  input: UpdateProfileSkillSetPublicityInput;
};


export type MutationUpdateProfileSkillSetRatingArgs = {
  input: UpdateProfileSkillSetRatingInput;
};


export type MutationUpdateTravelVisaArgs = {
  input: UpdateTravelVisaInput;
};


export type MutationUpdateWorkingHoursArgs = {
  input: UpdateWorkingHoursInput;
};


export type MutationUploadPortfolioCoverImageArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationUploadPortfolioFileArgs = {
  input: InputMaybe<Scalars['Unknown']['input']>;
};


export type MutationUploadResumeArgs = {
  input: UploadResumeInput;
};

export type MutationResult = {
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type Node = {
  id: Maybe<Scalars['Unknown']['output']>;
};

export type Payoneer = {
  canLeave: Maybe<Scalars['Unknown']['output']>;
  comment: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  isSelected: Maybe<Scalars['Unknown']['output']>;
  nameOnAccount: Maybe<Scalars['Unknown']['output']>;
  paymentMethod: Maybe<Scalars['Unknown']['output']>;
  payoneerId: Maybe<Scalars['Unknown']['output']>;
  status: Maybe<Scalars['Unknown']['output']>;
};

export type PortfolioCoverImageTransformationInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type PortfolioItem = {
  accomplishment: Maybe<Scalars['Unknown']['output']>;
  clientOrCompanyLogoUrl: Maybe<Scalars['Unknown']['output']>;
  clientOrCompanyName: Maybe<Scalars['Unknown']['output']>;
  coverImage: Maybe<Scalars['Unknown']['output']>;
  description: Maybe<Scalars['Unknown']['output']>;
  details: Maybe<PortfolioItemImageBlock>;
  engagement: Maybe<Scalars['Unknown']['output']>;
  files: Maybe<PortfolioItemFileConnection>;
  highlight: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  industries: Maybe<Scalars['Unknown']['output']>;
  kpis: Maybe<Scalars['Unknown']['output']>;
  link: Maybe<Scalars['Unknown']['output']>;
  publicationPermit: Maybe<Scalars['Unknown']['output']>;
  quotes: Maybe<Scalars['Unknown']['output']>;
  showViaToptal: Maybe<Scalars['Unknown']['output']>;
  skills: Maybe<Scalars['Unknown']['output']>;
  title: Maybe<Scalars['Unknown']['output']>;
  toptalRelated: Maybe<Scalars['Unknown']['output']>;
  websiteUrl: Maybe<Scalars['Unknown']['output']>;
};

export type PortfolioItemFile = {
  contentType: Maybe<Scalars['Unknown']['output']>;
  description: Maybe<Scalars['Unknown']['output']>;
  title: Maybe<Scalars['Unknown']['output']>;
};

export type PortfolioItemFileConnection = {
  nodes: Maybe<PortfolioItemFilePdf>;
};

export type PortfolioItemFileImage = {
  id: Maybe<Scalars['Unknown']['output']>;
  image: Maybe<PortfolioItemFileImageContent>;
};

export type PortfolioItemFileImageContent = {
  optimizedUrl: Maybe<Scalars['Unknown']['output']>;
  thumbUrl: Maybe<Scalars['Unknown']['output']>;
};

export type PortfolioItemFilePdf = {
  fileUrl: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  primaryContentType: Maybe<Scalars['Unknown']['output']>;
};

export type PortfolioItemGalleryBlock = {
  id: Maybe<Scalars['Unknown']['output']>;
  items: Maybe<Scalars['Unknown']['output']>;
  title: Maybe<Scalars['Unknown']['output']>;
};

export type PortfolioItemImageBlock = {
  id: Maybe<Scalars['Unknown']['output']>;
  image: Maybe<Scalars['Unknown']['output']>;
  title: Maybe<Scalars['Unknown']['output']>;
};

export type PortfolioItemTextBlock = {
  contentHast: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  title: Maybe<Scalars['Unknown']['output']>;
};

export type PortfolioItemVideoBlock = {
  id: Maybe<Scalars['Unknown']['output']>;
  title: Maybe<Scalars['Unknown']['output']>;
  videoUrl: Maybe<Scalars['Unknown']['output']>;
};

export type PortfolioItemsCountRecommendation = {
  minimumCount: Maybe<Scalars['Unknown']['output']>;
};

export type PortfolioItemsMissingIndustryRecommendation = {
  portfolioItems: Maybe<Scalars['Unknown']['output']>;
};

export type Profile = {
  about: Maybe<Scalars['Unknown']['output']>;
  advancedProfileWizardStatus: Maybe<Scalars['Unknown']['output']>;
  availableShiftRangeFrom: Maybe<Scalars['Unknown']['output']>;
  availableShiftRangeTo: Maybe<Scalars['Unknown']['output']>;
  basicInfoIndustries: Maybe<Scalars['Unknown']['output']>;
  behance: Maybe<Scalars['Unknown']['output']>;
  certifications: Maybe<Scalars['Unknown']['output']>;
  citizenship: Maybe<Scalars['Unknown']['output']>;
  city: Maybe<Scalars['Unknown']['output']>;
  country: Maybe<Scalars['Unknown']['output']>;
  customRequirements: Maybe<CustomRequirements>;
  dribbble: Maybe<Scalars['Unknown']['output']>;
  educations: Maybe<Scalars['Unknown']['output']>;
  employments: Maybe<Scalars['Unknown']['output']>;
  engagements: Maybe<Scalars['Unknown']['output']>;
  expectedEmploymentItems: Maybe<Scalars['Unknown']['output']>;
  experiments: Maybe<Scalars['Unknown']['output']>;
  fullName: Maybe<Scalars['Unknown']['output']>;
  github: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  jsonapiId: Maybe<Scalars['Unknown']['output']>;
  languages: Maybe<Scalars['Unknown']['output']>;
  legalName: Maybe<Scalars['Unknown']['output']>;
  linkedin: Maybe<Scalars['Unknown']['output']>;
  links: Maybe<Scalars['Unknown']['output']>;
  phoneNumber: Maybe<Scalars['Unknown']['output']>;
  photo: Maybe<Scalars['Unknown']['output']>;
  placeIdentity: Maybe<Scalars['Unknown']['output']>;
  portfolioItems: Maybe<Scalars['Unknown']['output']>;
  prefillStatusEnum: Maybe<Scalars['Unknown']['output']>;
  profileCompletion: Maybe<ProfileCompletion>;
  profileReadiness: Maybe<Scalars['Unknown']['output']>;
  quote: Maybe<Scalars['Unknown']['output']>;
  recommendations: Maybe<Scalars['Unknown']['output']>;
  reportingToAutocomplete: Maybe<Scalars['Unknown']['output']>;
  roleType: Maybe<Scalars['Unknown']['output']>;
  skillSets: Maybe<Scalars['Unknown']['output']>;
  skillsAutocomplete: Maybe<Scalars['Unknown']['output']>;
  skillsReadiness: Maybe<Scalars['Unknown']['output']>;
  skype: Maybe<Scalars['Unknown']['output']>;
  softwareSkills: Maybe<Scalars['Unknown']['output']>;
  submitAvailable: Maybe<Scalars['Unknown']['output']>;
  talent: Maybe<Scalars['Unknown']['output']>;
  talentEngagementAutocomplete: Maybe<Scalars['Unknown']['output']>;
  timeZone: Maybe<Scalars['Unknown']['output']>;
  toptalYearsOfExperience: Maybe<Scalars['Unknown']['output']>;
  travelVisas: Maybe<Scalars['Unknown']['output']>;
  twitter: Maybe<Scalars['Unknown']['output']>;
  updatedByTalentAt: Maybe<Scalars['Unknown']['output']>;
  versions: Maybe<Scalars['Unknown']['output']>;
  vertical: Maybe<Scalars['Unknown']['output']>;
  website: Maybe<Scalars['Unknown']['output']>;
  workingTimeFrom: Maybe<Scalars['Unknown']['output']>;
  workingTimeTo: Maybe<Scalars['Unknown']['output']>;
};


export type ProfileReportingToAutocompleteArgs = {
  limit: InputMaybe<Scalars['Unknown']['input']>;
  name: InputMaybe<Scalars['Unknown']['input']>;
};


export type ProfileSkillsAutocompleteArgs = {
  limit: InputMaybe<Scalars['Unknown']['input']>;
  search: InputMaybe<Scalars['Unknown']['input']>;
  withoutIds: InputMaybe<Scalars['Unknown']['input']>;
};


export type ProfileTalentEngagementAutocompleteArgs = {
  id: InputMaybe<Scalars['Unknown']['input']>;
};

export type ProfileCompletion = {
  basicInformation: Maybe<Scalars['Unknown']['output']>;
  certificationItemsCount: Maybe<Scalars['Unknown']['output']>;
  educationItemsCount: Maybe<Scalars['Unknown']['output']>;
  employmentItems: Maybe<Scalars['Unknown']['output']>;
  headshot: Maybe<Scalars['Unknown']['output']>;
  overall: Maybe<Scalars['Unknown']['output']>;
  portfolioItems: Maybe<Scalars['Unknown']['output']>;
  skills: Maybe<Scalars['Unknown']['output']>;
  timezone: Maybe<Scalars['Unknown']['output']>;
};

export type ProfileFreshnessRecommendation = {
  certificationsStatus: Maybe<Scalars['Unknown']['output']>;
  educationsStatus: Maybe<Scalars['Unknown']['output']>;
  portfolioItemsStatus: Maybe<Scalars['Unknown']['output']>;
  skillsStatus: Maybe<Scalars['Unknown']['output']>;
  workExperiencesStatus: Maybe<Scalars['Unknown']['output']>;
};

export type ProfileSkillSet = {
  connections: Maybe<Scalars['Unknown']['output']>;
  experience: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  position: Maybe<Scalars['Unknown']['output']>;
  public: Maybe<Scalars['Unknown']['output']>;
  rating: Maybe<Scalars['Unknown']['output']>;
  skill: Maybe<Scalars['Unknown']['output']>;
};

export type Query = {
  activation: Maybe<Scalars['Unknown']['output']>;
  agreement: Maybe<Scalars['Unknown']['output']>;
  agreementAcceptance: Maybe<Scalars['Unknown']['output']>;
  countries: Maybe<Scalars['Unknown']['output']>;
  employersAutocomplete: Maybe<Employer>;
  freelanceTalentAgreement: Maybe<Scalars['Unknown']['output']>;
  industriesAutocomplete: Maybe<Industry>;
  languages: Maybe<Scalars['Unknown']['output']>;
  links: Maybe<Scalars['Unknown']['output']>;
  node: Maybe<IndustryProfile>;
  profile: Maybe<Profile>;
  sectionReviews: Maybe<SectionReview>;
  stepSupportStaff: Maybe<Scalars['Unknown']['output']>;
  supportStaff: Maybe<Scalars['Unknown']['output']>;
  taxForms: Maybe<TaxForm>;
  timeZones: Maybe<Scalars['Unknown']['output']>;
  viewer: Maybe<Scalars['Unknown']['output']>;
};


export type QueryEmployersAutocompleteArgs = {
  limit: Scalars['Int']['input'];
  search: Scalars['String']['input'];
};


export type QueryIndustriesAutocompleteArgs = {
  limit: Scalars['Int']['input'];
  search: Scalars['String']['input'];
  withoutIds: InputMaybe<Array<Scalars['ID']['input']>>;
};


export type QueryNodeArgs = {
  id: Scalars['ID']['input'];
};


export type QueryProfileArgs = {
  id: Scalars['ID']['input'];
};


export type QuerySectionReviewsArgs = {
  id: Scalars['ID']['input'];
};


export type QueryStepSupportStaffArgs = {
  stepId: Scalars['ID']['input'];
};


export type QuerySupportStaffArgs = {
  settingsName: Scalars['SettingName']['input'];
};

export type RemoveCertificationInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type RemoveCertificationPayload = {
  errors: Maybe<UserError>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type RemoveEducationInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type RemoveEducationPayload = {
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type RemoveEmploymentInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type RemoveEmploymentPayload = {
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type RemovePortfolioItemInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type RemovePortfolioItemPayload = {
  profile: Maybe<Profile>;
};

export type RemoveProfileSkillSetConnectionPayload = {
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Scalars['Unknown']['output']>;
  skillSet: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type RemoveProfileSkillSetInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type RemoveProfileSkillSetPayload = {
  errors: Maybe<UserError>;
  profile: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type RemoveTravelVisaInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type RemoveTravelVisaPayload = {
  errors: Maybe<UserError>;
  profile: Maybe<Scalars['Unknown']['output']>;
};

export type RequestTaxFormInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type RequestTaxFormPayload = {
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
  talent: Maybe<Scalars['Unknown']['output']>;
};

export type SectionReview = {
  id: Maybe<Scalars['Unknown']['output']>;
  items: Maybe<Scalars['Unknown']['output']>;
  requestedAt: Maybe<Scalars['Unknown']['output']>;
  section: Maybe<Scalars['Unknown']['output']>;
};

export type SendContractsInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type SendContractsPayload = {
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
  talent: Maybe<Scalars['Unknown']['output']>;
};

export type SkillSetsMissingConnectionsRecommendation = {
  skillSets: Maybe<Scalars['Unknown']['output']>;
};

export type SubmitForReviewInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type SubmitForReviewPayload = {
  activation: Maybe<Activation>;
  errors: Maybe<Scalars['Unknown']['output']>;
  notice: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type Talent = {
  id: Maybe<Scalars['Unknown']['output']>;
  paymentOptions: Maybe<Payoneer>;
};

export type TalentEngagement = {
  clientName: Maybe<Scalars['Unknown']['output']>;
  endDate: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  jobPlainId: Maybe<Scalars['Unknown']['output']>;
  jobTitle: Maybe<Scalars['Unknown']['output']>;
  startDate: Maybe<Scalars['Unknown']['output']>;
  status: Maybe<Scalars['Unknown']['output']>;
};

export type TalentProfileVersion = {
  id: Maybe<Scalars['Unknown']['output']>;
  snapshotText: Maybe<Scalars['Unknown']['output']>;
};

export type TaxForm = {
  description: Maybe<Scalars['Unknown']['output']>;
  formType: Maybe<Scalars['Unknown']['output']>;
  title: Maybe<Scalars['Unknown']['output']>;
};

export type TestimonialEngagementRecommendation = {
  engagements: Maybe<Scalars['Unknown']['output']>;
};

export type ToptalPayments = {
  firstName: Maybe<Scalars['Unknown']['output']>;
  lastName: Maybe<Scalars['Unknown']['output']>;
  phoneNumber: Maybe<Scalars['Unknown']['output']>;
  postalCode: Maybe<Scalars['Unknown']['output']>;
};

export type TravelVisa = {
  country: Maybe<Scalars['Unknown']['output']>;
  expiryDate: Maybe<Scalars['Unknown']['output']>;
  id: Maybe<Scalars['Unknown']['output']>;
  visaType: Maybe<Scalars['Unknown']['output']>;
};

export type UpdateAdvancedProfileWizardStatusInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateAdvancedProfileWizardStatusPayload = {
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UpdateBasicInfoInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateBasicInfoPayload = {
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UpdateCertificationInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateCertificationPayload = {
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UpdateCustomRequirementsInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateCustomRequirementsPayload = {
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UpdateEducationInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateEducationPayload = {
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UpdateEmploymentInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateEmploymentPayload = {
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UpdateExternalProfilesInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateExternalProfilesPayload = {
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UpdateIndustryProfileInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateIndustryProfilePayload = {
  errors: Maybe<UserError>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UpdatePhotoInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdatePhotoPayload = {
  errors: Maybe<UserError>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UpdatePortfolioItemInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdatePortfolioItemPayload = {
  profile: Maybe<Profile>;
};

export type UpdateProfileSkillSetExperienceInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateProfileSkillSetExperiencePayload = {
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  skillSet: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UpdateProfileSkillSetPublicityInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateProfileSkillSetPublicityPayload = {
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  skillSet: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UpdateProfileSkillSetRatingInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateProfileSkillSetRatingPayload = {
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  skillSet: Maybe<Scalars['Unknown']['output']>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UpdateTravelVisaInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateTravelVisaPayload = {
  errors: Maybe<UserError>;
  profile: Maybe<Profile>;
};

export type UpdateWorkingHoursInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UpdateWorkingHoursPayload = {
  errors: Maybe<UserError>;
  notice: Maybe<Scalars['Unknown']['output']>;
  profile: Maybe<Profile>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UploadPortfolioCoverImagePayload = {
  coverImageCacheName: Maybe<Scalars['Unknown']['output']>;
  coverImageUrl: Maybe<Scalars['Unknown']['output']>;
};

export type UploadPortfolioFilePayload = {
  fileCacheName: Maybe<Scalars['Unknown']['output']>;
  fileUrl: Maybe<Scalars['Unknown']['output']>;
};

export type UploadResumeInput = {
  _placeholder: InputMaybe<Scalars['String']['input']>;
};

export type UploadResumePayload = {
  errors: Maybe<UserError>;
  success: Maybe<Scalars['Unknown']['output']>;
};

export type UserError = {
  code: Maybe<Scalars['Unknown']['output']>;
  key: Maybe<Scalars['Unknown']['output']>;
  message: Maybe<Scalars['Unknown']['output']>;
};

export type Verification = {
  id: Maybe<Scalars['Unknown']['output']>;
  link: Maybe<Scalars['Unknown']['output']>;
  status: Maybe<Scalars['Unknown']['output']>;
  updatedAt: Maybe<Scalars['Unknown']['output']>;
};


type Properties<T> = Required<{
  [K in keyof T]: z.ZodType<T[K]>;
}>;

type definedNonNullAny = {};

export const isDefinedNonNullAny = (v: any): v is definedNonNullAny => v !== undefined && v !== null;

export const definedNonNullAnySchema = z.any().refine((v) => isDefinedNonNullAny(v));

export function AcceptAgreementPayloadSchema(): z.ZodObject<Properties<AcceptAgreementPayload>> {
  return z.object({
    __typename: z.literal('AcceptAgreementPayload').optional(),
    activation: z.lazy(() => ActivationSchema().nullable()),
    errors: z.unknown().nullable(),
    notice: z.unknown().nullable(),
    success: z.unknown().nullable()
  })
}

export function AcceptFreelanceTalentAgreementInputSchema(): z.ZodObject<Properties<AcceptFreelanceTalentAgreementInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function AcceptFreelanceTalentAgreementPayloadSchema(): z.ZodObject<Properties<AcceptFreelanceTalentAgreementPayload>> {
  return z.object({
    __typename: z.literal('AcceptFreelanceTalentAgreementPayload').optional(),
    contract: z.lazy(() => ContractSchema().nullable()),
    errors: z.unknown().nullable(),
    notice: z.unknown().nullable(),
    success: z.unknown().nullable()
  })
}

export function AcceptTrainingPayloadSchema(): z.ZodObject<Properties<AcceptTrainingPayload>> {
  return z.object({
    __typename: z.literal('AcceptTrainingPayload').optional(),
    activation: z.lazy(() => ActivationSchema().nullable()),
    errors: z.unknown().nullable(),
    notice: z.unknown().nullable(),
    success: z.unknown().nullable()
  })
}

export function ActivationSchema(): z.ZodObject<Properties<Activation>> {
  return z.object({
    __typename: z.literal('Activation').optional(),
    steps: z.unknown().nullable()
  })
}

export function AddProfileSkillSetConnectionPayloadSchema(): z.ZodObject<Properties<AddProfileSkillSetConnectionPayload>> {
  return z.object({
    __typename: z.literal('AddProfileSkillSetConnectionPayload').optional(),
    profile: z.unknown().nullable(),
    skillSet: z.unknown().nullable()
  })
}

export function AddProfileSkillSetInputSchema(): z.ZodObject<Properties<AddProfileSkillSetInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function AddProfileSkillSetPayloadSchema(): z.ZodObject<Properties<AddProfileSkillSetPayload>> {
  return z.object({
    __typename: z.literal('AddProfileSkillSetPayload').optional(),
    profile: z.lazy(() => ProfileSchema().nullable()),
    skillSet: z.lazy(() => ProfileSkillSetSchema().nullable())
  })
}

export function AdvancedProfileRecommendationSchema(): z.ZodObject<Properties<AdvancedProfileRecommendation>> {
  return z.object({
    __typename: z.literal('AdvancedProfileRecommendation').optional(),
    isCustomRequirementsCompleted: z.unknown().nullable(),
    isTravelInformationCompleted: z.unknown().nullable()
  })
}

export function ApproveItemReviewInputSchema(): z.ZodObject<Properties<ApproveItemReviewInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function ApproveItemReviewPayloadSchema(): z.ZodObject<Properties<ApproveItemReviewPayload>> {
  return z.object({
    __typename: z.literal('ApproveItemReviewPayload').optional(),
    sectionReviews: z.lazy(() => SectionReviewSchema().nullable())
  })
}

export function ApproveSectionReviewInputSchema(): z.ZodObject<Properties<ApproveSectionReviewInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function ApproveSectionReviewPayloadSchema(): z.ZodObject<Properties<ApproveSectionReviewPayload>> {
  return z.object({
    __typename: z.literal('ApproveSectionReviewPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    sectionReviews: z.lazy(() => SectionReviewSchema().nullable()),
    success: z.unknown().nullable()
  })
}

export function CancelResumeUploadInputSchema(): z.ZodObject<Properties<CancelResumeUploadInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function CancelResumeUploadPayloadSchema(): z.ZodObject<Properties<CancelResumeUploadPayload>> {
  return z.object({
    __typename: z.literal('CancelResumeUploadPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    success: z.unknown().nullable()
  })
}

export function CertificationSchema(): z.ZodObject<Properties<Certification>> {
  return z.object({
    __typename: z.literal('Certification').optional(),
    certificate: z.unknown().nullable(),
    highlight: z.unknown().nullable(),
    id: z.unknown().nullable(),
    institution: z.unknown().nullable(),
    link: z.unknown().nullable(),
    number: z.unknown().nullable(),
    skills: z.unknown().nullable(),
    status: z.unknown().nullable(),
    validFromMonth: z.unknown().nullable(),
    validFromYear: z.unknown().nullable(),
    validToMonth: z.unknown().nullable(),
    validToYear: z.unknown().nullable()
  })
}

export function ChangePortfolioItemPositionInputSchema(): z.ZodObject<Properties<ChangePortfolioItemPositionInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function ChangePortfolioItemPositionPayloadSchema(): z.ZodObject<Properties<ChangePortfolioItemPositionPayload>> {
  return z.object({
    __typename: z.literal('ChangePortfolioItemPositionPayload').optional(),
    profile: z.lazy(() => ProfileSchema().nullable())
  })
}

export function ContractSchema(): z.ZodObject<Properties<Contract>> {
  return z.object({
    __typename: z.literal('Contract').optional(),
    billingType: z.unknown().nullable(),
    id: z.unknown().nullable(),
    isActive: z.unknown().nullable(),
    kind: z.unknown().nullable(),
    provider: z.unknown().nullable(),
    sentAt: z.unknown().nullable(),
    signedAt: z.unknown().nullable(),
    status: z.unknown().nullable(),
    title: z.unknown().nullable(),
    verificationDeadline: z.unknown().nullable()
  })
}

export function CreateCertificationInputSchema(): z.ZodObject<Properties<CreateCertificationInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function CreateCertificationPayloadSchema(): z.ZodObject<Properties<CreateCertificationPayload>> {
  return z.object({
    __typename: z.literal('CreateCertificationPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    profile: z.lazy(() => ProfileSchema().nullable()),
    success: z.unknown().nullable()
  })
}

export function CreateEducationInputSchema(): z.ZodObject<Properties<CreateEducationInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function CreateEducationPayloadSchema(): z.ZodObject<Properties<CreateEducationPayload>> {
  return z.object({
    __typename: z.literal('CreateEducationPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    profile: z.lazy(() => ProfileSchema().nullable()),
    success: z.unknown().nullable()
  })
}

export function CreateEmploymentInputSchema(): z.ZodObject<Properties<CreateEmploymentInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function CreateEmploymentPayloadSchema(): z.ZodObject<Properties<CreateEmploymentPayload>> {
  return z.object({
    __typename: z.literal('CreateEmploymentPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    profile: z.lazy(() => ProfileSchema().nullable()),
    success: z.unknown().nullable()
  })
}

export function CreateEngagementTestimonialInputSchema(): z.ZodObject<Properties<CreateEngagementTestimonialInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function CreateEngagementTestimonialPayloadSchema(): z.ZodObject<Properties<CreateEngagementTestimonialPayload>> {
  return z.object({
    __typename: z.literal('CreateEngagementTestimonialPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    success: z.unknown().nullable()
  })
}

export function CreateIndustryProfileInputSchema(): z.ZodObject<Properties<CreateIndustryProfileInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function CreateIndustryProfilePayloadSchema(): z.ZodObject<Properties<CreateIndustryProfilePayload>> {
  return z.object({
    __typename: z.literal('CreateIndustryProfilePayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    success: z.unknown().nullable()
  })
}

export function CreatePayoneerPaymentOptionInputSchema(): z.ZodObject<Properties<CreatePayoneerPaymentOptionInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function CreatePayoneerPaymentOptionPayloadSchema(): z.ZodObject<Properties<CreatePayoneerPaymentOptionPayload>> {
  return z.object({
    __typename: z.literal('CreatePayoneerPaymentOptionPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    success: z.unknown().nullable(),
    talent: z.lazy(() => TalentSchema().nullable())
  })
}

export function CreatePortfolioItemInputSchema(): z.ZodObject<Properties<CreatePortfolioItemInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function CreatePortfolioItemPayloadSchema(): z.ZodObject<Properties<CreatePortfolioItemPayload>> {
  return z.object({
    __typename: z.literal('CreatePortfolioItemPayload').optional(),
    profile: z.lazy(() => ProfileSchema().nullable())
  })
}

export function CreateToptalPaymentAccountInputSchema(): z.ZodObject<Properties<CreateToptalPaymentAccountInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function CreateToptalPaymentAccountPayloadSchema(): z.ZodObject<Properties<CreateToptalPaymentAccountPayload>> {
  return z.object({
    __typename: z.literal('CreateToptalPaymentAccountPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    success: z.unknown().nullable(),
    talent: z.lazy(() => TalentSchema().nullable())
  })
}

export function CreateTravelVisaInputSchema(): z.ZodObject<Properties<CreateTravelVisaInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function CreateTravelVisaPayloadSchema(): z.ZodObject<Properties<CreateTravelVisaPayload>> {
  return z.object({
    __typename: z.literal('CreateTravelVisaPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    profile: z.unknown().nullable()
  })
}

export function CustomRequirementsSchema(): z.ZodObject<Properties<CustomRequirements>> {
  return z.object({
    __typename: z.literal('CustomRequirements').optional(),
    backgroundCheck: z.unknown().nullable(),
    drugTest: z.unknown().nullable(),
    timeTrackingTools: z.unknown().nullable()
  })
}

export function DismissTestimonialNotificationInputSchema(): z.ZodObject<Properties<DismissTestimonialNotificationInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function DismissTestimonialNotificationPayloadSchema(): z.ZodObject<Properties<DismissTestimonialNotificationPayload>> {
  return z.object({
    __typename: z.literal('DismissTestimonialNotificationPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    success: z.unknown().nullable()
  })
}

export function EducationSchema(): z.ZodObject<Properties<Education>> {
  return z.object({
    __typename: z.literal('Education').optional(),
    degree: z.unknown().nullable(),
    fieldOfStudy: z.unknown().nullable(),
    highlight: z.unknown().nullable(),
    id: z.unknown().nullable(),
    institution: z.unknown().nullable(),
    location: z.unknown().nullable(),
    skills: z.unknown().nullable(),
    title: z.unknown().nullable(),
    yearFrom: z.unknown().nullable(),
    yearTo: z.unknown().nullable()
  })
}

export function EmployerSchema(): z.ZodObject<Properties<Employer>> {
  return z.object({
    __typename: z.literal('Employer').optional(),
    city: z.unknown().nullable(),
    country: z.unknown().nullable(),
    employeeCount: z.unknown().nullable(),
    id: z.unknown().nullable(),
    industries: z.unknown().nullable(),
    lastSyncedAt: z.unknown().nullable(),
    logoUrl: z.unknown().nullable(),
    name: z.unknown().nullable(),
    otherNames: z.unknown().nullable(),
    otherUrls: z.unknown().nullable(),
    revenue: z.unknown().nullable(),
    website: z.unknown().nullable()
  })
}

export function EmploymentSchema(): z.ZodObject<Properties<Employment>> {
  return z.object({
    __typename: z.literal('Employment').optional(),
    company: z.unknown().nullable(),
    companyWebsite: z.unknown().nullable(),
    employer: z.lazy(() => EmployerSchema().nullable()),
    endDate: z.unknown().nullable(),
    engagement: z.unknown().nullable(),
    experienceItems: z.unknown().nullable(),
    highlight: z.unknown().nullable(),
    id: z.unknown().nullable(),
    industries: z.unknown().nullable(),
    isEnterpriseExperience: z.unknown().nullable(),
    managementExperience: z.unknown().nullable(),
    noWebsite: z.unknown().nullable(),
    position: z.unknown().nullable(),
    primaryGeography: z.unknown().nullable(),
    publicationPermit: z.unknown().nullable(),
    reportingTo: z.unknown().nullable(),
    showViaToptal: z.unknown().nullable(),
    skills: z.unknown().nullable(),
    startDate: z.unknown().nullable(),
    toptalRelated: z.unknown().nullable()
  })
}

export function EmploymentsCountRecommendationSchema(): z.ZodObject<Properties<EmploymentsCountRecommendation>> {
  return z.object({
    __typename: z.literal('EmploymentsCountRecommendation').optional(),
    minimumCount: z.unknown().nullable(),
    type: z.unknown().nullable()
  })
}

export function EmploymentsMissingDataRecommendationSchema(): z.ZodObject<Properties<EmploymentsMissingDataRecommendation>> {
  return z.object({
    __typename: z.literal('EmploymentsMissingDataRecommendation').optional(),
    employments: z.unknown().nullable()
  })
}

export function HighlightCertificationPayloadSchema(): z.ZodObject<Properties<HighlightCertificationPayload>> {
  return z.object({
    __typename: z.literal('HighlightCertificationPayload').optional(),
    certification: z.unknown().nullable(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    success: z.unknown().nullable()
  })
}

export function HighlightEducationPayloadSchema(): z.ZodObject<Properties<HighlightEducationPayload>> {
  return z.object({
    __typename: z.literal('HighlightEducationPayload').optional(),
    education: z.unknown().nullable(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    success: z.unknown().nullable()
  })
}

export function HighlightEmploymentPayloadSchema(): z.ZodObject<Properties<HighlightEmploymentPayload>> {
  return z.object({
    __typename: z.literal('HighlightEmploymentPayload').optional(),
    employment: z.unknown().nullable(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    success: z.unknown().nullable()
  })
}

export function HighlightPortfolioItemPayloadSchema(): z.ZodObject<Properties<HighlightPortfolioItemPayload>> {
  return z.object({
    __typename: z.literal('HighlightPortfolioItemPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    portfolioItem: z.unknown().nullable(),
    success: z.unknown().nullable()
  })
}

export function IndustrySchema(): z.ZodObject<Properties<Industry>> {
  return z.object({
    __typename: z.literal('Industry').optional(),
    id: z.unknown().nullable(),
    name: z.unknown().nullable()
  })
}

export function IndustryProfileSchema(): z.ZodObject<Properties<IndustryProfile>> {
  return z.object({
    __typename: z.literal('IndustryProfile').optional(),
    about: z.unknown().nullable(),
    certifications: z.unknown().nullable(),
    domainArea: z.unknown().nullable(),
    educations: z.unknown().nullable(),
    employments: z.unknown().nullable(),
    highlights: z.unknown().nullable(),
    id: z.unknown().nullable(),
    portfolioItems: z.unknown().nullable(),
    title: z.unknown().nullable()
  })
}

export function LogOutInputSchema(): z.ZodObject<Properties<LogOutInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function LogOutPayloadSchema(): z.ZodObject<Properties<LogOutPayload>> {
  return z.object({
    __typename: z.literal('LogOutPayload').optional(),
    errors: z.unknown().nullable(),
    notice: z.unknown().nullable(),
    returnTo: z.unknown().nullable(),
    success: z.unknown().nullable()
  })
}

export function MutationResultSchema(): z.ZodObject<Properties<MutationResult>> {
  return z.object({
    __typename: z.literal('MutationResult').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    success: z.unknown().nullable()
  })
}

export function NodeSchema(): z.ZodObject<Properties<Node>> {
  return z.object({
    __typename: z.literal('Node').optional(),
    id: z.unknown().nullable()
  })
}

export function PayoneerSchema(): z.ZodObject<Properties<Payoneer>> {
  return z.object({
    __typename: z.literal('Payoneer').optional(),
    canLeave: z.unknown().nullable(),
    comment: z.unknown().nullable(),
    id: z.unknown().nullable(),
    isSelected: z.unknown().nullable(),
    nameOnAccount: z.unknown().nullable(),
    paymentMethod: z.unknown().nullable(),
    payoneerId: z.unknown().nullable(),
    status: z.unknown().nullable()
  })
}

export function PortfolioCoverImageTransformationInputSchema(): z.ZodObject<Properties<PortfolioCoverImageTransformationInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function PortfolioItemSchema(): z.ZodObject<Properties<PortfolioItem>> {
  return z.object({
    __typename: z.literal('PortfolioItem').optional(),
    accomplishment: z.unknown().nullable(),
    clientOrCompanyLogoUrl: z.unknown().nullable(),
    clientOrCompanyName: z.unknown().nullable(),
    coverImage: z.unknown().nullable(),
    description: z.unknown().nullable(),
    details: z.lazy(() => PortfolioItemImageBlockSchema().nullable()),
    engagement: z.unknown().nullable(),
    files: z.lazy(() => PortfolioItemFileConnectionSchema().nullable()),
    highlight: z.unknown().nullable(),
    id: z.unknown().nullable(),
    industries: z.unknown().nullable(),
    kpis: z.unknown().nullable(),
    link: z.unknown().nullable(),
    publicationPermit: z.unknown().nullable(),
    quotes: z.unknown().nullable(),
    showViaToptal: z.unknown().nullable(),
    skills: z.unknown().nullable(),
    title: z.unknown().nullable(),
    toptalRelated: z.unknown().nullable(),
    websiteUrl: z.unknown().nullable()
  })
}

export function PortfolioItemFileSchema(): z.ZodObject<Properties<PortfolioItemFile>> {
  return z.object({
    __typename: z.literal('PortfolioItemFile').optional(),
    contentType: z.unknown().nullable(),
    description: z.unknown().nullable(),
    title: z.unknown().nullable()
  })
}

export function PortfolioItemFileConnectionSchema(): z.ZodObject<Properties<PortfolioItemFileConnection>> {
  return z.object({
    __typename: z.literal('PortfolioItemFileConnection').optional(),
    nodes: z.lazy(() => PortfolioItemFilePdfSchema().nullable())
  })
}

export function PortfolioItemFileImageSchema(): z.ZodObject<Properties<PortfolioItemFileImage>> {
  return z.object({
    __typename: z.literal('PortfolioItemFileImage').optional(),
    id: z.unknown().nullable(),
    image: z.lazy(() => PortfolioItemFileImageContentSchema().nullable())
  })
}

export function PortfolioItemFileImageContentSchema(): z.ZodObject<Properties<PortfolioItemFileImageContent>> {
  return z.object({
    __typename: z.literal('PortfolioItemFileImageContent').optional(),
    optimizedUrl: z.unknown().nullable(),
    thumbUrl: z.unknown().nullable()
  })
}

export function PortfolioItemFilePdfSchema(): z.ZodObject<Properties<PortfolioItemFilePdf>> {
  return z.object({
    __typename: z.literal('PortfolioItemFilePdf').optional(),
    fileUrl: z.unknown().nullable(),
    id: z.unknown().nullable(),
    primaryContentType: z.unknown().nullable()
  })
}

export function PortfolioItemGalleryBlockSchema(): z.ZodObject<Properties<PortfolioItemGalleryBlock>> {
  return z.object({
    __typename: z.literal('PortfolioItemGalleryBlock').optional(),
    id: z.unknown().nullable(),
    items: z.unknown().nullable(),
    title: z.unknown().nullable()
  })
}

export function PortfolioItemImageBlockSchema(): z.ZodObject<Properties<PortfolioItemImageBlock>> {
  return z.object({
    __typename: z.literal('PortfolioItemImageBlock').optional(),
    id: z.unknown().nullable(),
    image: z.unknown().nullable(),
    title: z.unknown().nullable()
  })
}

export function PortfolioItemTextBlockSchema(): z.ZodObject<Properties<PortfolioItemTextBlock>> {
  return z.object({
    __typename: z.literal('PortfolioItemTextBlock').optional(),
    contentHast: z.unknown().nullable(),
    id: z.unknown().nullable(),
    title: z.unknown().nullable()
  })
}

export function PortfolioItemVideoBlockSchema(): z.ZodObject<Properties<PortfolioItemVideoBlock>> {
  return z.object({
    __typename: z.literal('PortfolioItemVideoBlock').optional(),
    id: z.unknown().nullable(),
    title: z.unknown().nullable(),
    videoUrl: z.unknown().nullable()
  })
}

export function PortfolioItemsCountRecommendationSchema(): z.ZodObject<Properties<PortfolioItemsCountRecommendation>> {
  return z.object({
    __typename: z.literal('PortfolioItemsCountRecommendation').optional(),
    minimumCount: z.unknown().nullable()
  })
}

export function PortfolioItemsMissingIndustryRecommendationSchema(): z.ZodObject<Properties<PortfolioItemsMissingIndustryRecommendation>> {
  return z.object({
    __typename: z.literal('PortfolioItemsMissingIndustryRecommendation').optional(),
    portfolioItems: z.unknown().nullable()
  })
}

export function ProfileSchema(): z.ZodObject<Properties<Profile>> {
  return z.object({
    __typename: z.literal('Profile').optional(),
    about: z.unknown().nullable(),
    advancedProfileWizardStatus: z.unknown().nullable(),
    availableShiftRangeFrom: z.unknown().nullable(),
    availableShiftRangeTo: z.unknown().nullable(),
    basicInfoIndustries: z.unknown().nullable(),
    behance: z.unknown().nullable(),
    certifications: z.unknown().nullable(),
    citizenship: z.unknown().nullable(),
    city: z.unknown().nullable(),
    country: z.unknown().nullable(),
    customRequirements: z.lazy(() => CustomRequirementsSchema().nullable()),
    dribbble: z.unknown().nullable(),
    educations: z.unknown().nullable(),
    employments: z.unknown().nullable(),
    engagements: z.unknown().nullable(),
    expectedEmploymentItems: z.unknown().nullable(),
    experiments: z.unknown().nullable(),
    fullName: z.unknown().nullable(),
    github: z.unknown().nullable(),
    id: z.unknown().nullable(),
    jsonapiId: z.unknown().nullable(),
    languages: z.unknown().nullable(),
    legalName: z.unknown().nullable(),
    linkedin: z.unknown().nullable(),
    links: z.unknown().nullable(),
    phoneNumber: z.unknown().nullable(),
    photo: z.unknown().nullable(),
    placeIdentity: z.unknown().nullable(),
    portfolioItems: z.unknown().nullable(),
    prefillStatusEnum: z.unknown().nullable(),
    profileCompletion: z.lazy(() => ProfileCompletionSchema().nullable()),
    profileReadiness: z.unknown().nullable(),
    quote: z.unknown().nullable(),
    recommendations: z.unknown().nullable(),
    reportingToAutocomplete: z.unknown().nullable(),
    roleType: z.unknown().nullable(),
    skillSets: z.unknown().nullable(),
    skillsAutocomplete: z.unknown().nullable(),
    skillsReadiness: z.unknown().nullable(),
    skype: z.unknown().nullable(),
    softwareSkills: z.unknown().nullable(),
    submitAvailable: z.unknown().nullable(),
    talent: z.unknown().nullable(),
    talentEngagementAutocomplete: z.unknown().nullable(),
    timeZone: z.unknown().nullable(),
    toptalYearsOfExperience: z.unknown().nullable(),
    travelVisas: z.unknown().nullable(),
    twitter: z.unknown().nullable(),
    updatedByTalentAt: z.unknown().nullable(),
    versions: z.unknown().nullable(),
    vertical: z.unknown().nullable(),
    website: z.unknown().nullable(),
    workingTimeFrom: z.unknown().nullable(),
    workingTimeTo: z.unknown().nullable()
  })
}

export function ProfileReportingToAutocompleteArgsSchema(): z.ZodObject<Properties<ProfileReportingToAutocompleteArgs>> {
  return z.object({
    limit: z.unknown().nullable(),
    name: z.unknown().nullable()
  })
}

export function ProfileSkillsAutocompleteArgsSchema(): z.ZodObject<Properties<ProfileSkillsAutocompleteArgs>> {
  return z.object({
    limit: z.unknown().nullable(),
    search: z.unknown().nullable(),
    withoutIds: z.unknown().nullable()
  })
}

export function ProfileTalentEngagementAutocompleteArgsSchema(): z.ZodObject<Properties<ProfileTalentEngagementAutocompleteArgs>> {
  return z.object({
    id: z.unknown().nullable()
  })
}

export function ProfileCompletionSchema(): z.ZodObject<Properties<ProfileCompletion>> {
  return z.object({
    __typename: z.literal('ProfileCompletion').optional(),
    basicInformation: z.unknown().nullable(),
    certificationItemsCount: z.unknown().nullable(),
    educationItemsCount: z.unknown().nullable(),
    employmentItems: z.unknown().nullable(),
    headshot: z.unknown().nullable(),
    overall: z.unknown().nullable(),
    portfolioItems: z.unknown().nullable(),
    skills: z.unknown().nullable(),
    timezone: z.unknown().nullable()
  })
}

export function ProfileFreshnessRecommendationSchema(): z.ZodObject<Properties<ProfileFreshnessRecommendation>> {
  return z.object({
    __typename: z.literal('ProfileFreshnessRecommendation').optional(),
    certificationsStatus: z.unknown().nullable(),
    educationsStatus: z.unknown().nullable(),
    portfolioItemsStatus: z.unknown().nullable(),
    skillsStatus: z.unknown().nullable(),
    workExperiencesStatus: z.unknown().nullable()
  })
}

export function ProfileSkillSetSchema(): z.ZodObject<Properties<ProfileSkillSet>> {
  return z.object({
    __typename: z.literal('ProfileSkillSet').optional(),
    connections: z.unknown().nullable(),
    experience: z.unknown().nullable(),
    id: z.unknown().nullable(),
    position: z.unknown().nullable(),
    public: z.unknown().nullable(),
    rating: z.unknown().nullable(),
    skill: z.unknown().nullable()
  })
}

export function RemoveCertificationInputSchema(): z.ZodObject<Properties<RemoveCertificationInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function RemoveCertificationPayloadSchema(): z.ZodObject<Properties<RemoveCertificationPayload>> {
  return z.object({
    __typename: z.literal('RemoveCertificationPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    profile: z.lazy(() => ProfileSchema().nullable()),
    success: z.unknown().nullable()
  })
}

export function RemoveEducationInputSchema(): z.ZodObject<Properties<RemoveEducationInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function RemoveEducationPayloadSchema(): z.ZodObject<Properties<RemoveEducationPayload>> {
  return z.object({
    __typename: z.literal('RemoveEducationPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    profile: z.lazy(() => ProfileSchema().nullable()),
    success: z.unknown().nullable()
  })
}

export function RemoveEmploymentInputSchema(): z.ZodObject<Properties<RemoveEmploymentInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function RemoveEmploymentPayloadSchema(): z.ZodObject<Properties<RemoveEmploymentPayload>> {
  return z.object({
    __typename: z.literal('RemoveEmploymentPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    profile: z.lazy(() => ProfileSchema().nullable()),
    success: z.unknown().nullable()
  })
}

export function RemovePortfolioItemInputSchema(): z.ZodObject<Properties<RemovePortfolioItemInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function RemovePortfolioItemPayloadSchema(): z.ZodObject<Properties<RemovePortfolioItemPayload>> {
  return z.object({
    __typename: z.literal('RemovePortfolioItemPayload').optional(),
    profile: z.lazy(() => ProfileSchema().nullable())
  })
}

export function RemoveProfileSkillSetConnectionPayloadSchema(): z.ZodObject<Properties<RemoveProfileSkillSetConnectionPayload>> {
  return z.object({
    __typename: z.literal('RemoveProfileSkillSetConnectionPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    profile: z.unknown().nullable(),
    skillSet: z.unknown().nullable(),
    success: z.unknown().nullable()
  })
}

export function RemoveProfileSkillSetInputSchema(): z.ZodObject<Properties<RemoveProfileSkillSetInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function RemoveProfileSkillSetPayloadSchema(): z.ZodObject<Properties<RemoveProfileSkillSetPayload>> {
  return z.object({
    __typename: z.literal('RemoveProfileSkillSetPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    profile: z.unknown().nullable(),
    success: z.unknown().nullable()
  })
}

export function RemoveTravelVisaInputSchema(): z.ZodObject<Properties<RemoveTravelVisaInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function RemoveTravelVisaPayloadSchema(): z.ZodObject<Properties<RemoveTravelVisaPayload>> {
  return z.object({
    __typename: z.literal('RemoveTravelVisaPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    profile: z.unknown().nullable()
  })
}

export function RequestTaxFormInputSchema(): z.ZodObject<Properties<RequestTaxFormInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function RequestTaxFormPayloadSchema(): z.ZodObject<Properties<RequestTaxFormPayload>> {
  return z.object({
    __typename: z.literal('RequestTaxFormPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    success: z.unknown().nullable(),
    talent: z.unknown().nullable()
  })
}

export function SectionReviewSchema(): z.ZodObject<Properties<SectionReview>> {
  return z.object({
    __typename: z.literal('SectionReview').optional(),
    id: z.unknown().nullable(),
    items: z.unknown().nullable(),
    requestedAt: z.unknown().nullable(),
    section: z.unknown().nullable()
  })
}

export function SendContractsInputSchema(): z.ZodObject<Properties<SendContractsInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function SendContractsPayloadSchema(): z.ZodObject<Properties<SendContractsPayload>> {
  return z.object({
    __typename: z.literal('SendContractsPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    success: z.unknown().nullable(),
    talent: z.unknown().nullable()
  })
}

export function SkillSetsMissingConnectionsRecommendationSchema(): z.ZodObject<Properties<SkillSetsMissingConnectionsRecommendation>> {
  return z.object({
    __typename: z.literal('SkillSetsMissingConnectionsRecommendation').optional(),
    skillSets: z.unknown().nullable()
  })
}

export function SubmitForReviewInputSchema(): z.ZodObject<Properties<SubmitForReviewInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function SubmitForReviewPayloadSchema(): z.ZodObject<Properties<SubmitForReviewPayload>> {
  return z.object({
    __typename: z.literal('SubmitForReviewPayload').optional(),
    activation: z.lazy(() => ActivationSchema().nullable()),
    errors: z.unknown().nullable(),
    notice: z.unknown().nullable(),
    success: z.unknown().nullable()
  })
}

export function TalentSchema(): z.ZodObject<Properties<Talent>> {
  return z.object({
    __typename: z.literal('Talent').optional(),
    id: z.unknown().nullable(),
    paymentOptions: z.lazy(() => PayoneerSchema().nullable())
  })
}

export function TalentEngagementSchema(): z.ZodObject<Properties<TalentEngagement>> {
  return z.object({
    __typename: z.literal('TalentEngagement').optional(),
    clientName: z.unknown().nullable(),
    endDate: z.unknown().nullable(),
    id: z.unknown().nullable(),
    jobPlainId: z.unknown().nullable(),
    jobTitle: z.unknown().nullable(),
    startDate: z.unknown().nullable(),
    status: z.unknown().nullable()
  })
}

export function TalentProfileVersionSchema(): z.ZodObject<Properties<TalentProfileVersion>> {
  return z.object({
    __typename: z.literal('TalentProfileVersion').optional(),
    id: z.unknown().nullable(),
    snapshotText: z.unknown().nullable()
  })
}

export function TaxFormSchema(): z.ZodObject<Properties<TaxForm>> {
  return z.object({
    __typename: z.literal('TaxForm').optional(),
    description: z.unknown().nullable(),
    formType: z.unknown().nullable(),
    title: z.unknown().nullable()
  })
}

export function TestimonialEngagementRecommendationSchema(): z.ZodObject<Properties<TestimonialEngagementRecommendation>> {
  return z.object({
    __typename: z.literal('TestimonialEngagementRecommendation').optional(),
    engagements: z.unknown().nullable()
  })
}

export function ToptalPaymentsSchema(): z.ZodObject<Properties<ToptalPayments>> {
  return z.object({
    __typename: z.literal('ToptalPayments').optional(),
    firstName: z.unknown().nullable(),
    lastName: z.unknown().nullable(),
    phoneNumber: z.unknown().nullable(),
    postalCode: z.unknown().nullable()
  })
}

export function TravelVisaSchema(): z.ZodObject<Properties<TravelVisa>> {
  return z.object({
    __typename: z.literal('TravelVisa').optional(),
    country: z.unknown().nullable(),
    expiryDate: z.unknown().nullable(),
    id: z.unknown().nullable(),
    visaType: z.unknown().nullable()
  })
}

export function UpdateAdvancedProfileWizardStatusInputSchema(): z.ZodObject<Properties<UpdateAdvancedProfileWizardStatusInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function UpdateAdvancedProfileWizardStatusPayloadSchema(): z.ZodObject<Properties<UpdateAdvancedProfileWizardStatusPayload>> {
  return z.object({
    __typename: z.literal('UpdateAdvancedProfileWizardStatusPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    profile: z.lazy(() => ProfileSchema().nullable()),
    success: z.unknown().nullable()
  })
}

export function UpdateBasicInfoInputSchema(): z.ZodObject<Properties<UpdateBasicInfoInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function UpdateBasicInfoPayloadSchema(): z.ZodObject<Properties<UpdateBasicInfoPayload>> {
  return z.object({
    __typename: z.literal('UpdateBasicInfoPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    profile: z.lazy(() => ProfileSchema().nullable()),
    success: z.unknown().nullable()
  })
}

export function UpdateCertificationInputSchema(): z.ZodObject<Properties<UpdateCertificationInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function UpdateCertificationPayloadSchema(): z.ZodObject<Properties<UpdateCertificationPayload>> {
  return z.object({
    __typename: z.literal('UpdateCertificationPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    profile: z.lazy(() => ProfileSchema().nullable()),
    success: z.unknown().nullable()
  })
}

export function UpdateCustomRequirementsInputSchema(): z.ZodObject<Properties<UpdateCustomRequirementsInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function UpdateCustomRequirementsPayloadSchema(): z.ZodObject<Properties<UpdateCustomRequirementsPayload>> {
  return z.object({
    __typename: z.literal('UpdateCustomRequirementsPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    profile: z.lazy(() => ProfileSchema().nullable()),
    success: z.unknown().nullable()
  })
}

export function UpdateEducationInputSchema(): z.ZodObject<Properties<UpdateEducationInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function UpdateEducationPayloadSchema(): z.ZodObject<Properties<UpdateEducationPayload>> {
  return z.object({
    __typename: z.literal('UpdateEducationPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    profile: z.lazy(() => ProfileSchema().nullable()),
    success: z.unknown().nullable()
  })
}

export function UpdateEmploymentInputSchema(): z.ZodObject<Properties<UpdateEmploymentInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function UpdateEmploymentPayloadSchema(): z.ZodObject<Properties<UpdateEmploymentPayload>> {
  return z.object({
    __typename: z.literal('UpdateEmploymentPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    profile: z.lazy(() => ProfileSchema().nullable()),
    success: z.unknown().nullable()
  })
}

export function UpdateExternalProfilesInputSchema(): z.ZodObject<Properties<UpdateExternalProfilesInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function UpdateExternalProfilesPayloadSchema(): z.ZodObject<Properties<UpdateExternalProfilesPayload>> {
  return z.object({
    __typename: z.literal('UpdateExternalProfilesPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    profile: z.lazy(() => ProfileSchema().nullable()),
    success: z.unknown().nullable()
  })
}

export function UpdateIndustryProfileInputSchema(): z.ZodObject<Properties<UpdateIndustryProfileInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function UpdateIndustryProfilePayloadSchema(): z.ZodObject<Properties<UpdateIndustryProfilePayload>> {
  return z.object({
    __typename: z.literal('UpdateIndustryProfilePayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    success: z.unknown().nullable()
  })
}

export function UpdatePhotoInputSchema(): z.ZodObject<Properties<UpdatePhotoInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function UpdatePhotoPayloadSchema(): z.ZodObject<Properties<UpdatePhotoPayload>> {
  return z.object({
    __typename: z.literal('UpdatePhotoPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    profile: z.lazy(() => ProfileSchema().nullable()),
    success: z.unknown().nullable()
  })
}

export function UpdatePortfolioItemInputSchema(): z.ZodObject<Properties<UpdatePortfolioItemInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function UpdatePortfolioItemPayloadSchema(): z.ZodObject<Properties<UpdatePortfolioItemPayload>> {
  return z.object({
    __typename: z.literal('UpdatePortfolioItemPayload').optional(),
    profile: z.lazy(() => ProfileSchema().nullable())
  })
}

export function UpdateProfileSkillSetExperienceInputSchema(): z.ZodObject<Properties<UpdateProfileSkillSetExperienceInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function UpdateProfileSkillSetExperiencePayloadSchema(): z.ZodObject<Properties<UpdateProfileSkillSetExperiencePayload>> {
  return z.object({
    __typename: z.literal('UpdateProfileSkillSetExperiencePayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    profile: z.lazy(() => ProfileSchema().nullable()),
    skillSet: z.unknown().nullable(),
    success: z.unknown().nullable()
  })
}

export function UpdateProfileSkillSetPublicityInputSchema(): z.ZodObject<Properties<UpdateProfileSkillSetPublicityInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function UpdateProfileSkillSetPublicityPayloadSchema(): z.ZodObject<Properties<UpdateProfileSkillSetPublicityPayload>> {
  return z.object({
    __typename: z.literal('UpdateProfileSkillSetPublicityPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    profile: z.lazy(() => ProfileSchema().nullable()),
    skillSet: z.unknown().nullable(),
    success: z.unknown().nullable()
  })
}

export function UpdateProfileSkillSetRatingInputSchema(): z.ZodObject<Properties<UpdateProfileSkillSetRatingInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function UpdateProfileSkillSetRatingPayloadSchema(): z.ZodObject<Properties<UpdateProfileSkillSetRatingPayload>> {
  return z.object({
    __typename: z.literal('UpdateProfileSkillSetRatingPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    profile: z.lazy(() => ProfileSchema().nullable()),
    skillSet: z.unknown().nullable(),
    success: z.unknown().nullable()
  })
}

export function UpdateTravelVisaInputSchema(): z.ZodObject<Properties<UpdateTravelVisaInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function UpdateTravelVisaPayloadSchema(): z.ZodObject<Properties<UpdateTravelVisaPayload>> {
  return z.object({
    __typename: z.literal('UpdateTravelVisaPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    profile: z.lazy(() => ProfileSchema().nullable())
  })
}

export function UpdateWorkingHoursInputSchema(): z.ZodObject<Properties<UpdateWorkingHoursInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function UpdateWorkingHoursPayloadSchema(): z.ZodObject<Properties<UpdateWorkingHoursPayload>> {
  return z.object({
    __typename: z.literal('UpdateWorkingHoursPayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    notice: z.unknown().nullable(),
    profile: z.lazy(() => ProfileSchema().nullable()),
    success: z.unknown().nullable()
  })
}

export function UploadPortfolioCoverImagePayloadSchema(): z.ZodObject<Properties<UploadPortfolioCoverImagePayload>> {
  return z.object({
    __typename: z.literal('UploadPortfolioCoverImagePayload').optional(),
    coverImageCacheName: z.unknown().nullable(),
    coverImageUrl: z.unknown().nullable()
  })
}

export function UploadPortfolioFilePayloadSchema(): z.ZodObject<Properties<UploadPortfolioFilePayload>> {
  return z.object({
    __typename: z.literal('UploadPortfolioFilePayload').optional(),
    fileCacheName: z.unknown().nullable(),
    fileUrl: z.unknown().nullable()
  })
}

export function UploadResumeInputSchema(): z.ZodObject<Properties<UploadResumeInput>> {
  return z.object({
    _placeholder: z.string().nullable()
  })
}

export function UploadResumePayloadSchema(): z.ZodObject<Properties<UploadResumePayload>> {
  return z.object({
    __typename: z.literal('UploadResumePayload').optional(),
    errors: z.lazy(() => UserErrorSchema().nullable()),
    success: z.unknown().nullable()
  })
}

export function UserErrorSchema(): z.ZodObject<Properties<UserError>> {
  return z.object({
    __typename: z.literal('UserError').optional(),
    code: z.unknown().nullable(),
    key: z.unknown().nullable(),
    message: z.unknown().nullable()
  })
}

export function VerificationSchema(): z.ZodObject<Properties<Verification>> {
  return z.object({
    __typename: z.literal('Verification').optional(),
    id: z.unknown().nullable(),
    link: z.unknown().nullable(),
    status: z.unknown().nullable(),
    updatedAt: z.unknown().nullable()
  })
}
