// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Oleksii PELYKH

import { chmod, mkdir, open, readFile, rename, unlink } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

import { Cookie, CookieJar, MemoryCookieStore } from "tough-cookie";

/**
 * Mozilla / Netscape cookies.txt format header. Matches what curl writes so
 * the file is round-trippable via `curl --cookie-jar` for debugging.
 *
 * Trailing newline only — the blank line that separates the header block from
 * the first data row is added by the join in `saveCookieJar`.
 */
const MOZILLA_HEADER =
  "# Netscape HTTP Cookie File\n" +
  "# https://curl.se/docs/http-cookies.html\n" +
  "# This file was generated by ttctl. Edit at your own risk.\n";

/**
 * Per the Mozilla / curl convention, HttpOnly cookies are emitted with a
 * `# HttpOnly_` prefix prepended to the domain field. Curl reads this back
 * into the HttpOnly flag.
 */
const HTTPONLY_PREFIX = "#HttpOnly_";

export interface DiscoverCookieJarPathOptions {
  /** Override `process.env`; useful for tests. */
  env?: NodeJS.ProcessEnv;
  /** Override `process.platform`; useful for tests. */
  platform?: NodeJS.Platform;
  /** Override `os.homedir()`; useful for tests. */
  homeDir?: string;
}

/**
 * Resolve the on-disk path for the persisted session cookie jar.
 *
 * Priority:
 *   - Windows: `%APPDATA%/ttctl/session.cookies`
 *     (fallback `%USERPROFILE%/AppData/Roaming/ttctl/session.cookies`).
 *   - Linux/macOS: `$XDG_DATA_HOME/ttctl/session.cookies` if `XDG_DATA_HOME`
 *     is set and non-empty (per XDG spec — empty falls back), else
 *     `~/.ttctl/session.cookies`.
 */
export function discoverCookieJarPath(opts: DiscoverCookieJarPathOptions = {}): string {
  const env = opts.env ?? process.env;
  const platform = opts.platform ?? process.platform;
  const home = opts.homeDir ?? homedir();

  if (platform === "win32") {
    const appData = env["APPDATA"];
    if (appData !== undefined && appData !== "") {
      return join(appData, "ttctl", "session.cookies");
    }
    const userProfile = env["USERPROFILE"];
    const base = userProfile !== undefined && userProfile !== "" ? userProfile : home;
    return join(base, "AppData", "Roaming", "ttctl", "session.cookies");
  }

  // POSIX: per XDG Base Directory Specification, an empty value is treated
  // as if unset.
  const xdg = env["XDG_DATA_HOME"];
  if (xdg !== undefined && xdg !== "") {
    return join(xdg, "ttctl", "session.cookies");
  }
  return join(home, ".ttctl", "session.cookies");
}

interface MozillaRow {
  domain: string;
  hostOnly: boolean;
  path: string;
  secure: boolean;
  expires: number;
  name: string;
  value: string;
  httpOnly: boolean;
}

function parseMozillaContents(text: string): MozillaRow[] {
  const rows: MozillaRow[] = [];
  for (const rawLine of text.split(/\r?\n/)) {
    if (rawLine === "") continue;
    let httpOnly = false;
    let line = rawLine;
    if (line.startsWith(HTTPONLY_PREFIX)) {
      httpOnly = true;
      line = line.slice(HTTPONLY_PREFIX.length);
    } else if (line.startsWith("#")) {
      // Comment line, skip.
      continue;
    }
    const fields = line.split("\t");
    if (fields.length < 7) {
      // Malformed row — skip silently rather than throw, matching curl's
      // tolerance for hand-edited jars.
      continue;
    }
    const [domain, includeSubdomains, path, secure, expires, name, ...rest] = fields as [
      string,
      string,
      string,
      string,
      string,
      string,
      ...string[],
    ];
    // The value field can legitimately contain tab characters (it's
    // technically the "rest of the line" per curl). Rejoin defensively.
    const value = rest.join("\t");
    const expiresNum = Number.parseInt(expires, 10);
    rows.push({
      domain,
      hostOnly: includeSubdomains.toUpperCase() !== "TRUE",
      path,
      secure: secure.toUpperCase() === "TRUE",
      expires: Number.isFinite(expiresNum) ? expiresNum : 0,
      name,
      value,
      httpOnly,
    });
  }
  return rows;
}

function rowToCookie(row: MozillaRow): Cookie {
  // Mozilla format omits creation/lastAccessed; tough-cookie sets sane
  // defaults if not provided. `expires === 0` indicates a session cookie
  // (no expiry); represent that as "Infinity" per tough-cookie convention.
  const expires: Date | "Infinity" = row.expires === 0 ? "Infinity" : new Date(row.expires * 1000);
  // tough-cookie strips a leading dot from the persisted-domain when
  // hostOnly is set; for the includeSubdomains case (hostOnly=false) the
  // dot is also redundant since tough-cookie stores the canonical form.
  const domain = row.domain.startsWith(".") ? row.domain.slice(1) : row.domain;
  return new Cookie({
    key: row.name,
    value: row.value,
    domain,
    path: row.path,
    secure: row.secure,
    httpOnly: row.httpOnly,
    expires,
    hostOnly: row.hostOnly,
  });
}

function cookieToMozillaLine(cookie: Cookie): string {
  const domain = cookie.domain ?? "";
  const path = cookie.path ?? "/";
  // hostOnly=true → cookie does NOT apply to subdomains → includeSubdomains=FALSE
  const includeSubdomains = cookie.hostOnly === true ? "FALSE" : "TRUE";
  const secure = cookie.secure ? "TRUE" : "FALSE";
  // `cookie.expires` is typed `Date | "Infinity" | null`; "Infinity" and
  // null both indicate a session cookie, encoded as 0 in Mozilla format.
  const expires = cookie.expires instanceof Date ? Math.floor(cookie.expires.getTime() / 1000) : 0;
  // Preserve the value bytes verbatim — Toptal's `_csrf_token` is sometimes
  // emitted with surrounding double quotes and any normalization would break
  // the next request.
  const prefix = cookie.httpOnly ? HTTPONLY_PREFIX : "";
  return `${prefix}${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expires.toString()}\t${cookie.key}\t${cookie.value}`;
}

/**
 * Load a {@link CookieJar} from a persisted Mozilla-format file.
 *
 * Returns an empty jar if the file does not exist (first-run case).
 * Throws on read errors other than ENOENT.
 */
export async function loadCookieJar(path: string): Promise<CookieJar> {
  let raw: string;
  try {
    raw = await readFile(path, "utf8");
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") {
      return new CookieJar(new MemoryCookieStore());
    }
    throw err;
  }
  const store = new MemoryCookieStore();
  const jar = new CookieJar(store);
  for (const row of parseMozillaContents(raw)) {
    const cookie = rowToCookie(row);
    await store.putCookie(cookie);
  }
  return jar;
}

/**
 * Persist a {@link CookieJar} to disk in Mozilla cookies.txt format.
 *
 * Atomic on POSIX: writes to a sibling `*.tmp` file with mode `0o600`,
 * fsyncs, then renames over the destination. A crash mid-write leaves
 * either the previous valid file or the new valid file — never a partial.
 *
 * Permissions are `0o600` on Unix. Windows ignores the mode; the file
 * lives under the user's profile directory which already restricts access
 * to the owning user via NTFS ACLs.
 */
export async function saveCookieJar(path: string, jar: CookieJar): Promise<void> {
  const serialized = await jar.serialize();
  const lines: string[] = [MOZILLA_HEADER];
  for (const sc of serialized.cookies) {
    const restored = Cookie.fromJSON(sc);
    if (restored !== undefined) {
      lines.push(cookieToMozillaLine(restored));
    }
  }
  // Trailing newline so the file always ends cleanly.
  const content = lines.join("\n") + "\n";

  await mkdir(dirname(path), { recursive: true });

  const tmpPath = `${path}.tmp`;
  // O_WRONLY | O_CREAT | O_TRUNC with mode 0o600. Existing tmp left over
  // from a prior crashed write is overwritten.
  const fh = await open(tmpPath, "w", 0o600);
  try {
    await fh.writeFile(content, "utf8");
    await fh.sync();
  } finally {
    await fh.close();
  }
  // Defensive re-chmod in case the umask filtered the open() mode (some
  // shells set umask 077, others 022 — the open mode is masked through it).
  if (process.platform !== "win32") {
    try {
      await chmod(tmpPath, 0o600);
    } catch {
      // chmod can fail on filesystems that don't support POSIX perms (e.g.
      // some FUSE mounts). Don't block the save — the rename below will
      // still produce a valid file.
    }
  }
  try {
    await rename(tmpPath, path);
  } catch (err) {
    // Best-effort cleanup of the temp file if the rename failed.
    try {
      await unlink(tmpPath);
    } catch {
      /* ignore */
    }
    throw err;
  }
  // Fsync the parent directory so the rename's metadata reaches disk —
  // without this, a power-loss between rename and the next implicit metadata
  // flush can leave the file invisible despite the data being durable. POSIX
  // requires opening the directory for read; not supported on Windows, where
  // the rename's NTFS journaling already covers this.
  if (process.platform !== "win32") {
    try {
      const dirHandle = await open(dirname(path), "r");
      try {
        await dirHandle.sync();
      } finally {
        await dirHandle.close();
      }
    } catch {
      // Some filesystems (FUSE, network mounts) refuse fsync on directory
      // handles. The rename already succeeded; skipping the dir-fsync only
      // weakens power-loss durability, not process-crash atomicity.
    }
  }
}
