// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Oleksii PELYKH

import { describe, expect, it } from "vitest";

import type { AllocatedHoursChangeRequestStatus, UserError } from "../__generated__/zod-schemas.js";
import { AllocatedHoursChangeRequestStatusSchema, UserErrorSchema } from "../__generated__/zod-schemas.js";

/**
 * Smoke test for Z-2 (#284) Zod codegen wiring: verifies that
 * `pnpm codegen` produces importable, well-formed Zod schemas alongside
 * their TS-type counterparts in `__generated__/zod-schemas.ts`, and that
 * the schemas parse hand-rolled wire-shape payloads correctly.
 *
 * The Zod schemas are generated by `graphql-codegen-typescript-validation-schema`
 * v0.19.0 with `nullishBehavior: "nullable"` (see `codegen.config.ts`
 * § ZOD_PLUGIN_CONFIG): nullable GraphQL fields → Zod `.nullable()`,
 * NOT `.nullish()` — keeping the Zod parse type aligned with the
 * project's `Maybe<T> = T | null` TS contract under
 * `exactOptionalPropertyTypes: true`.
 *
 * Track 2 of the hybrid wire-validation model (ADR-006) wires these
 * schemas through `callGateway`/`callTalentProfile` in Z-3 (#286);
 * this test only validates the codegen path. Schemas are dormant in
 * @ttctl/core source until Z-3 lands.
 */
describe("zod-schemas codegen (Z-2 / #284)", () => {
  it("parses a valid AllocatedHoursChangeRequestStatus payload (required-fields shape)", () => {
    const status = AllocatedHoursChangeRequestStatusSchema();
    const sample = {
      __typename: "AllocatedHoursChangeRequestStatus",
      value: "PENDING",
      verbose: "Pending review",
    };
    const parsed = status.parse(sample);
    expect(parsed.value).toBe("PENDING");
    expect(parsed.verbose).toBe("Pending review");
  });

  it("accepts payloads with or without __typename (skipTypename emits optional literal)", () => {
    const status = AllocatedHoursChangeRequestStatusSchema();
    // Server may or may not include __typename depending on Apollo client config.
    expect(() => status.parse({ value: "ACTIVE", verbose: "Active" })).not.toThrow();
    expect(() =>
      status.parse({ __typename: "AllocatedHoursChangeRequestStatus", value: "ACTIVE", verbose: "Active" }),
    ).not.toThrow();
  });

  it("parses a UserError payload with all nullable fields present and null", () => {
    const userError = UserErrorSchema();
    const allPresent: UserError = {
      code: "E_VALIDATION",
      key: "name",
      message: "Name is required.",
    };
    const allNull: UserError = {
      code: null,
      key: null,
      message: null,
    };
    expect(userError.parse(allPresent)).toStrictEqual(allPresent);
    expect(userError.parse(allNull)).toStrictEqual(allNull);
  });

  it("rejects payloads with the wrong wire shape (drift-detection assertion)", () => {
    const status = AllocatedHoursChangeRequestStatusSchema();
    // `value` declared `String` on the wire — a numeric value would be drift.
    expect(() => status.parse({ value: 42, verbose: "Active" })).toThrow();
    // Missing required `verbose` is also drift.
    expect(() => status.parse({ value: "ACTIVE" })).toThrow();
  });

  it("imports TS-type companions without `__typename` (skipTypename: true)", () => {
    // Compile-time assertion: the TS type emitted in zod-schemas.ts has
    // __typename stripped. Assigning an object literal with __typename to
    // `AllocatedHoursChangeRequestStatus` would fail compilation; this
    // structural-positive case proves the type compiles.
    const status: AllocatedHoursChangeRequestStatus = {
      value: "PENDING",
      verbose: "Pending review",
    };
    expect(status.value).toBe("PENDING");
  });
});
